# Run wopke_100 extraction on mapped papers

Reads markdown from `data/wopke_100/paper_output`.
Uses `src/experimentutils/papermap.py` (folder → GT `Study#`) and by default runs the **90 mapped** papers only.

Runs **direct LLM**, **static workflow**, and **MAS**. Results go to `outputs/{tag}/` as CSV. Re-run to **resume**: finished paper/method CSVs are skipped.

In [ ]:
# --- LLM (edit these; overrides .env for this run) ---
PROVIDER = "surf"
MODEL_NAME = "mistralai/Mistral-Small-3.2-24B-Instruct-2506"

# --- Paths ---
PAPER_INPUT_DIR = "data/wopke_100/paper_output"

# --- Experiment ---
STANDARD_KEY = "wopke_100"
METHODS = ["direct_llm", "static_workflow", "mas"]
SKIP_EXISTING = True  # resume 1→90; skip done methods; skip incomplete gaps behind later results
ONLY_MAPPED = True  # True = papermap folders only (90); False = all 100 folders
STUDY_IDS = None  # None = all selected papers; or GT Study# list e.g. [1, 2, 10]
SKIP_STUDY_IDS = []  # temporary: skip Study# 3 (Bulson 1997) — hung on SURF Qwen
MAS_TOPOLOGY = "pipeline"
SHOW_LOGS = True  # INFO logs from orchestrator / workflow / LLM calls
QUIET_HTTP = True  # keep httpx/httpcore/openai chatter down

In [2]:
from __future__ import annotations

import logging
import os
import re
import sys
import warnings
from datetime import datetime
from pathlib import Path

warnings.filterwarnings("ignore")

# Restore progress logs (previously silenced with logging.disable)
logging.disable(logging.NOTSET)
root = logging.getLogger()
root.handlers.clear()
logging.basicConfig(
    level=logging.INFO if SHOW_LOGS else logging.WARNING,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    datefmt="%H:%M:%S",
    force=True,
)
for name in ("httpx", "httpcore", "openai", "urllib3", "httpx._client"):
    logging.getLogger(name).setLevel(logging.WARNING if QUIET_HTTP else logging.INFO)
    logging.getLogger(name).disabled = False
# Project loggers
for name in ("src", "src.orchestrator", "src.players", "src.static_workflow", "src.direct_llm_call"):
    logging.getLogger(name).setLevel(logging.INFO if SHOW_LOGS else logging.WARNING)

repo_root = Path.cwd().resolve()
for p in [repo_root, *repo_root.parents]:
    if (p / "src").is_dir() and (p / "outputs").is_dir():
        repo_root = p
        break
if str(repo_root) not in sys.path:
    sys.path.insert(0, str(repo_root))

from dotenv import load_dotenv

load_dotenv(repo_root / ".env")
os.environ["LLM_PROVIDER"] = PROVIDER
os.environ["LLM_MODEL"] = MODEL_NAME

import src.config as cfg

cfg.LLM_PROVIDER = PROVIDER
cfg.DEFAULT_MODEL = MODEL_NAME

import pandas as pd
from tqdm.auto import tqdm

from src.context import create_context
from src.core.schema_factory import SchemaFactory
from src.direct_llm_call import extract_meta_analysis
from src.experimentutils import (
    get_all_markdown_paths,
    get_paper_info_from_path,
    highlight_numbers_and_tables,
    read_paper_text,
)
from src.experimentutils.output_utils import DEFAULT_OUTPUT_DIR
from src.experimentutils.papermap import (
    FOLDER_TO_STUDY_ID,
    UNMAPPED_FOLDERS,
    study_id_for_folder,
)
from src.orchestrator import Orchestrator
from src.standards import METADATA_STANDARDS
from src.static_workflow import run_two_step_text_to_dataset

log = logging.getLogger("run_wopke_100")

standard = METADATA_STANDARDS[STANDARD_KEY]
n_fields = len(SchemaFactory()._parse_schema_string(standard))
OutputSchema = SchemaFactory().create_from_standard(
    standard,
    record_class_name="WopkeRecord",
    output_class_name="WopkeOutput",
    records_key="yield_records",
)

provider_label = re.sub(r"[^A-Za-z0-9]+", "-", PROVIDER.strip()).strip("-")
model_label = re.sub(r"[^A-Za-z0-9]+", "-", MODEL_NAME.strip()).strip("-")
file_tag = f"{provider_label}_{model_label}_{n_fields}fields"

paper_input = Path(PAPER_INPUT_DIR)
if not paper_input.is_absolute():
    paper_input = repo_root / paper_input
if not paper_input.is_dir():
    raise FileNotFoundError(f"Paper input dir not found: {paper_input}")

run_dir = Path(DEFAULT_OUTPUT_DIR) / file_tag
by_paper_dir = run_dir / "by_paper"
by_paper_dir.mkdir(parents=True, exist_ok=True)
status_path = run_dir / "run_status.csv"


def make_paper_id(folder_name: str, study_id: int | None = None) -> str:
    m = re.match(r"^(\d+)\.\s*(.*)$", folder_name)
    rest = m.group(2) if m else folder_name
    slug = re.sub(r"[^A-Za-z0-9]+", "_", rest).strip("_")[:50]
    if study_id is not None:
        return f"{int(study_id):03d}_{slug}"
    if m:
        return f"{int(m.group(1)):03d}_{slug}"
    return slug[:80]


papers = []
for md_path in get_all_markdown_paths(base_dir=str(paper_input)):
    info = get_paper_info_from_path(md_path)
    folder = info["paper_folder"]
    study_id = study_id_for_folder(folder)
    if ONLY_MAPPED and study_id is None:
        continue
    papers.append(
        {
            "paper_id": make_paper_id(folder, study_id),
            "paper_folder": folder,
            "path": md_path,
            "study_id": study_id,
            "study_ids": [study_id] if study_id is not None else [],
        }
    )

if STUDY_IDS is not None:
    wanted = {int(s) for s in STUDY_IDS}
    papers = [p for p in papers if p["study_id"] in wanted]

skip_ids = {int(s) for s in (SKIP_STUDY_IDS or [])}
if skip_ids:
    before = len(papers)
    papers = [p for p in papers if p["study_id"] not in skip_ids]
    print(f"Skipped Study# {sorted(skip_ids)} ({before - len(papers)} papers)")

# Study# ascending (1→90); unfinished methods are picked up in METHODS order.
papers.sort(
    key=lambda p: (
        p["study_id"] is None,  # mapped first
        p["study_id"] if p["study_id"] is not None else 10**9,  # smallest Study# first
        p["paper_folder"],
    )
)


def method_done(paper_id: str, method: str) -> bool:
    path = by_paper_dir / f"{paper_id}__{method}.csv"
    return path.is_file() and path.stat().st_size > 0


def pending_methods(paper_id: str) -> list[str]:
    if not SKIP_EXISTING:
        return list(METHODS)
    return [m for m in METHODS if not method_done(paper_id, m)]


def paper_has_any_result(paper_id: str) -> bool:
    return any(method_done(paper_id, m) for m in METHODS)


def later_paper_has_progress(idx: int) -> bool:
    """True if any later Study# already has at least one method CSV."""
    for p in papers[idx + 1 :]:
        if paper_has_any_result(p["paper_id"]):
            return True
    return False


# Inventory existing by_paper outputs for resume.
# Incomplete papers behind a later finished paper are treated as abandoned
# (failed/skipped last time) and are not retried.
n_method_done = {m: 0 for m in METHODS}
n_paper_complete = 0
n_paper_partial = 0
n_paper_todo = 0
n_paper_gap_skip = 0
first_resume = None
for idx, p in enumerate(papers):
    pending = pending_methods(p["paper_id"])
    done_here = [m for m in METHODS if m not in pending]
    for m in done_here:
        n_method_done[m] += 1
    if not pending:
        n_paper_complete += 1
        continue
    if SKIP_EXISTING and later_paper_has_progress(idx):
        n_paper_gap_skip += 1
        continue
    if len(pending) < len(METHODS):
        n_paper_partial += 1
    else:
        n_paper_todo += 1
    if first_resume is None:
        first_resume = (p, pending)

n_mapped = sum(1 for p in papers if p["study_id"] is not None)
print(f"LLM      : {PROVIDER}/{MODEL_NAME}")
print(f"Standard : {STANDARD_KEY} ({n_fields} fields)")
print(f"Methods  : {METHODS}")
print(f"Input    : {paper_input}")
print(f"Papermap : {len(FOLDER_TO_STUDY_ID)} folders → Study# (unmapped folders: {len(UNMAPPED_FOLDERS)})")
print(f"Papers   : {len(papers)} (ONLY_MAPPED={ONLY_MAPPED})")
print(f"Mapped   : {n_mapped}/{len(papers)} have a GT Study#")
print(f"Output   : {run_dir}")
print(f"Tag      : {file_tag}")
print(f"Order    : Study# ascending (1→90)")
print(f"Resume   : SKIP_EXISTING={SKIP_EXISTING}")
print(
    f"Progress : complete={n_paper_complete} partial={n_paper_partial} "
    f"todo={n_paper_todo} gap_skip={n_paper_gap_skip} "
    f"| per-method done={dict(n_method_done)}"
)
if first_resume is not None:
    p0, pending0 = first_resume
    print(
        f"Next     : Study {p0['study_id']} · {p0['paper_id']} "
        f"→ pending {pending0}"
    )
else:
    print("Next     : nothing left (all selected papers × methods done)")
print(f"Logs     : SHOW_LOGS={SHOW_LOGS} QUIET_HTTP={QUIET_HTTP}")
log.info("Setup complete — ready to run %d papers", len(papers))

10:02:40 | INFO | run_wopke_100 | Setup complete — ready to run 89 papers

Skipped Study# [3] (1 papers)
LLM      : surf/mistralai/Mistral-Small-3.2-24B-Instruct-2506
Standard : wopke_100 (42 fields)
Methods  : ['direct_llm', 'static_workflow', 'mas']
Input    : /home/com3dian/Github/meta_analysis_agents/data/wopke_100/paper_output
Papermap : 90 folders → Study# (unmapped folders: 10)
Papers   : 89 (ONLY_MAPPED=True)
Mapped   : 89/89 have a GT Study#
Output   : /home/com3dian/Github/meta_analysis_agents/outputs/surf_mistralai-Mistral-Small-3-2-24B-Instruct-2506_42fields
Tag      : surf_mistralai-Mistral-Small-3-2-24B-Instruct-2506_42fields
Logs     : SHOW_LOGS=True QUIET_HTTP=True

In [3]:
mas_objective = f"""You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:
{standard}

**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.
"""

def paper_csv_path(paper_id: str, method: str) -> Path:
    return by_paper_dir / f"{paper_id}__{method}.csv"


def output_exists(paper_id: str, method: str) -> bool:
    path = paper_csv_path(paper_id, method)
    return path.is_file() and path.stat().st_size > 0


def records_to_df(results) -> pd.DataFrame:
    if hasattr(results, "model_dump"):
        payload = results.model_dump()
    elif hasattr(results, "dict"):
        payload = results.dict()
    elif isinstance(results, dict):
        payload = results
    else:
        raise TypeError(f"Unsupported results type: {type(results)}")
    records = payload.get("yield_records") or payload.get("records") or []
    if not isinstance(records, list):
        records = [records]
    rows_out = []
    for rec in records:
        if hasattr(rec, "model_dump"):
            rows_out.append(rec.model_dump())
        elif isinstance(rec, dict):
            rows_out.append(rec)
    return pd.DataFrame(rows_out)


def save_records(results, paper: dict, method: str) -> tuple[str, int]:
    df = records_to_df(results)
    df.insert(0, "paper_folder", paper["paper_folder"])
    df.insert(0, "method", method)
    df.insert(0, "study_ids", ";".join(str(s) for s in paper["study_ids"]))
    df.insert(0, "study_id", paper["study_id"] if paper["study_id"] is not None else "")
    df.insert(0, "paper_id", paper["paper_id"])
    path = paper_csv_path(paper["paper_id"], method)
    tmp = path.with_suffix(".csv.tmp")
    df.to_csv(tmp, index=False)
    tmp.replace(path)
    return str(path), len(df)


def rebuild_combined(method: str) -> str | None:
    parts = sorted(by_paper_dir.glob(f"*__{method}.csv"))
    if not parts:
        return None
    frames = [pd.read_csv(p) for p in parts]
    out = run_dir / f"{method}.csv"
    pd.concat(frames, ignore_index=True).to_csv(out, index=False)
    return str(out)


def write_status(rows: list[dict]) -> None:
    pd.DataFrame(rows).to_csv(status_path, index=False)


def parse_mas_records(result_mas):
    if result_mas is None:
        return None
    workspace = getattr(result_mas, "final_workspace", None) or {}
    raw = workspace.get("final_meta_analysis_records", {})
    if isinstance(raw, OutputSchema):
        return raw
    if isinstance(raw, dict):
        return OutputSchema.model_validate(raw)
    return None


def run_direct(paper_path: str):
    return extract_meta_analysis(
        paper_path,
        schema=standard,
        provider=PROVIDER,
        model_name=MODEL_NAME,
        debug_raw_response=False,
    )


def run_workflow(paper_path: str):
    text = highlight_numbers_and_tables(read_paper_text(paper_path))
    out = run_two_step_text_to_dataset(
        text=text,
        workflow="label_then_direct",
        dataset_standard=standard,
        dataset_records_key="yield_records",
        record_class_name="WopkeRecord",
        output_class_name="WopkeOutput",
        label_step2_prompt_style="direct_full",
        label_step2_include_tag_note=True,
        label_step2_maximize_completeness=True,
        labeled_text_max_chars=120_000,
        provider=PROVIDER,
        model_name=MODEL_NAME,
    )
    return out.get("schema_output")


def run_mas(paper_path: str, paper_id: str):
    context = create_context(source=paper_path, name=f"paper_{paper_id}")
    orchestrator = Orchestrator(
        topology_name=MAS_TOPOLOGY,
        provider=PROVIDER,
        model_name=MODEL_NAME,
    )
    result = orchestrator.run(
        source=context,
        objective=mas_objective,
        output_schema=OutputSchema,
    )
    return parse_mas_records(result)

In [4]:
import time
from datetime import datetime

runners = {
    "direct_llm": lambda path, paper: run_direct(path),
    "static_workflow": lambda path, paper: run_workflow(path),
    "mas": lambda path, paper: run_mas(path, paper["paper_id"]),
}

for method in METHODS:
    rebuild_combined(method)

rows = []
done_ok = done_skip = done_fail = 0
t0_all = time.perf_counter()


def progress(msg: str) -> None:
    line = f"{datetime.now().strftime('%H:%M:%S')} | {msg}"
    tqdm.write(line)
    log.info(msg)


n_jobs = 0
for idx, p in enumerate(papers):
    pending = pending_methods(p["paper_id"])
    if not pending:
        continue
    if SKIP_EXISTING and later_paper_has_progress(idx):
        continue
    n_jobs += len(pending)

progress(
    f"Starting run: {len(papers)} papers × {METHODS} "
    f"({n_jobs} remaining jobs) → {run_dir}"
)

pbar = tqdm(papers, desc="Papers", unit="paper")
for i, paper in enumerate(pbar, start=1):
    paper_id = paper["paper_id"]
    paper_path = paper["path"]
    idx = i - 1
    pending = pending_methods(paper_id)
    if SKIP_EXISTING and not pending:
        # All 3 experiments already done — move to next Study#.
        done_skip += len(METHODS)
        for method in METHODS:
            n_rec = None
            try:
                n_rec = max(len(pd.read_csv(paper_csv_path(paper_id, method))), 0)
            except Exception:
                pass
            rows.append(
                {
                    "paper_id": paper_id,
                    "study_id": paper["study_id"],
                    "method": method,
                    "status": "skipped",
                    "n_records": n_rec,
                    "path": str(paper_csv_path(paper_id, method)),
                }
            )
        write_status(rows)
        progress(
            f"[{i}/{len(papers)}] Study {paper['study_id']} · {paper_id[:50]} "
            f"— all {len(METHODS)} methods done, next"
        )
        continue

    # Incomplete, but a later paper already has results → abandoned last run; don't retry.
    if SKIP_EXISTING and later_paper_has_progress(idx):
        done_skip += len(pending)
        for method in pending:
            rows.append(
                {
                    "paper_id": paper_id,
                    "study_id": paper["study_id"],
                    "method": method,
                    "status": "skipped_gap",
                    "n_records": 0,
                    "path": "",
                }
            )
        write_status(rows)
        progress(
            f"[{i}/{len(papers)}] Study {paper['study_id']} · {paper_id[:50]} "
            f"— incomplete {pending}, but later paper has results → skip gap, next"
        )
        continue

    progress(
        f"[{i}/{len(papers)}] Study {paper['study_id']} · {paper_id[:50]} "
        f"— pending {pending}"
    )
    for method in METHODS:
        pbar.set_postfix_str(f"{paper_id[:24]} · {method}", refresh=True)
        if SKIP_EXISTING and output_exists(paper_id, method):
            n_rec = None
            try:
                n_rec = max(len(pd.read_csv(paper_csv_path(paper_id, method))), 0)
            except Exception:
                pass
            rows.append(
                {
                    "paper_id": paper_id,
                    "study_id": paper["study_id"],
                    "method": method,
                    "status": "skipped",
                    "n_records": n_rec,
                    "path": str(paper_csv_path(paper_id, method)),
                }
            )
            write_status(rows)
            done_skip += 1
            progress(f"  skip  {method} (existing, n_records={n_rec})")
            continue
        progress(f"  start {method} …")
        t0 = time.perf_counter()
        try:
            result = runners[method](paper_path, paper)
            elapsed = time.perf_counter() - t0
            if result is None:
                rows.append(
                    {
                        "paper_id": paper_id,
                        "study_id": paper["study_id"],
                        "method": method,
                        "status": "no_output",
                        "n_records": 0,
                        "path": "",
                    }
                )
                write_status(rows)
                done_fail += 1
                progress(f"  fail  {method} (no_output) in {elapsed:.1f}s")
                continue
            path, n_rec = save_records(result, paper, method)
            rebuild_combined(method)
            rows.append(
                {
                    "paper_id": paper_id,
                    "study_id": paper["study_id"],
                    "method": method,
                    "status": "ok",
                    "n_records": n_rec,
                    "path": path,
                }
            )
            write_status(rows)
            done_ok += 1
            progress(f"  ok    {method}: {n_rec} records in {elapsed:.1f}s → {Path(path).name}")
        except Exception as exc:
            elapsed = time.perf_counter() - t0
            rows.append(
                {
                    "paper_id": paper_id,
                    "study_id": paper["study_id"],
                    "method": method,
                    "status": f"error: {type(exc).__name__}: {exc}",
                    "n_records": 0,
                    "path": "",
                }
            )
            write_status(rows)
            done_fail += 1
            progress(f"  error {method} after {elapsed:.1f}s: {type(exc).__name__}: {exc}")

for method in METHODS:
    rebuild_combined(method)

elapsed_all = time.perf_counter() - t0_all
progress(
    f"Finished in {elapsed_all/60:.1f} min — ok={done_ok} skipped={done_skip} failed={done_fail}"
)

summary = pd.DataFrame(rows)
summary

10:02:40 | INFO | run_wopke_100 | Starting run: 89 papers × ['direct_llm', 'static_workflow', 'mas'] → /home/com3dian/Github/meta_analysis_agents/outputs/surf_mistralai-Mistral-Small-3-2-24B-Instruct-2506_42fields

10:02:40 | Starting run: 89 papers × ['direct_llm', 'static_workflow', 'mas'] → /home/com3dian/Github/meta_analysis_agents/outputs/surf_mistralai-Mistral-Small-3-2-24B-Instruct-2506_42fields

Papers:   0%|          | 0/89 [00:00<?, ?paper/s]

10:02:40 | INFO | run_wopke_100 | [1/89] Study 1 · 001_Jensen_1996_Grain_yield_symbiotic_N2_fixation_
10:02:40 | INFO | run_wopke_100 |   start direct_llm …

10:02:40 | [1/89] Study 1 · 001_Jensen_1996_Grain_yield_symbiotic_N2_fixation_
10:02:40 |   start direct_llm …

10:02:41 | INFO | run_wopke_100 |   error direct_llm after 1.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:41 | INFO | run_wopke_100 |   start static_workflow …
10:02:41 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=69254 use_llm=False max_facts=200
10:02:41 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:41 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=69254) — output should be much shorter than the full paper
10:02:41 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=77901); calling LLM…

10:02:41 |   error direct_llm after 1.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:41 |   start static_workflow …

10:02:41 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:41 | INFO | run_wopke_100 |   start mas …
10:02:41 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:41 | INFO | root |   Players per step: 1
10:02:41 | INFO | root |   Debate rounds: 0
10:02:41 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:41 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:41 | INFO | root | ============================================================
10:02:41 | INFO | root | STARTING ORCHESTRATION
10:02:41 | INFO | root | Context: paper_001_Jensen_1996_Grain_yield_symbiotic_N2_fixation_and_
10:02:41 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:41 | INFO | root | Output schema: WopkeOutput
10:02:41 | INFO | root | ============================================================
10:02:41 | INFO | root | ============================================================
10:02:41 | INFO | root | GENERATING PLAN
10:02:41 | INFO | root | Context: paper_001_Jensen_1996_Grain_yield_symbiotic_N2_fixation_and_
10:02:41 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:41 | INFO | root | ============================================================
10:02:41 | INFO | root | Context info:
10:02:41 | INFO | root | Context Name: paper_001_Jensen_1996_Grain_yield_symbiotic_N2_fixation_and_
Resources: Jensen 1996 Grain yield, symbiotic N2 fixation and interspecific competition for inorganic N in pea-barley
10:02:41 | INFO | root | ----------------------------------------
10:02:41 | INFO | root | Available players manifest
10:02:41 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:41 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:41 |   start mas …
10:02:41 |   fail  mas (no_output) in 0.1s
10:02:41 | [2/89] Study 2 · 002_Hauggaard_Nielsen_2001_Interspecific_competiti
10:02:41 |   start direct_llm …

10:02:42 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:42 | INFO | run_wopke_100 |   start static_workflow …
10:02:42 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=43360 use_llm=False max_facts=200
10:02:42 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:42 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=43360) — output should be much shorter than the full paper
10:02:42 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=52007); calling LLM…

10:02:42 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:42 |   start static_workflow …

10:02:42 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:42 | INFO | run_wopke_100 |   start mas …
10:02:42 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:42 | INFO | root |   Players per step: 1
10:02:42 | INFO | root |   Debate rounds: 0
10:02:42 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:42 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:42 | INFO | root | ============================================================
10:02:42 | INFO | root | STARTING ORCHESTRATION
10:02:42 | INFO | root | Context: paper_002_Hauggaard_Nielsen_2001_Interspecific_competition_N
10:02:42 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:42 | INFO | root | Output schema: WopkeOutput
10:02:42 | INFO | root | ============================================================
10:02:42 | INFO | root | ============================================================
10:02:42 | INFO | root | GENERATING PLAN
10:02:42 | INFO | root | Context: paper_002_Hauggaard_Nielsen_2001_Interspecific_competition_N
10:02:42 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:42 | INFO | root | ============================================================
10:02:42 | INFO | root | Context info:
10:02:42 | INFO | root | Context Name: paper_002_Hauggaard_Nielsen_2001_Interspecific_competition_N
Resources: Hauggaard-Nielsen 2001 Interspecific competition, N use and interference with weeds in pea-barley
10:02:42 | INFO | root | ----------------------------------------
10:02:42 | INFO | root | Available players manifest
10:02:42 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:42 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:42 |   start mas …
10:02:42 |   fail  mas (no_output) in 0.1s
10:02:42 | [3/89] Study 4 · 004_Li_2001_Wheat_maize_or_wheat_soybean_strip_int
10:02:42 |   start direct_llm …

10:02:42 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:42 | INFO | run_wopke_100 |   start static_workflow …
10:02:43 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=78282 use_llm=False max_facts=200
10:02:43 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:43 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=78282) — output should be much shorter than the full paper
10:02:43 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=86929); calling LLM…

10:02:42 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:42 |   start static_workflow …

10:02:43 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:43 | INFO | run_wopke_100 |   start mas …
10:02:43 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:43 | INFO | root |   Players per step: 1
10:02:43 | INFO | root |   Debate rounds: 0
10:02:43 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:43 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:43 | INFO | root | ============================================================
10:02:43 | INFO | root | STARTING ORCHESTRATION
10:02:43 | INFO | root | Context: paper_004_Li_2001_Wheat_maize_or_wheat_soybean_strip_intercr
10:02:43 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:43 | INFO | root | Output schema: WopkeOutput
10:02:43 | INFO | root | ============================================================
10:02:43 | INFO | root | ============================================================
10:02:43 | INFO | root | GENERATING PLAN
10:02:43 | INFO | root | Context: paper_004_Li_2001_Wheat_maize_or_wheat_soybean_strip_intercr
10:02:43 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:43 | INFO | root | ============================================================
10:02:43 | INFO | root | Context info:
10:02:43 | INFO | root | Context Name: paper_004_Li_2001_Wheat_maize_or_wheat_soybean_strip_intercr
Resources: Li 2001 Wheat-maize or wheat-soybean strip intercropping I. Yield advantage and inerspecific interactions
10:02:43 | INFO | root | ----------------------------------------
10:02:43 | INFO | root | Available players manifest
10:02:43 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:43 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:43 |   start mas …
10:02:43 |   fail  mas (no_output) in 0.1s
10:02:43 | [4/89] Study 5 · 005_Li_1999_Interspecific_complementary_and_compet
10:02:43 |   start direct_llm …

10:02:43 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:43 | INFO | run_wopke_100 |   start static_workflow …
10:02:43 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=46443 use_llm=False max_facts=200
10:02:43 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:43 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=46443) — output should be much shorter than the full paper
10:02:43 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=55090); calling LLM…

10:02:43 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:43 |   start static_workflow …

10:02:43 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:44 | INFO | run_wopke_100 |   start mas …
10:02:44 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:44 | INFO | root |   Players per step: 1
10:02:44 | INFO | root |   Debate rounds: 0
10:02:44 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:44 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:44 | INFO | root | ============================================================
10:02:44 | INFO | root | STARTING ORCHESTRATION
10:02:44 | INFO | root | Context: paper_005_Li_1999_Interspecific_complementary_and_competitiv
10:02:44 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:44 | INFO | root | Output schema: WopkeOutput
10:02:44 | INFO | root | ============================================================
10:02:44 | INFO | root | ============================================================
10:02:44 | INFO | root | GENERATING PLAN
10:02:44 | INFO | root | Context: paper_005_Li_1999_Interspecific_complementary_and_competitiv
10:02:44 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:44 | INFO | root | ============================================================
10:02:44 | INFO | root | Context info:
10:02:44 | INFO | root | Context Name: paper_005_Li_1999_Interspecific_complementary_and_competitiv
Resources: Li 1999 Interspecific complementary and competitive interactions between intercropped maize and faba bean
10:02:44 | INFO | root | ----------------------------------------
10:02:44 | INFO | root | Available players manifest
10:02:44 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:43 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:44 |   start mas …
10:02:44 |   fail  mas (no_output) in 0.1s
10:02:44 | [5/89] Study 6 · 006_Hauggaard_Nielson_2003_The_comparison_of_nitro
10:02:44 |   start direct_llm …

10:02:44 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:44 | INFO | run_wopke_100 |   start static_workflow …
10:02:44 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=61651 use_llm=False max_facts=200
10:02:44 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:44 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=61651) — output should be much shorter than the full paper
10:02:44 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=70298); calling LLM…

10:02:44 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:44 |   start static_workflow …

10:02:44 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:44 | INFO | run_wopke_100 |   start mas …
10:02:44 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:44 | INFO | root |   Players per step: 1
10:02:44 | INFO | root |   Debate rounds: 0
10:02:44 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:44 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:44 | INFO | root | ============================================================
10:02:44 | INFO | root | STARTING ORCHESTRATION
10:02:44 | INFO | root | Context: paper_006_Hauggaard_Nielson_2003_The_comparison_of_nitrogen_
10:02:44 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:44 | INFO | root | Output schema: WopkeOutput
10:02:44 | INFO | root | ============================================================
10:02:44 | INFO | root | ============================================================
10:02:44 | INFO | root | GENERATING PLAN
10:02:44 | INFO | root | Context: paper_006_Hauggaard_Nielson_2003_The_comparison_of_nitrogen_
10:02:44 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:44 | INFO | root | ============================================================
10:02:44 | INFO | root | Context info:
10:02:44 | INFO | root | Context Name: paper_006_Hauggaard_Nielson_2003_The_comparison_of_nitrogen_
Resources: Hauggaard-Nielson 2003 The comparison of nitrogen use and leaching in sole cropped versus intercropped
10:02:44 | INFO | root | ----------------------------------------
10:02:44 | INFO | root | Available players manifest
10:02:44 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:44 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:44 |   start mas …
10:02:44 |   fail  mas (no_output) in 0.1s
10:02:44 | [6/89] Study 7 · 007_Hauggaard_Nielsen_2001_Evaluating_pea_and_barl
10:02:44 |   start direct_llm …

10:02:45 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:45 | INFO | run_wopke_100 |   start static_workflow …
10:02:45 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=54174 use_llm=False max_facts=200
10:02:45 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:45 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=54174) — output should be much shorter than the full paper
10:02:45 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=62821); calling LLM…

10:02:45 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:45 |   start static_workflow …

10:02:45 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:45 | INFO | run_wopke_100 |   start mas …
10:02:45 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:45 | INFO | root |   Players per step: 1
10:02:45 | INFO | root |   Debate rounds: 0
10:02:45 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:45 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:45 | INFO | root | ============================================================
10:02:45 | INFO | root | STARTING ORCHESTRATION
10:02:45 | INFO | root | Context: paper_007_Hauggaard_Nielsen_2001_Evaluating_pea_and_barley_c
10:02:45 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:45 | INFO | root | Output schema: WopkeOutput
10:02:45 | INFO | root | ============================================================
10:02:45 | INFO | root | ============================================================
10:02:45 | INFO | root | GENERATING PLAN
10:02:45 | INFO | root | Context: paper_007_Hauggaard_Nielsen_2001_Evaluating_pea_and_barley_c
10:02:45 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:45 | INFO | root | ============================================================
10:02:45 | INFO | root | Context info:
10:02:45 | INFO | root | Context Name: paper_007_Hauggaard_Nielsen_2001_Evaluating_pea_and_barley_c
Resources: Hauggaard-Nielsen 2001 Evaluating pea and barley cultivars for complementarity in intercropping
10:02:45 | INFO | root | ----------------------------------------
10:02:45 | INFO | root | Available players manifest
10:02:45 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:45 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:45 |   start mas …
10:02:45 |   fail  mas (no_output) in 0.1s
10:02:45 | [7/89] Study 8 · 008_Li_et_al_2006_Root_distribution_and_interactio
10:02:45 |   start direct_llm …

10:02:45 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:45 | INFO | run_wopke_100 |   start static_workflow …
10:02:45 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=59684 use_llm=False max_facts=200
10:02:45 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:45 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=59684) — output should be much shorter than the full paper
10:02:45 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=68331); calling LLM…

10:02:45 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:45 |   start static_workflow …

10:02:46 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:46 | INFO | run_wopke_100 |   start mas …
10:02:46 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:46 | INFO | root |   Players per step: 1
10:02:46 | INFO | root |   Debate rounds: 0
10:02:46 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:46 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:46 | INFO | root | ============================================================
10:02:46 | INFO | root | STARTING ORCHESTRATION
10:02:46 | INFO | root | Context: paper_008_Li_et_al_2006_Root_distribution_and_interactions_b
10:02:46 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:46 | INFO | root | Output schema: WopkeOutput
10:02:46 | INFO | root | ============================================================
10:02:46 | INFO | root | ============================================================
10:02:46 | INFO | root | GENERATING PLAN
10:02:46 | INFO | root | Context: paper_008_Li_et_al_2006_Root_distribution_and_interactions_b
10:02:46 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:46 | INFO | root | ============================================================
10:02:46 | INFO | root | Context info:
10:02:46 | INFO | root | Context Name: paper_008_Li_et_al_2006_Root_distribution_and_interactions_b
Resources: Li et al 2006 Root distribution and interactions between intercropped species
10:02:46 | INFO | root | ----------------------------------------
10:02:46 | INFO | root | Available players manifest
10:02:46 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:46 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:46 |   start mas …
10:02:46 |   fail  mas (no_output) in 0.1s
10:02:46 | [8/89] Study 9 · 009_Ghosh_2004_Growth_yield_competition_and_econom
10:02:46 |   start direct_llm …

10:02:46 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:46 | INFO | run_wopke_100 |   start static_workflow …
10:02:46 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=51792 use_llm=False max_facts=200
10:02:46 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:46 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=51792) — output should be much shorter than the full paper
10:02:46 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=60439); calling LLM…

10:02:46 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:46 |   start static_workflow …

10:02:46 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:46 | INFO | run_wopke_100 |   start mas …
10:02:46 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:46 | INFO | root |   Players per step: 1
10:02:46 | INFO | root |   Debate rounds: 0
10:02:46 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:46 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:46 | INFO | root | ============================================================
10:02:46 | INFO | root | STARTING ORCHESTRATION
10:02:46 | INFO | root | Context: paper_009_Ghosh_2004_Growth_yield_competition_and_economics_
10:02:46 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:46 | INFO | root | Output schema: WopkeOutput
10:02:46 | INFO | root | ============================================================
10:02:46 | INFO | root | ============================================================
10:02:46 | INFO | root | GENERATING PLAN
10:02:46 | INFO | root | Context: paper_009_Ghosh_2004_Growth_yield_competition_and_economics_
10:02:46 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:46 | INFO | root | ============================================================
10:02:46 | INFO | root | Context info:
10:02:46 | INFO | root | Context Name: paper_009_Ghosh_2004_Growth_yield_competition_and_economics_
Resources: Ghosh 2004 Growth, yield, competition and economics of groundnut-cereal fodder intercropping systems
10:02:46 | INFO | root | ----------------------------------------
10:02:46 | INFO | root | Available players manifest
10:02:46 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:46 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:46 |   start mas …
10:02:46 |   fail  mas (no_output) in 0.1s
10:02:46 | [9/89] Study 10 · 010_Dhima_2006_Competition_indices_of_common_vetch
10:02:46 |   start direct_llm …

10:02:47 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:47 | INFO | run_wopke_100 |   start static_workflow …
10:02:47 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=49568 use_llm=False max_facts=200
10:02:47 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:47 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=49568) — output should be much shorter than the full paper
10:02:47 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=58215); calling LLM…

10:02:47 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:47 |   start static_workflow …

10:02:47 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:47 | INFO | run_wopke_100 |   start mas …
10:02:47 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:47 | INFO | root |   Players per step: 1
10:02:47 | INFO | root |   Debate rounds: 0
10:02:47 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:47 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:47 | INFO | root | ============================================================
10:02:47 | INFO | root | STARTING ORCHESTRATION
10:02:47 | INFO | root | Context: paper_010_Dhima_2006_Competition_indices_of_common_vetch_and
10:02:47 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:47 | INFO | root | Output schema: WopkeOutput
10:02:47 | INFO | root | ============================================================
10:02:47 | INFO | root | ============================================================
10:02:47 | INFO | root | GENERATING PLAN
10:02:47 | INFO | root | Context: paper_010_Dhima_2006_Competition_indices_of_common_vetch_and
10:02:47 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:47 | INFO | root | ============================================================
10:02:47 | INFO | root | Context info:
10:02:47 | INFO | root | Context Name: paper_010_Dhima_2006_Competition_indices_of_common_vetch_and
Resources: Dhima 2006 Competition indices of common vetch and cereal intercrops in two seeding ratio
10:02:47 | INFO | root | ----------------------------------------
10:02:47 | INFO | root | Available players manifest
10:02:47 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:47 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:47 |   start mas …
10:02:47 |   fail  mas (no_output) in 0.1s
10:02:47 | [10/89] Study 11 · 011_Andersen_2004_Biomass_production_symbiotic_nit
10:02:47 |   start direct_llm …

10:02:47 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:47 | INFO | run_wopke_100 |   start static_workflow …
10:02:47 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=66665 use_llm=False max_facts=200
10:02:47 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:47 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=66665) — output should be much shorter than the full paper
10:02:47 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=75312); calling LLM…

10:02:47 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:47 |   start static_workflow …

10:02:48 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:48 | INFO | run_wopke_100 |   start mas …
10:02:48 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:48 | INFO | root |   Players per step: 1
10:02:48 | INFO | root |   Debate rounds: 0
10:02:48 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:48 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:48 | INFO | root | ============================================================
10:02:48 | INFO | root | STARTING ORCHESTRATION
10:02:48 | INFO | root | Context: paper_011_Andersen_2004_Biomass_production_symbiotic_nitroge
10:02:48 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:48 | INFO | root | Output schema: WopkeOutput
10:02:48 | INFO | root | ============================================================
10:02:48 | INFO | root | ============================================================
10:02:48 | INFO | root | GENERATING PLAN
10:02:48 | INFO | root | Context: paper_011_Andersen_2004_Biomass_production_symbiotic_nitroge
10:02:48 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:48 | INFO | root | ============================================================
10:02:48 | INFO | root | Context info:
10:02:48 | INFO | root | Context Name: paper_011_Andersen_2004_Biomass_production_symbiotic_nitroge
Resources: Andersen 2004 Biomass production, symbiotic nitrogen fixation and inorganic N use
10:02:48 | INFO | root | ----------------------------------------
10:02:48 | INFO | root | Available players manifest
10:02:48 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:48 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:48 |   start mas …
10:02:48 |   fail  mas (no_output) in 0.1s
10:02:48 | [11/89] Study 12 · 012_Baumann_2001_Competition_and_crop_performance_
10:02:48 |   start direct_llm …

10:02:48 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:48 | INFO | run_wopke_100 |   start static_workflow …
10:02:48 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=83087 use_llm=False max_facts=200
10:02:48 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:48 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=83087) — output should be much shorter than the full paper
10:02:48 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=91734); calling LLM…

10:02:48 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:48 |   start static_workflow …

10:02:49 | INFO | run_wopke_100 |   error static_workflow after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:49 | INFO | run_wopke_100 |   start mas …
10:02:49 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:49 | INFO | root |   Players per step: 1
10:02:49 | INFO | root |   Debate rounds: 0
10:02:49 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:49 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:49 | INFO | root | ============================================================
10:02:49 | INFO | root | STARTING ORCHESTRATION
10:02:49 | INFO | root | Context: paper_012_Baumann_2001_Competition_and_crop_performance_in_a
10:02:49 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:49 | INFO | root | Output schema: WopkeOutput
10:02:49 | INFO | root | ============================================================
10:02:49 | INFO | root | ============================================================
10:02:49 | INFO | root | GENERATING PLAN
10:02:49 | INFO | root | Context: paper_012_Baumann_2001_Competition_and_crop_performance_in_a
10:02:49 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:49 | INFO | root | ============================================================
10:02:49 | INFO | root | Context info:
10:02:49 | INFO | root | Context Name: paper_012_Baumann_2001_Competition_and_crop_performance_in_a
Resources: Baumann 2001 Competition and crop performance in a leek celery intercropping system
10:02:49 | INFO | root | ----------------------------------------
10:02:49 | INFO | root | Available players manifest
10:02:49 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:49 |   error static_workflow after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:49 |   start mas …
10:02:49 |   fail  mas (no_output) in 0.1s
10:02:49 | [12/89] Study 13 · 013_Banik_2006_Wheat_and_chickpea_intercropping_sy
10:02:49 |   start direct_llm …

10:02:49 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:49 | INFO | run_wopke_100 |   start static_workflow …
10:02:49 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=63879 use_llm=False max_facts=200
10:02:49 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:49 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=63879) — output should be much shorter than the full paper
10:02:49 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=72526); calling LLM…

10:02:49 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:49 |   start static_workflow …

10:02:49 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:49 | INFO | run_wopke_100 |   start mas …
10:02:49 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:49 | INFO | root |   Players per step: 1
10:02:49 | INFO | root |   Debate rounds: 0
10:02:49 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:49 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:49 | INFO | root | ============================================================
10:02:49 | INFO | root | STARTING ORCHESTRATION
10:02:49 | INFO | root | Context: paper_013_Banik_2006_Wheat_and_chickpea_intercropping_system
10:02:49 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:49 | INFO | root | Output schema: WopkeOutput
10:02:49 | INFO | root | ============================================================
10:02:49 | INFO | root | ============================================================
10:02:49 | INFO | root | GENERATING PLAN
10:02:49 | INFO | root | Context: paper_013_Banik_2006_Wheat_and_chickpea_intercropping_system
10:02:49 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:49 | INFO | root | ============================================================
10:02:49 | INFO | root | Context info:
10:02:49 | INFO | root | Context Name: paper_013_Banik_2006_Wheat_and_chickpea_intercropping_system
Resources: Banik 2006 Wheat and chickpea intercropping systems in an additive series experiment
10:02:49 | INFO | root | ----------------------------------------
10:02:49 | INFO | root | Available players manifest
10:02:49 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:49 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:49 |   start mas …
10:02:49 |   fail  mas (no_output) in 0.1s
10:02:49 | [13/89] Study 14 · 014_Corre_Hellou_2006_Interspecific_competition_fo
10:02:49 |   start direct_llm …

10:02:50 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:50 | INFO | run_wopke_100 |   start static_workflow …
10:02:50 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=68061 use_llm=False max_facts=200
10:02:50 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:50 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=68061) — output should be much shorter than the full paper
10:02:50 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=76708); calling LLM…

10:02:50 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:50 |   start static_workflow …

10:02:50 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:50 | INFO | run_wopke_100 |   start mas …
10:02:50 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:50 | INFO | root |   Players per step: 1
10:02:50 | INFO | root |   Debate rounds: 0
10:02:50 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:50 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:50 | INFO | root | ============================================================
10:02:50 | INFO | root | STARTING ORCHESTRATION
10:02:50 | INFO | root | Context: paper_014_Corre_Hellou_2006_Interspecific_competition_for_so
10:02:50 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:50 | INFO | root | Output schema: WopkeOutput
10:02:50 | INFO | root | ============================================================
10:02:50 | INFO | root | ============================================================
10:02:50 | INFO | root | GENERATING PLAN
10:02:50 | INFO | root | Context: paper_014_Corre_Hellou_2006_Interspecific_competition_for_so
10:02:50 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:50 | INFO | root | ============================================================
10:02:50 | INFO | root | Context info:
10:02:50 | INFO | root | Context Name: paper_014_Corre_Hellou_2006_Interspecific_competition_for_so
Resources: Corre-Hellou 2006 Interspecific competition for soil N and its interaction with N-2 fixation
10:02:50 | INFO | root | ----------------------------------------
10:02:50 | INFO | root | Available players manifest
10:02:50 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:50 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:50 |   start mas …
10:02:50 |   fail  mas (no_output) in 0.1s
10:02:50 | [14/89] Study 15 · 015_Chu_2004_Nitrogen_fixation_and_N_transfer_from
10:02:50 |   start direct_llm …

10:02:51 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:51 | INFO | run_wopke_100 |   start static_workflow …
10:02:51 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=62480 use_llm=False max_facts=200
10:02:51 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:51 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=62480) — output should be much shorter than the full paper
10:02:51 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=71127); calling LLM…

10:02:51 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:51 |   start static_workflow …

10:02:51 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:51 | INFO | run_wopke_100 |   start mas …
10:02:51 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:51 | INFO | root |   Players per step: 1
10:02:51 | INFO | root |   Debate rounds: 0
10:02:51 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:51 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:51 | INFO | root | ============================================================
10:02:51 | INFO | root | STARTING ORCHESTRATION
10:02:51 | INFO | root | Context: paper_015_Chu_2004_Nitrogen_fixation_and_N_transfer_from_pea
10:02:51 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:51 | INFO | root | Output schema: WopkeOutput
10:02:51 | INFO | root | ============================================================
10:02:51 | INFO | root | ============================================================
10:02:51 | INFO | root | GENERATING PLAN
10:02:51 | INFO | root | Context: paper_015_Chu_2004_Nitrogen_fixation_and_N_transfer_from_pea
10:02:51 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:51 | INFO | root | ============================================================
10:02:51 | INFO | root | Context info:
10:02:51 | INFO | root | Context Name: paper_015_Chu_2004_Nitrogen_fixation_and_N_transfer_from_pea
Resources: Chu 2004 Nitrogen fixation and N transfer from peanut to rice cultivated in aerobic soil in an intercropping
10:02:51 | INFO | root | ----------------------------------------
10:02:51 | INFO | root | Available players manifest
10:02:51 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:51 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:51 |   start mas …
10:02:51 |   fail  mas (no_output) in 0.1s
10:02:51 | [15/89] Study 16 · 016_Fan_et_al_2006_Nitrogen_fixation_of_faba_bean_
10:02:51 |   start direct_llm …

10:02:51 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:51 | INFO | run_wopke_100 |   start static_workflow …
10:02:51 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=52730 use_llm=False max_facts=200
10:02:51 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:51 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=52730) — output should be much shorter than the full paper
10:02:51 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=61377); calling LLM…

10:02:51 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:51 |   start static_workflow …

10:02:52 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:52 | INFO | run_wopke_100 |   start mas …
10:02:52 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:52 | INFO | root |   Players per step: 1
10:02:52 | INFO | root |   Debate rounds: 0
10:02:52 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:52 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:52 | INFO | root | ============================================================
10:02:52 | INFO | root | STARTING ORCHESTRATION
10:02:52 | INFO | root | Context: paper_016_Fan_et_al_2006_Nitrogen_fixation_of_faba_bean_inte
10:02:52 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:52 | INFO | root | Output schema: WopkeOutput
10:02:52 | INFO | root | ============================================================
10:02:52 | INFO | root | ============================================================
10:02:52 | INFO | root | GENERATING PLAN
10:02:52 | INFO | root | Context: paper_016_Fan_et_al_2006_Nitrogen_fixation_of_faba_bean_inte
10:02:52 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:52 | INFO | root | ============================================================
10:02:52 | INFO | root | Context info:
10:02:52 | INFO | root | Context Name: paper_016_Fan_et_al_2006_Nitrogen_fixation_of_faba_bean_inte
Resources: Fan et al 2006 Nitrogen fixation of faba bean interacting with a non-legume in two contrasting intercropping
10:02:52 | INFO | root | ----------------------------------------
10:02:52 | INFO | root | Available players manifest
10:02:52 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:52 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:52 |   start mas …
10:02:52 |   fail  mas (no_output) in 0.1s
10:02:52 | [16/89] Study 17 · 017_Agegnehu_2006_Yield_performance_and_land_use_e
10:02:52 |   start direct_llm …

10:02:52 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:52 | INFO | run_wopke_100 |   start static_workflow …
10:02:52 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=44838 use_llm=False max_facts=200
10:02:52 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:52 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=44838) — output should be much shorter than the full paper
10:02:52 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=53485); calling LLM…

10:02:52 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:52 |   start static_workflow …

10:02:52 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:52 | INFO | run_wopke_100 |   start mas …
10:02:52 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:52 | INFO | root |   Players per step: 1
10:02:52 | INFO | root |   Debate rounds: 0
10:02:52 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:52 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:52 | INFO | root | ============================================================
10:02:52 | INFO | root | STARTING ORCHESTRATION
10:02:52 | INFO | root | Context: paper_017_Agegnehu_2006_Yield_performance_and_land_use_effic
10:02:52 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:52 | INFO | root | Output schema: WopkeOutput
10:02:52 | INFO | root | ============================================================
10:02:52 | INFO | root | ============================================================
10:02:52 | INFO | root | GENERATING PLAN
10:02:52 | INFO | root | Context: paper_017_Agegnehu_2006_Yield_performance_and_land_use_effic
10:02:52 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:52 | INFO | root | ============================================================
10:02:52 | INFO | root | Context info:
10:02:52 | INFO | root | Context Name: paper_017_Agegnehu_2006_Yield_performance_and_land_use_effic
Resources: Agegnehu 2006 Yield performance and land use efficiency of barley and faba bean mixed cropping
10:02:52 | INFO | root | ----------------------------------------
10:02:52 | INFO | root | Available players manifest
10:02:52 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:52 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:52 |   start mas …
10:02:52 |   fail  mas (no_output) in 0.1s
10:02:52 | [17/89] Study 18 · 018_Hauggaard_Nielsen_et_al_2006_Density_and_relat
10:02:52 |   start direct_llm …

10:02:53 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:53 | INFO | run_wopke_100 |   start static_workflow …
10:02:53 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=57300 use_llm=False max_facts=200
10:02:53 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:53 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=57300) — output should be much shorter than the full paper
10:02:53 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=65947); calling LLM…

10:02:53 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:53 |   start static_workflow …

10:02:53 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:53 | INFO | run_wopke_100 |   start mas …
10:02:53 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:53 | INFO | root |   Players per step: 1
10:02:53 | INFO | root |   Debate rounds: 0
10:02:53 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:53 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:53 | INFO | root | ============================================================
10:02:53 | INFO | root | STARTING ORCHESTRATION
10:02:53 | INFO | root | Context: paper_018_Hauggaard_Nielsen_et_al_2006_Density_and_relative_
10:02:53 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:53 | INFO | root | Output schema: WopkeOutput
10:02:53 | INFO | root | ============================================================
10:02:53 | INFO | root | ============================================================
10:02:53 | INFO | root | GENERATING PLAN
10:02:53 | INFO | root | Context: paper_018_Hauggaard_Nielsen_et_al_2006_Density_and_relative_
10:02:53 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:53 | INFO | root | ============================================================
10:02:53 | INFO | root | Context info:
10:02:53 | INFO | root | Context Name: paper_018_Hauggaard_Nielsen_et_al_2006_Density_and_relative_
Resources: Hauggaard-Nielsen et al 2006 Density and relative frequency effects on  pea barley intercrops
10:02:53 | INFO | root | ----------------------------------------
10:02:53 | INFO | root | Available players manifest
10:02:53 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:53 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:53 |   start mas …
10:02:53 |   fail  mas (no_output) in 0.1s
10:02:53 | [18/89] Study 19 · 019_Reddy_et_al_1981Growth_and_resource_use_studie
10:02:53 |   start direct_llm …

10:02:53 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:53 | INFO | run_wopke_100 |   start static_workflow …
10:02:53 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=34853 use_llm=False max_facts=200
10:02:53 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:53 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=34853) — output should be much shorter than the full paper
10:02:53 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=43500); calling LLM…

10:02:53 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:53 |   start static_workflow …

10:02:54 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:54 | INFO | run_wopke_100 |   start mas …
10:02:54 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:54 | INFO | root |   Players per step: 1
10:02:54 | INFO | root |   Debate rounds: 0
10:02:54 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:54 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:54 | INFO | root | ============================================================
10:02:54 | INFO | root | STARTING ORCHESTRATION
10:02:54 | INFO | root | Context: paper_019_Reddy_et_al_1981Growth_and_resource_use_studies_in
10:02:54 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:54 | INFO | root | Output schema: WopkeOutput
10:02:54 | INFO | root | ============================================================
10:02:54 | INFO | root | ============================================================
10:02:54 | INFO | root | GENERATING PLAN
10:02:54 | INFO | root | Context: paper_019_Reddy_et_al_1981Growth_and_resource_use_studies_in
10:02:54 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:54 | INFO | root | ============================================================
10:02:54 | INFO | root | Context info:
10:02:54 | INFO | root | Context Name: paper_019_Reddy_et_al_1981Growth_and_resource_use_studies_in
Resources: Reddy et al 1981Growth and resource use studies in an intercrop of pearl millet-groundnut
10:02:54 | INFO | root | ----------------------------------------
10:02:54 | INFO | root | Available players manifest
10:02:54 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:54 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:54 |   start mas …
10:02:54 |   fail  mas (no_output) in 0.1s
10:02:54 | [19/89] Study 20 · 020_Awal_et_al_2006_Radiation_interception_and_use
10:02:54 |   start direct_llm …

10:02:54 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:54 | INFO | run_wopke_100 |   start static_workflow …
10:02:54 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=49052 use_llm=False max_facts=200
10:02:54 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:54 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=49052) — output should be much shorter than the full paper
10:02:54 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=57699); calling LLM…

10:02:54 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:54 |   start static_workflow …

10:02:54 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:54 | INFO | run_wopke_100 |   start mas …
10:02:54 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:54 | INFO | root |   Players per step: 1
10:02:54 | INFO | root |   Debate rounds: 0
10:02:54 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:54 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:54 | INFO | root | ============================================================
10:02:54 | INFO | root | STARTING ORCHESTRATION
10:02:54 | INFO | root | Context: paper_020_Awal_et_al_2006_Radiation_interception_and_use_by_
10:02:54 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:54 | INFO | root | Output schema: WopkeOutput
10:02:54 | INFO | root | ============================================================
10:02:54 | INFO | root | ============================================================
10:02:54 | INFO | root | GENERATING PLAN
10:02:54 | INFO | root | Context: paper_020_Awal_et_al_2006_Radiation_interception_and_use_by_
10:02:54 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:54 | INFO | root | ============================================================
10:02:54 | INFO | root | Context info:
10:02:54 | INFO | root | Context Name: paper_020_Awal_et_al_2006_Radiation_interception_and_use_by_
Resources: Awal et al 2006 Radiation interception and use by maize-peanut intercrop canopy
10:02:54 | INFO | root | ----------------------------------------
10:02:54 | INFO | root | Available players manifest
10:02:54 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:54 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:54 |   start mas …
10:02:54 |   fail  mas (no_output) in 0.1s
10:02:54 | [20/89] Study 21 · 021_Waterer_et_al_1994_Yield_and_symbiotic_nitroge
10:02:54 |   start direct_llm …

10:02:55 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:55 | INFO | run_wopke_100 |   start static_workflow …
10:02:55 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=43422 use_llm=False max_facts=200
10:02:55 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:55 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=43422) — output should be much shorter than the full paper
10:02:55 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=52069); calling LLM…

10:02:55 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:55 |   start static_workflow …

10:02:55 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:55 | INFO | run_wopke_100 |   start mas …
10:02:55 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:55 | INFO | root |   Players per step: 1
10:02:55 | INFO | root |   Debate rounds: 0
10:02:55 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:55 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:55 | INFO | root | ============================================================
10:02:55 | INFO | root | STARTING ORCHESTRATION
10:02:55 | INFO | root | Context: paper_021_Waterer_et_al_1994_Yield_and_symbiotic_nitrogen_fi
10:02:55 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:55 | INFO | root | Output schema: WopkeOutput
10:02:55 | INFO | root | ============================================================
10:02:55 | INFO | root | ============================================================
10:02:55 | INFO | root | GENERATING PLAN
10:02:55 | INFO | root | Context: paper_021_Waterer_et_al_1994_Yield_and_symbiotic_nitrogen_fi
10:02:55 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:55 | INFO | root | ============================================================
10:02:55 | INFO | root | Context info:
10:02:55 | INFO | root | Context Name: paper_021_Waterer_et_al_1994_Yield_and_symbiotic_nitrogen_fi
Resources: Waterer et al 1994 Yield and symbiotic nitrogen fixation in a pea-mustard intercrop as influenced
10:02:55 | INFO | root | ----------------------------------------
10:02:55 | INFO | root | Available players manifest
10:02:55 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:55 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:55 |   start mas …
10:02:55 |   fail  mas (no_output) in 0.1s
10:02:55 | [21/89] Study 22 · 022_Song_et_al_2007_Effect_of_intercropping_on_cro
10:02:55 |   start direct_llm …

10:02:55 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:55 | INFO | run_wopke_100 |   start static_workflow …
10:02:55 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=60609 use_llm=False max_facts=200
10:02:55 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:55 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=60609) — output should be much shorter than the full paper
10:02:55 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=69256); calling LLM…

10:02:55 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:55 |   start static_workflow …

10:02:56 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:56 | INFO | run_wopke_100 |   start mas …
10:02:56 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:56 | INFO | root |   Players per step: 1
10:02:56 | INFO | root |   Debate rounds: 0
10:02:56 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:56 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:56 | INFO | root | ============================================================
10:02:56 | INFO | root | STARTING ORCHESTRATION
10:02:56 | INFO | root | Context: paper_022_Song_et_al_2007_Effect_of_intercropping_on_crop_yi
10:02:56 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:56 | INFO | root | Output schema: WopkeOutput
10:02:56 | INFO | root | ============================================================
10:02:56 | INFO | root | ============================================================
10:02:56 | INFO | root | GENERATING PLAN
10:02:56 | INFO | root | Context: paper_022_Song_et_al_2007_Effect_of_intercropping_on_crop_yi
10:02:56 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:56 | INFO | root | ============================================================
10:02:56 | INFO | root | Context info:
10:02:56 | INFO | root | Context Name: paper_022_Song_et_al_2007_Effect_of_intercropping_on_crop_yi
Resources: Song et al 2007 Effect of intercropping on crop yield and chemical and microiological properties
10:02:56 | INFO | root | ----------------------------------------
10:02:56 | INFO | root | Available players manifest
10:02:56 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:56 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:56 |   start mas …
10:02:56 |   fail  mas (no_output) in 0.2s
10:02:56 | [22/89] Study 23 · 023_Banik_et_al_2000_Evaluation_of_mustard_and_leg
10:02:56 |   start direct_llm …

10:02:56 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:56 | INFO | run_wopke_100 |   start static_workflow …
10:02:56 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=37143 use_llm=False max_facts=200
10:02:56 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:56 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=37143) — output should be much shorter than the full paper
10:02:56 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=45790); calling LLM…

10:02:56 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:56 |   start static_workflow …

10:02:56 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:56 | INFO | run_wopke_100 |   start mas …
10:02:56 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:56 | INFO | root |   Players per step: 1
10:02:56 | INFO | root |   Debate rounds: 0
10:02:56 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:56 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:56 | INFO | root | ============================================================
10:02:56 | INFO | root | STARTING ORCHESTRATION
10:02:56 | INFO | root | Context: paper_023_Banik_et_al_2000_Evaluation_of_mustard_and_legume_
10:02:56 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:56 | INFO | root | Output schema: WopkeOutput
10:02:56 | INFO | root | ============================================================
10:02:56 | INFO | root | ============================================================
10:02:56 | INFO | root | GENERATING PLAN
10:02:56 | INFO | root | Context: paper_023_Banik_et_al_2000_Evaluation_of_mustard_and_legume_
10:02:56 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:56 | INFO | root | ============================================================
10:02:56 | INFO | root | Context info:
10:02:56 | INFO | root | Context Name: paper_023_Banik_et_al_2000_Evaluation_of_mustard_and_legume_
Resources: Banik et al 2000 Evaluation of mustard and legume intercropping
10:02:56 | INFO | root | ----------------------------------------
10:02:56 | INFO | root | Available players manifest
10:02:56 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:56 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:56 |   start mas …
10:02:57 |   fail  mas (no_output) in 0.1s
10:02:57 | [23/89] Study 24 · 024_Watiki_et_al_1993_Radiation_interception_and_g
10:02:57 |   start direct_llm …

10:02:57 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:57 | INFO | run_wopke_100 |   start static_workflow …
10:02:57 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=46653 use_llm=False max_facts=200
10:02:57 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:57 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=46653) — output should be much shorter than the full paper
10:02:57 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=55300); calling LLM…

10:02:57 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:57 |   start static_workflow …

10:02:57 | INFO | run_wopke_100 |   error static_workflow after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:57 | INFO | run_wopke_100 |   start mas …
10:02:57 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:57 | INFO | root |   Players per step: 1
10:02:57 | INFO | root |   Debate rounds: 0
10:02:57 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:57 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:57 | INFO | root | ============================================================
10:02:57 | INFO | root | STARTING ORCHESTRATION
10:02:57 | INFO | root | Context: paper_024_Watiki_et_al_1993_Radiation_interception_and_growt
10:02:57 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:57 | INFO | root | Output schema: WopkeOutput
10:02:57 | INFO | root | ============================================================
10:02:57 | INFO | root | ============================================================
10:02:57 | INFO | root | GENERATING PLAN
10:02:57 | INFO | root | Context: paper_024_Watiki_et_al_1993_Radiation_interception_and_growt
10:02:57 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:57 | INFO | root | ============================================================
10:02:57 | INFO | root | Context info:
10:02:57 | INFO | root | Context Name: paper_024_Watiki_et_al_1993_Radiation_interception_and_growt
Resources: Watiki et al 1993 Radiation interception and growth of maize-cowpea intercrop
10:02:57 | INFO | root | ----------------------------------------
10:02:57 | INFO | root | Available players manifest
10:02:57 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:57 |   error static_workflow after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:57 |   start mas …
10:02:57 |   fail  mas (no_output) in 0.1s
10:02:57 | [24/89] Study 25 · 025_Olasantan_et_al_1994_Effects_of_itnercropping_
10:02:57 |   start direct_llm …

10:02:58 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:58 | INFO | run_wopke_100 |   start static_workflow …
10:02:58 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=37458 use_llm=False max_facts=200
10:02:58 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:58 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=37458) — output should be much shorter than the full paper
10:02:58 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=46105); calling LLM…

10:02:58 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:58 |   start static_workflow …

10:02:58 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:58 | INFO | run_wopke_100 |   start mas …
10:02:58 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:58 | INFO | root |   Players per step: 1
10:02:58 | INFO | root |   Debate rounds: 0
10:02:58 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:58 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:58 | INFO | root | ============================================================
10:02:58 | INFO | root | STARTING ORCHESTRATION
10:02:58 | INFO | root | Context: paper_025_Olasantan_et_al_1994_Effects_of_itnercropping_and_
10:02:58 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:58 | INFO | root | Output schema: WopkeOutput
10:02:58 | INFO | root | ============================================================
10:02:58 | INFO | root | ============================================================
10:02:58 | INFO | root | GENERATING PLAN
10:02:58 | INFO | root | Context: paper_025_Olasantan_et_al_1994_Effects_of_itnercropping_and_
10:02:58 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:58 | INFO | root | ============================================================
10:02:58 | INFO | root | Context info:
10:02:58 | INFO | root | Context Name: paper_025_Olasantan_et_al_1994_Effects_of_itnercropping_and_
Resources: Olasantan et al 1994 Effects of itnercropping and fertilizer application on weed control and performance
10:02:58 | INFO | root | ----------------------------------------
10:02:58 | INFO | root | Available players manifest
10:02:58 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:58 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:58 |   start mas …
10:02:58 |   fail  mas (no_output) in 0.1s
10:02:58 | [25/89] Study 26 · 026_Zhang_et_al_2007_Growth_yield_and_quality_of_w
10:02:58 |   start direct_llm …

10:02:58 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:58 | INFO | run_wopke_100 |   start static_workflow …
10:02:58 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=76562 use_llm=False max_facts=200
10:02:58 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:58 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=76562) — output should be much shorter than the full paper
10:02:58 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=85209); calling LLM…

10:02:58 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:58 |   start static_workflow …

10:02:59 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:59 | INFO | run_wopke_100 |   start mas …
10:02:59 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:59 | INFO | root |   Players per step: 1
10:02:59 | INFO | root |   Debate rounds: 0
10:02:59 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:59 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:59 | INFO | root | ============================================================
10:02:59 | INFO | root | STARTING ORCHESTRATION
10:02:59 | INFO | root | Context: paper_026_Zhang_et_al_2007_Growth_yield_and_quality_of_wheat
10:02:59 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:59 | INFO | root | Output schema: WopkeOutput
10:02:59 | INFO | root | ============================================================
10:02:59 | INFO | root | ============================================================
10:02:59 | INFO | root | GENERATING PLAN
10:02:59 | INFO | root | Context: paper_026_Zhang_et_al_2007_Growth_yield_and_quality_of_wheat
10:02:59 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:59 | INFO | root | ============================================================
10:02:59 | INFO | root | Context info:
10:02:59 | INFO | root | Context Name: paper_026_Zhang_et_al_2007_Growth_yield_and_quality_of_wheat
Resources: Zhang et al 2007 Growth, yield and quality of wheat and cotton in relay strop intercropping systems
10:02:59 | INFO | root | ----------------------------------------
10:02:59 | INFO | root | Available players manifest
10:02:59 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:59 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:59 |   start mas …
10:02:59 |   fail  mas (no_output) in 0.1s
10:02:59 | [26/89] Study 27 · 027_Haymes_et_al_1999_Competition_between_autumn_a
10:02:59 |   start direct_llm …

10:02:59 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:59 | INFO | run_wopke_100 |   start static_workflow …
10:02:59 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=36976 use_llm=False max_facts=200
10:02:59 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:02:59 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=36976) — output should be much shorter than the full paper
10:02:59 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=45623); calling LLM…

10:02:59 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:59 |   start static_workflow …

10:02:59 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:59 | INFO | run_wopke_100 |   start mas …
10:02:59 | INFO | root | PlanExecutor initialized with topology: pipeline
10:02:59 | INFO | root |   Players per step: 1
10:02:59 | INFO | root |   Debate rounds: 0
10:02:59 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:02:59 | INFO | root | Orchestrator initialized with topology: pipeline
10:02:59 | INFO | root | ============================================================
10:02:59 | INFO | root | STARTING ORCHESTRATION
10:02:59 | INFO | root | Context: paper_027_Haymes_et_al_1999_Competition_between_autumn_and_s
10:02:59 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:59 | INFO | root | Output schema: WopkeOutput
10:02:59 | INFO | root | ============================================================
10:02:59 | INFO | root | ============================================================
10:02:59 | INFO | root | GENERATING PLAN
10:02:59 | INFO | root | Context: paper_027_Haymes_et_al_1999_Competition_between_autumn_and_s
10:02:59 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:02:59 | INFO | root | ============================================================
10:02:59 | INFO | root | Context info:
10:02:59 | INFO | root | Context Name: paper_027_Haymes_et_al_1999_Competition_between_autumn_and_s
Resources: Haymes et al 1999 Competition between autumn and spring planted grain inetrcrops of wheat and field bean
10:02:59 | INFO | root | ----------------------------------------
10:02:59 | INFO | root | Available players manifest
10:02:59 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:02:59 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:02:59 |   start mas …
10:02:59 |   fail  mas (no_output) in 0.1s
10:02:59 | [27/89] Study 28 · 028_Ghaley_et_al_2005_Intercropping_of_wheat_and_p
10:02:59 |   start direct_llm …

10:03:00 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:00 | INFO | run_wopke_100 |   start static_workflow …
10:03:00 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=60365 use_llm=False max_facts=200
10:03:00 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:00 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=60365) — output should be much shorter than the full paper
10:03:00 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=69012); calling LLM…

10:03:00 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:00 |   start static_workflow …

10:03:00 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:00 | INFO | run_wopke_100 |   start mas …
10:03:00 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:00 | INFO | root |   Players per step: 1
10:03:00 | INFO | root |   Debate rounds: 0
10:03:00 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:00 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:00 | INFO | root | ============================================================
10:03:00 | INFO | root | STARTING ORCHESTRATION
10:03:00 | INFO | root | Context: paper_028_Ghaley_et_al_2005_Intercropping_of_wheat_and_pea_a
10:03:00 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:00 | INFO | root | Output schema: WopkeOutput
10:03:00 | INFO | root | ============================================================
10:03:00 | INFO | root | ============================================================
10:03:00 | INFO | root | GENERATING PLAN
10:03:00 | INFO | root | Context: paper_028_Ghaley_et_al_2005_Intercropping_of_wheat_and_pea_a
10:03:00 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:00 | INFO | root | ============================================================
10:03:00 | INFO | root | Context info:
10:03:00 | INFO | root | Context Name: paper_028_Ghaley_et_al_2005_Intercropping_of_wheat_and_pea_a
Resources: Ghaley et al 2005 Intercropping of wheat and pea as influenced by nitrogen fertilization
10:03:00 | INFO | root | ----------------------------------------
10:03:00 | INFO | root | Available players manifest
10:03:00 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:00 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:00 |   start mas …
10:03:00 |   fail  mas (no_output) in 0.1s
10:03:00 | [28/89] Study 29 · 029_Tobita_et_al_1994_Field_evaluation_of_nitrogen
10:03:00 |   start direct_llm …

10:03:01 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:01 | INFO | run_wopke_100 |   start static_workflow …
10:03:01 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=57832 use_llm=False max_facts=200
10:03:01 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:01 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=57832) — output should be much shorter than the full paper
10:03:01 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=66479); calling LLM…

10:03:01 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:01 |   start static_workflow …

10:03:01 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:01 | INFO | run_wopke_100 |   start mas …
10:03:01 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:01 | INFO | root |   Players per step: 1
10:03:01 | INFO | root |   Debate rounds: 0
10:03:01 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:01 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:01 | INFO | root | ============================================================
10:03:01 | INFO | root | STARTING ORCHESTRATION
10:03:01 | INFO | root | Context: paper_029_Tobita_et_al_1994_Field_evaluation_of_nitrogen_fix
10:03:01 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:01 | INFO | root | Output schema: WopkeOutput
10:03:01 | INFO | root | ============================================================
10:03:01 | INFO | root | ============================================================
10:03:01 | INFO | root | GENERATING PLAN
10:03:01 | INFO | root | Context: paper_029_Tobita_et_al_1994_Field_evaluation_of_nitrogen_fix
10:03:01 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:01 | INFO | root | ============================================================
10:03:01 | INFO | root | Context info:
10:03:01 | INFO | root | Context Name: paper_029_Tobita_et_al_1994_Field_evaluation_of_nitrogen_fix
Resources: Tobita et al 1994 Field evaluation of nitrogen fixation and use of nitrogen fertilizer
10:03:01 | INFO | root | ----------------------------------------
10:03:01 | INFO | root | Available players manifest
10:03:01 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:01 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:01 |   start mas …
10:03:01 |   fail  mas (no_output) in 0.1s
10:03:01 | [29/89] Study 30 · 030_Carruthers_et_al_2000_Intercropping_corn_with_
10:03:01 |   start direct_llm …

10:03:01 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:01 | INFO | run_wopke_100 |   start static_workflow …
10:03:01 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=81073 use_llm=False max_facts=200
10:03:01 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:01 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=81073) — output should be much shorter than the full paper
10:03:01 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=89720); calling LLM…

10:03:01 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:01 |   start static_workflow …

10:03:02 | INFO | run_wopke_100 |   error static_workflow after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:02 | INFO | run_wopke_100 |   start mas …
10:03:02 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:02 | INFO | root |   Players per step: 1
10:03:02 | INFO | root |   Debate rounds: 0
10:03:02 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:02 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:02 | INFO | root | ============================================================
10:03:02 | INFO | root | STARTING ORCHESTRATION
10:03:02 | INFO | root | Context: paper_030_Carruthers_et_al_2000_Intercropping_corn_with_soyb
10:03:02 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:02 | INFO | root | Output schema: WopkeOutput
10:03:02 | INFO | root | ============================================================
10:03:02 | INFO | root | ============================================================
10:03:02 | INFO | root | GENERATING PLAN
10:03:02 | INFO | root | Context: paper_030_Carruthers_et_al_2000_Intercropping_corn_with_soyb
10:03:02 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:02 | INFO | root | ============================================================
10:03:02 | INFO | root | Context info:
10:03:02 | INFO | root | Context Name: paper_030_Carruthers_et_al_2000_Intercropping_corn_with_soyb
Resources: Carruthers et al 2000 Intercropping corn with soybean, lupin and forages
10:03:02 | INFO | root | ----------------------------------------
10:03:02 | INFO | root | Available players manifest
10:03:02 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:02 |   error static_workflow after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:02 |   start mas …
10:03:02 |   fail  mas (no_output) in 0.1s
10:03:02 | [30/89] Study 31 · 031_Lithourgidis_et_al_2007_Sustainable_production
10:03:02 |   start direct_llm …

10:03:02 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:02 | INFO | run_wopke_100 |   start static_workflow …
10:03:02 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=36359 use_llm=False max_facts=200
10:03:02 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:02 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=36359) — output should be much shorter than the full paper
10:03:02 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=45006); calling LLM…

10:03:02 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:02 |   start static_workflow …

10:03:02 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:02 | INFO | run_wopke_100 |   start mas …
10:03:02 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:02 | INFO | root |   Players per step: 1
10:03:02 | INFO | root |   Debate rounds: 0
10:03:02 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:02 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:02 | INFO | root | ============================================================
10:03:02 | INFO | root | STARTING ORCHESTRATION
10:03:02 | INFO | root | Context: paper_031_Lithourgidis_et_al_2007_Sustainable_production_of_
10:03:02 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:02 | INFO | root | Output schema: WopkeOutput
10:03:02 | INFO | root | ============================================================
10:03:02 | INFO | root | ============================================================
10:03:02 | INFO | root | GENERATING PLAN
10:03:02 | INFO | root | Context: paper_031_Lithourgidis_et_al_2007_Sustainable_production_of_
10:03:02 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:02 | INFO | root | ============================================================
10:03:02 | INFO | root | Context info:
10:03:02 | INFO | root | Context Name: paper_031_Lithourgidis_et_al_2007_Sustainable_production_of_
Resources: Lithourgidis et al 2007 Sustainable production of barley and wheat by intercropping common vetch
10:03:02 | INFO | root | ----------------------------------------
10:03:02 | INFO | root | Available players manifest
10:03:02 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:02 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:02 |   start mas …
10:03:02 |   fail  mas (no_output) in 0.1s
10:03:02 | [31/89] Study 32 · 032_Knudsen_et_al_2004_Comparison_of_interspecific
10:03:02 |   start direct_llm …

10:03:03 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:03 | INFO | run_wopke_100 |   start static_workflow …
10:03:03 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=60262 use_llm=False max_facts=200
10:03:03 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:03 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=60262) — output should be much shorter than the full paper
10:03:03 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=68909); calling LLM…

10:03:03 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:03 |   start static_workflow …

10:03:03 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:03 | INFO | run_wopke_100 |   start mas …
10:03:03 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:03 | INFO | root |   Players per step: 1
10:03:03 | INFO | root |   Debate rounds: 0
10:03:03 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:03 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:03 | INFO | root | ============================================================
10:03:03 | INFO | root | STARTING ORCHESTRATION
10:03:03 | INFO | root | Context: paper_032_Knudsen_et_al_2004_Comparison_of_interspecific_com
10:03:03 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:03 | INFO | root | Output schema: WopkeOutput
10:03:03 | INFO | root | ============================================================
10:03:03 | INFO | root | ============================================================
10:03:03 | INFO | root | GENERATING PLAN
10:03:03 | INFO | root | Context: paper_032_Knudsen_et_al_2004_Comparison_of_interspecific_com
10:03:03 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:03 | INFO | root | ============================================================
10:03:03 | INFO | root | Context info:
10:03:03 | INFO | root | Context Name: paper_032_Knudsen_et_al_2004_Comparison_of_interspecific_com
Resources: Knudsen et al 2004 Comparison of interspecific competition and N use in intercrops grown a
10:03:03 | INFO | root | ----------------------------------------
10:03:03 | INFO | root | Available players manifest
10:03:03 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:03 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:03 |   start mas …
10:03:03 |   fail  mas (no_output) in 0.1s
10:03:03 | [32/89] Study 33 · 033_Chabi_Olaye_et_al_2005_Relationships_of_interc
10:03:03 |   start direct_llm …

10:03:04 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:04 | INFO | run_wopke_100 |   start static_workflow …
10:03:04 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=89824 use_llm=False max_facts=200
10:03:04 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:04 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=89824) — output should be much shorter than the full paper
10:03:04 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=98471); calling LLM…

10:03:04 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:04 |   start static_workflow …

10:03:04 | INFO | run_wopke_100 |   error static_workflow after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:04 | INFO | run_wopke_100 |   start mas …
10:03:04 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:04 | INFO | root |   Players per step: 1
10:03:04 | INFO | root |   Debate rounds: 0
10:03:04 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:04 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:04 | INFO | root | ============================================================
10:03:04 | INFO | root | STARTING ORCHESTRATION
10:03:04 | INFO | root | Context: paper_033_Chabi_Olaye_et_al_2005_Relationships_of_intercropp
10:03:04 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:04 | INFO | root | Output schema: WopkeOutput
10:03:04 | INFO | root | ============================================================
10:03:04 | INFO | root | ============================================================
10:03:04 | INFO | root | GENERATING PLAN
10:03:04 | INFO | root | Context: paper_033_Chabi_Olaye_et_al_2005_Relationships_of_intercropp
10:03:04 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:04 | INFO | root | ============================================================
10:03:04 | INFO | root | Context info:
10:03:04 | INFO | root | Context Name: paper_033_Chabi_Olaye_et_al_2005_Relationships_of_intercropp
Resources: Chabi-Olaye et al 2005 Relationships of intercropped maize, stem borer damage to maize yield and land-use
10:03:04 | INFO | root | ----------------------------------------
10:03:04 | INFO | root | Available players manifest
10:03:04 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:04 |   error static_workflow after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:04 |   start mas …
10:03:04 |   fail  mas (no_output) in 0.1s
10:03:04 | [33/89] Study 34 · 034_Helenius_et_al_1994_Yield_advantage_and_compet
10:03:04 |   start direct_llm …

10:03:04 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:04 | INFO | run_wopke_100 |   start static_workflow …
10:03:04 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=50817 use_llm=False max_facts=200
10:03:04 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:04 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=50817) — output should be much shorter than the full paper
10:03:04 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=59464); calling LLM…

10:03:04 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:04 |   start static_workflow …

10:03:05 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:05 | INFO | run_wopke_100 |   start mas …
10:03:05 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:05 | INFO | root |   Players per step: 1
10:03:05 | INFO | root |   Debate rounds: 0
10:03:05 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:05 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:05 | INFO | root | ============================================================
10:03:05 | INFO | root | STARTING ORCHESTRATION
10:03:05 | INFO | root | Context: paper_034_Helenius_et_al_1994_Yield_advantage_and_competitio
10:03:05 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:05 | INFO | root | Output schema: WopkeOutput
10:03:05 | INFO | root | ============================================================
10:03:05 | INFO | root | ============================================================
10:03:05 | INFO | root | GENERATING PLAN
10:03:05 | INFO | root | Context: paper_034_Helenius_et_al_1994_Yield_advantage_and_competitio
10:03:05 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:05 | INFO | root | ============================================================
10:03:05 | INFO | root | Context info:
10:03:05 | INFO | root | Context Name: paper_034_Helenius_et_al_1994_Yield_advantage_and_competitio
Resources: Helenius et al 1994 Yield advantage and competition in intercropped oats and faba bean
10:03:05 | INFO | root | ----------------------------------------
10:03:05 | INFO | root | Available players manifest
10:03:05 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:05 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:05 |   start mas …
10:03:05 |   fail  mas (no_output) in 0.1s
10:03:05 | [34/89] Study 35 · 035_Carr_et_al_1995_Grain_yield_and_weed_biomass_o
10:03:05 |   start direct_llm …

10:03:05 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:05 | INFO | run_wopke_100 |   start static_workflow …
10:03:05 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=43573 use_llm=False max_facts=200
10:03:05 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:05 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=43573) — output should be much shorter than the full paper
10:03:05 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=52220); calling LLM…

10:03:05 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:05 |   start static_workflow …

10:03:05 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:05 | INFO | run_wopke_100 |   start mas …
10:03:05 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:05 | INFO | root |   Players per step: 1
10:03:05 | INFO | root |   Debate rounds: 0
10:03:05 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:05 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:05 | INFO | root | ============================================================
10:03:05 | INFO | root | STARTING ORCHESTRATION
10:03:05 | INFO | root | Context: paper_035_Carr_et_al_1995_Grain_yield_and_weed_biomass_of_a_
10:03:05 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:05 | INFO | root | Output schema: WopkeOutput
10:03:05 | INFO | root | ============================================================
10:03:05 | INFO | root | ============================================================
10:03:05 | INFO | root | GENERATING PLAN
10:03:05 | INFO | root | Context: paper_035_Carr_et_al_1995_Grain_yield_and_weed_biomass_of_a_
10:03:05 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:05 | INFO | root | ============================================================
10:03:05 | INFO | root | Context info:
10:03:05 | INFO | root | Context Name: paper_035_Carr_et_al_1995_Grain_yield_and_weed_biomass_of_a_
Resources: Carr et al 1995 Grain yield and weed biomass of a wheat-lentil intercrop
10:03:05 | INFO | root | ----------------------------------------
10:03:05 | INFO | root | Available players manifest
10:03:05 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:05 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:05 |   start mas …
10:03:05 |   fail  mas (no_output) in 0.1s
10:03:05 | [35/89] Study 36 · 036_Marthin_et_al_1990_Intercropping_corn_and_soyb
10:03:05 |   start direct_llm …

10:03:06 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:06 | INFO | run_wopke_100 |   start static_workflow …
10:03:06 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=65895 use_llm=False max_facts=200
10:03:06 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:06 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=65895) — output should be much shorter than the full paper
10:03:06 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=74542); calling LLM…

10:03:06 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:06 |   start static_workflow …

10:03:06 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:06 | INFO | run_wopke_100 |   start mas …
10:03:06 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:06 | INFO | root |   Players per step: 1
10:03:06 | INFO | root |   Debate rounds: 0
10:03:06 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:06 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:06 | INFO | root | ============================================================
10:03:06 | INFO | root | STARTING ORCHESTRATION
10:03:06 | INFO | root | Context: paper_036_Marthin_et_al_1990_Intercropping_corn_and_soybean_
10:03:06 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:06 | INFO | root | Output schema: WopkeOutput
10:03:06 | INFO | root | ============================================================
10:03:06 | INFO | root | ============================================================
10:03:06 | INFO | root | GENERATING PLAN
10:03:06 | INFO | root | Context: paper_036_Marthin_et_al_1990_Intercropping_corn_and_soybean_
10:03:06 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:06 | INFO | root | ============================================================
10:03:06 | INFO | root | Context info:
10:03:06 | INFO | root | Context Name: paper_036_Marthin_et_al_1990_Intercropping_corn_and_soybean_
Resources: Marthin et al 1990 Intercropping corn and soybean for silage in a cool temperate region
10:03:06 | INFO | root | ----------------------------------------
10:03:06 | INFO | root | Available players manifest
10:03:06 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:06 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:06 |   start mas …
10:03:06 |   fail  mas (no_output) in 0.1s
10:03:06 | [36/89] Study 37 · 037_Bedoussac_et_al_2010_The_efficiency_of_a_durum
10:03:06 |   start direct_llm …

10:03:06 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:06 | INFO | run_wopke_100 |   start static_workflow …
10:03:06 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=96029 use_llm=False max_facts=200
10:03:06 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:06 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=96029) — output should be much shorter than the full paper
10:03:06 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=104676); calling LLM…

10:03:06 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:06 |   start static_workflow …

10:03:07 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:07 | INFO | run_wopke_100 |   start mas …
10:03:07 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:07 | INFO | root |   Players per step: 1
10:03:07 | INFO | root |   Debate rounds: 0
10:03:07 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:07 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:07 | INFO | root | ============================================================
10:03:07 | INFO | root | STARTING ORCHESTRATION
10:03:07 | INFO | root | Context: paper_037_Bedoussac_et_al_2010_The_efficiency_of_a_durum_whe
10:03:07 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:07 | INFO | root | Output schema: WopkeOutput
10:03:07 | INFO | root | ============================================================
10:03:07 | INFO | root | ============================================================
10:03:07 | INFO | root | GENERATING PLAN
10:03:07 | INFO | root | Context: paper_037_Bedoussac_et_al_2010_The_efficiency_of_a_durum_whe
10:03:07 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:07 | INFO | root | ============================================================
10:03:07 | INFO | root | Context info:
10:03:07 | INFO | root | Context Name: paper_037_Bedoussac_et_al_2010_The_efficiency_of_a_durum_whe
Resources: Bedoussac et al 2010 The efficiency of a durum wheat-winter pea intercrop
10:03:07 | INFO | root | ----------------------------------------
10:03:07 | INFO | root | Available players manifest
10:03:07 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:07 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:07 |   start mas …
10:03:07 |   fail  mas (no_output) in 0.1s
10:03:07 | [37/89] Study 38 · 038_Jahansooz_et_al_2006_Radiation_and_water_use_a
10:03:07 |   start direct_llm …

10:03:07 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:07 | INFO | run_wopke_100 |   start static_workflow …
10:03:07 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=49479 use_llm=False max_facts=200
10:03:07 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:07 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=49479) — output should be much shorter than the full paper
10:03:07 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=58126); calling LLM…

10:03:07 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:07 |   start static_workflow …

10:03:08 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:08 | INFO | run_wopke_100 |   start mas …
10:03:08 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:08 | INFO | root |   Players per step: 1
10:03:08 | INFO | root |   Debate rounds: 0
10:03:08 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:08 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:08 | INFO | root | ============================================================
10:03:08 | INFO | root | STARTING ORCHESTRATION
10:03:08 | INFO | root | Context: paper_038_Jahansooz_et_al_2006_Radiation_and_water_use_assoc
10:03:08 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:08 | INFO | root | Output schema: WopkeOutput
10:03:08 | INFO | root | ============================================================
10:03:08 | INFO | root | ============================================================
10:03:08 | INFO | root | GENERATING PLAN
10:03:08 | INFO | root | Context: paper_038_Jahansooz_et_al_2006_Radiation_and_water_use_assoc
10:03:08 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:08 | INFO | root | ============================================================
10:03:08 | INFO | root | Context info:
10:03:08 | INFO | root | Context Name: paper_038_Jahansooz_et_al_2006_Radiation_and_water_use_assoc
Resources: Jahansooz et al 2006 Radiation and water use associated with growth and yields of wheat and chickpea
10:03:08 | INFO | root | ----------------------------------------
10:03:08 | INFO | root | Available players manifest
10:03:08 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:08 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:08 |   start mas …
10:03:08 |   fail  mas (no_output) in 0.1s
10:03:08 | [38/89] Study 39 · 039_Gunes_et_al_2007_Mineral_nutrition_of_wheat_ch
10:03:08 |   start direct_llm …

10:03:08 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:08 | INFO | run_wopke_100 |   start static_workflow …
10:03:08 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=78651 use_llm=False max_facts=200
10:03:08 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:08 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=78651) — output should be much shorter than the full paper
10:03:08 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=87298); calling LLM…

10:03:08 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:08 |   start static_workflow …

10:03:08 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:08 | INFO | run_wopke_100 |   start mas …
10:03:08 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:08 | INFO | root |   Players per step: 1
10:03:08 | INFO | root |   Debate rounds: 0
10:03:08 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:08 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:08 | INFO | root | ============================================================
10:03:08 | INFO | root | STARTING ORCHESTRATION
10:03:08 | INFO | root | Context: paper_039_Gunes_et_al_2007_Mineral_nutrition_of_wheat_chickp
10:03:08 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:08 | INFO | root | Output schema: WopkeOutput
10:03:08 | INFO | root | ============================================================
10:03:08 | INFO | root | ============================================================
10:03:08 | INFO | root | GENERATING PLAN
10:03:08 | INFO | root | Context: paper_039_Gunes_et_al_2007_Mineral_nutrition_of_wheat_chickp
10:03:08 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:08 | INFO | root | ============================================================
10:03:08 | INFO | root | Context info:
10:03:08 | INFO | root | Context Name: paper_039_Gunes_et_al_2007_Mineral_nutrition_of_wheat_chickp
Resources: Gunes et al 2007 Mineral nutrition of wheat, chickpea and lentil as affected by mixed cropping and soil mo
10:03:08 | INFO | root | ----------------------------------------
10:03:08 | INFO | root | Available players manifest
10:03:08 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:08 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:08 |   start mas …
10:03:08 |   fail  mas (no_output) in 0.1s
10:03:08 | [39/89] Study 40 · 040_Ofori_et_al_1988_Maize_cowpea_intercrop_system
10:03:08 |   start direct_llm …

10:03:09 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:09 | INFO | run_wopke_100 |   start static_workflow …
10:03:09 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=48079 use_llm=False max_facts=200
10:03:09 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:09 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=48079) — output should be much shorter than the full paper
10:03:09 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=56726); calling LLM…

10:03:09 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:09 |   start static_workflow …

10:03:09 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:09 | INFO | run_wopke_100 |   start mas …
10:03:09 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:09 | INFO | root |   Players per step: 1
10:03:09 | INFO | root |   Debate rounds: 0
10:03:09 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:09 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:09 | INFO | root | ============================================================
10:03:09 | INFO | root | STARTING ORCHESTRATION
10:03:09 | INFO | root | Context: paper_040_Ofori_et_al_1988_Maize_cowpea_intercrop_system_eff
10:03:09 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:09 | INFO | root | Output schema: WopkeOutput
10:03:09 | INFO | root | ============================================================
10:03:09 | INFO | root | ============================================================
10:03:09 | INFO | root | GENERATING PLAN
10:03:09 | INFO | root | Context: paper_040_Ofori_et_al_1988_Maize_cowpea_intercrop_system_eff
10:03:09 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:09 | INFO | root | ============================================================
10:03:09 | INFO | root | Context info:
10:03:09 | INFO | root | Context Name: paper_040_Ofori_et_al_1988_Maize_cowpea_intercrop_system_eff
Resources: Ofori et al 1988 Maize-cowpea intercrop system, effect of nitrogen fertilizer on productivity and efficiency
10:03:09 | INFO | root | ----------------------------------------
10:03:09 | INFO | root | Available players manifest
10:03:09 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:09 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:09 |   start mas …
10:03:09 |   fail  mas (no_output) in 0.1s
10:03:09 | [40/89] Study 41 · 041_Willey_et_al_1981_A_field_technique_for_separa
10:03:09 |   start direct_llm …

10:03:09 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:09 | INFO | run_wopke_100 |   start static_workflow …
10:03:09 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=23622 use_llm=False max_facts=200
10:03:09 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:09 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=23622) — output should be much shorter than the full paper
10:03:09 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=32269); calling LLM…

10:03:09 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:09 |   start static_workflow …

10:03:10 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:10 | INFO | run_wopke_100 |   start mas …
10:03:10 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:10 | INFO | root |   Players per step: 1
10:03:10 | INFO | root |   Debate rounds: 0
10:03:10 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:10 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:10 | INFO | root | ============================================================
10:03:10 | INFO | root | STARTING ORCHESTRATION
10:03:10 | INFO | root | Context: paper_041_Willey_et_al_1981_A_field_technique_for_separating
10:03:10 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:10 | INFO | root | Output schema: WopkeOutput
10:03:10 | INFO | root | ============================================================
10:03:10 | INFO | root | ============================================================
10:03:10 | INFO | root | GENERATING PLAN
10:03:10 | INFO | root | Context: paper_041_Willey_et_al_1981_A_field_technique_for_separating
10:03:10 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:10 | INFO | root | ============================================================
10:03:10 | INFO | root | Context info:
10:03:10 | INFO | root | Context Name: paper_041_Willey_et_al_1981_A_field_technique_for_separating
Resources: Willey et al 1981 A field technique for separating above and below ground interactions in intercropping
10:03:10 | INFO | root | ----------------------------------------
10:03:10 | INFO | root | Available players manifest
10:03:10 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:10 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:10 |   start mas …
10:03:10 |   fail  mas (no_output) in 0.1s
10:03:10 | [41/89] Study 42 · 042_Ntare_1990_Intercropping_morphologically_diffe
10:03:10 |   start direct_llm …

10:03:10 | INFO | run_wopke_100 |   error direct_llm after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:10 | INFO | run_wopke_100 |   start static_workflow …
10:03:10 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=24084 use_llm=False max_facts=200
10:03:10 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:10 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=24084) — output should be much shorter than the full paper
10:03:10 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=32731); calling LLM…

10:03:10 |   error direct_llm after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:10 |   start static_workflow …

10:03:10 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:10 | INFO | run_wopke_100 |   start mas …
10:03:10 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:10 | INFO | root |   Players per step: 1
10:03:10 | INFO | root |   Debate rounds: 0
10:03:10 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:10 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:10 | INFO | root | ============================================================
10:03:10 | INFO | root | STARTING ORCHESTRATION
10:03:10 | INFO | root | Context: paper_042_Ntare_1990_Intercropping_morphologically_different
10:03:10 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:10 | INFO | root | Output schema: WopkeOutput
10:03:10 | INFO | root | ============================================================
10:03:10 | INFO | root | ============================================================
10:03:10 | INFO | root | GENERATING PLAN
10:03:10 | INFO | root | Context: paper_042_Ntare_1990_Intercropping_morphologically_different
10:03:10 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:10 | INFO | root | ============================================================
10:03:10 | INFO | root | Context info:
10:03:10 | INFO | root | Context Name: paper_042_Ntare_1990_Intercropping_morphologically_different
Resources: Ntare 1990 Intercropping morphologically different cowpeas with pearl-,illite
10:03:10 | INFO | root | ----------------------------------------
10:03:10 | INFO | root | Available players manifest
10:03:10 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:10 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:10 |   start mas …
10:03:10 |   fail  mas (no_output) in 0.1s
10:03:10 | [42/89] Study 43 · 043_Chowdhury_et_al_1994_Comparison_of_nitrogen_ph
10:03:10 |   start direct_llm …

10:03:11 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:11 | INFO | run_wopke_100 |   start static_workflow …
10:03:11 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=43076 use_llm=False max_facts=200
10:03:11 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:11 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=43076) — output should be much shorter than the full paper
10:03:11 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=51723); calling LLM…

10:03:11 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:11 |   start static_workflow …

10:03:11 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:11 | INFO | run_wopke_100 |   start mas …
10:03:11 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:11 | INFO | root |   Players per step: 1
10:03:11 | INFO | root |   Debate rounds: 0
10:03:11 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:11 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:11 | INFO | root | ============================================================
10:03:11 | INFO | root | STARTING ORCHESTRATION
10:03:11 | INFO | root | Context: paper_043_Chowdhury_et_al_1994_Comparison_of_nitrogen_phosph
10:03:11 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:11 | INFO | root | Output schema: WopkeOutput
10:03:11 | INFO | root | ============================================================
10:03:11 | INFO | root | ============================================================
10:03:11 | INFO | root | GENERATING PLAN
10:03:11 | INFO | root | Context: paper_043_Chowdhury_et_al_1994_Comparison_of_nitrogen_phosph
10:03:11 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:11 | INFO | root | ============================================================
10:03:11 | INFO | root | Context info:
10:03:11 | INFO | root | Context Name: paper_043_Chowdhury_et_al_1994_Comparison_of_nitrogen_phosph
Resources: Chowdhury et al 1994 Comparison of nitrogen, phosphorus and potassium utilization
10:03:11 | INFO | root | ----------------------------------------
10:03:11 | INFO | root | Available players manifest
10:03:11 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:11 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:11 |   start mas …
10:03:11 |   fail  mas (no_output) in 0.1s
10:03:11 | [43/89] Study 44 · 044_Schmidtke_et_al_Soil_and_atmospheric_nitrogen_
10:03:11 |   start direct_llm …

10:03:11 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:11 | INFO | run_wopke_100 |   start static_workflow …
10:03:11 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=70261 use_llm=False max_facts=200
10:03:11 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:11 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=70261) — output should be much shorter than the full paper
10:03:11 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=78908); calling LLM…

10:03:11 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:11 |   start static_workflow …

10:03:12 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:12 | INFO | run_wopke_100 |   start mas …
10:03:12 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:12 | INFO | root |   Players per step: 1
10:03:12 | INFO | root |   Debate rounds: 0
10:03:12 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:12 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:12 | INFO | root | ============================================================
10:03:12 | INFO | root | STARTING ORCHESTRATION
10:03:12 | INFO | root | Context: paper_044_Schmidtke_et_al_Soil_and_atmospheric_nitrogen_upta
10:03:12 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:12 | INFO | root | Output schema: WopkeOutput
10:03:12 | INFO | root | ============================================================
10:03:12 | INFO | root | ============================================================
10:03:12 | INFO | root | GENERATING PLAN
10:03:12 | INFO | root | Context: paper_044_Schmidtke_et_al_Soil_and_atmospheric_nitrogen_upta
10:03:12 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:12 | INFO | root | ============================================================
10:03:12 | INFO | root | Context info:
10:03:12 | INFO | root | Context Name: paper_044_Schmidtke_et_al_Soil_and_atmospheric_nitrogen_upta
Resources: Schmidtke et al Soil and atmospheric nitrogen uptake by lentil and barley as monocrops and intercrops
10:03:12 | INFO | root | ----------------------------------------
10:03:12 | INFO | root | Available players manifest
10:03:12 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:12 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:12 |   start mas …
10:03:12 |   fail  mas (no_output) in 0.1s
10:03:12 | [44/89] Study 45 · 045_Akanvou_et_al_2001_Evaluating_the_use_of_two_c
10:03:12 |   start direct_llm …

10:03:12 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:12 | INFO | run_wopke_100 |   start static_workflow …
10:03:12 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=52128 use_llm=False max_facts=200
10:03:12 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:12 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=52128) — output should be much shorter than the full paper
10:03:12 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=60775); calling LLM…

10:03:12 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:12 |   start static_workflow …

10:03:12 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:12 | INFO | run_wopke_100 |   start mas …
10:03:12 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:12 | INFO | root |   Players per step: 1
10:03:12 | INFO | root |   Debate rounds: 0
10:03:12 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:12 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:12 | INFO | root | ============================================================
10:03:12 | INFO | root | STARTING ORCHESTRATION
10:03:12 | INFO | root | Context: paper_045_Akanvou_et_al_2001_Evaluating_the_use_of_two_contr
10:03:12 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:12 | INFO | root | Output schema: WopkeOutput
10:03:12 | INFO | root | ============================================================
10:03:12 | INFO | root | ============================================================
10:03:12 | INFO | root | GENERATING PLAN
10:03:12 | INFO | root | Context: paper_045_Akanvou_et_al_2001_Evaluating_the_use_of_two_contr
10:03:12 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:12 | INFO | root | ============================================================
10:03:12 | INFO | root | Context info:
10:03:12 | INFO | root | Context Name: paper_045_Akanvou_et_al_2001_Evaluating_the_use_of_two_contr
Resources: Akanvou et al 2001 Evaluating the use of two contrasting legume species as realy intercrop
10:03:12 | INFO | root | ----------------------------------------
10:03:12 | INFO | root | Available players manifest
10:03:12 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:12 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:12 |   start mas …
10:03:12 |   fail  mas (no_output) in 0.1s
10:03:12 | [45/89] Study 46 · 046_Moynihan_et_al_1996_Intercropping_annual_medic
10:03:12 |   start direct_llm …

10:03:13 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:13 | INFO | run_wopke_100 |   start static_workflow …
10:03:13 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=28272 use_llm=False max_facts=200
10:03:13 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:13 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=28272) — output should be much shorter than the full paper
10:03:13 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=36919); calling LLM…

10:03:13 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:13 |   start static_workflow …

10:03:13 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:13 | INFO | run_wopke_100 |   start mas …
10:03:13 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:13 | INFO | root |   Players per step: 1
10:03:13 | INFO | root |   Debate rounds: 0
10:03:13 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:13 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:13 | INFO | root | ============================================================
10:03:13 | INFO | root | STARTING ORCHESTRATION
10:03:13 | INFO | root | Context: paper_046_Moynihan_et_al_1996_Intercropping_annual_medic_wit
10:03:13 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:13 | INFO | root | Output schema: WopkeOutput
10:03:13 | INFO | root | ============================================================
10:03:13 | INFO | root | ============================================================
10:03:13 | INFO | root | GENERATING PLAN
10:03:13 | INFO | root | Context: paper_046_Moynihan_et_al_1996_Intercropping_annual_medic_wit
10:03:13 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:13 | INFO | root | ============================================================
10:03:13 | INFO | root | Context info:
10:03:13 | INFO | root | Context Name: paper_046_Moynihan_et_al_1996_Intercropping_annual_medic_wit
Resources: Moynihan et al 1996 Intercropping annual medic with conventional height and semidwarf barley grown for grain
10:03:13 | INFO | root | ----------------------------------------
10:03:13 | INFO | root | Available players manifest
10:03:13 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:13 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:13 |   start mas …
10:03:13 |   fail  mas (no_output) in 0.1s
10:03:13 | [46/89] Study 47 · 047_Reynolds_et_al_1994_Intercropping_wheat_and_ba
10:03:13 |   start direct_llm …

10:03:13 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:13 | INFO | run_wopke_100 |   start static_workflow …
10:03:13 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=54029 use_llm=False max_facts=200
10:03:13 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:13 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=54029) — output should be much shorter than the full paper
10:03:13 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=62676); calling LLM…

10:03:13 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:13 |   start static_workflow …

10:03:13 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:13 | INFO | run_wopke_100 |   start mas …
10:03:13 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:13 | INFO | root |   Players per step: 1
10:03:13 | INFO | root |   Debate rounds: 0
10:03:13 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:13 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:13 | INFO | root | ============================================================
10:03:13 | INFO | root | STARTING ORCHESTRATION
10:03:13 | INFO | root | Context: paper_047_Reynolds_et_al_1994_Intercropping_wheat_and_barley
10:03:13 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:13 | INFO | root | Output schema: WopkeOutput
10:03:13 | INFO | root | ============================================================
10:03:13 | INFO | root | ============================================================
10:03:13 | INFO | root | GENERATING PLAN
10:03:13 | INFO | root | Context: paper_047_Reynolds_et_al_1994_Intercropping_wheat_and_barley
10:03:13 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:13 | INFO | root | ============================================================
10:03:13 | INFO | root | Context info:
10:03:13 | INFO | root | Context Name: paper_047_Reynolds_et_al_1994_Intercropping_wheat_and_barley
Resources: Reynolds et al 1994 Intercropping wheat and barley with N fixing legume species
10:03:13 | INFO | root | ----------------------------------------
10:03:13 | INFO | root | Available players manifest
10:03:13 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:13 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:13 |   start mas …
10:03:14 |   fail  mas (no_output) in 0.1s
10:03:14 | [47/89] Study 48 · 048_Ofori_et_al_1987_Evaluation_of_N_fixation_and_
10:03:14 |   start direct_llm …

10:03:14 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:14 | INFO | run_wopke_100 |   start static_workflow …
10:03:14 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=53886 use_llm=False max_facts=200
10:03:14 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:14 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=53886) — output should be much shorter than the full paper
10:03:14 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=62533); calling LLM…

10:03:14 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:14 |   start static_workflow …

10:03:14 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:14 | INFO | run_wopke_100 |   start mas …
10:03:14 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:14 | INFO | root |   Players per step: 1
10:03:14 | INFO | root |   Debate rounds: 0
10:03:14 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:14 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:14 | INFO | root | ============================================================
10:03:14 | INFO | root | STARTING ORCHESTRATION
10:03:14 | INFO | root | Context: paper_048_Ofori_et_al_1987_Evaluation_of_N_fixation_and_nitr
10:03:14 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:14 | INFO | root | Output schema: WopkeOutput
10:03:14 | INFO | root | ============================================================
10:03:14 | INFO | root | ============================================================
10:03:14 | INFO | root | GENERATING PLAN
10:03:14 | INFO | root | Context: paper_048_Ofori_et_al_1987_Evaluation_of_N_fixation_and_nitr
10:03:14 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:14 | INFO | root | ============================================================
10:03:14 | INFO | root | Context info:
10:03:14 | INFO | root | Context Name: paper_048_Ofori_et_al_1987_Evaluation_of_N_fixation_and_nitr
Resources: Ofori et al 1987 Evaluation of N fixation and nitrogen economy of a maize-cowpea intercrop system using N
10:03:14 | INFO | root | ----------------------------------------
10:03:14 | INFO | root | Available players manifest
10:03:14 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:14 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:14 |   start mas …
10:03:14 |   fail  mas (no_output) in 0.1s
10:03:14 | [48/89] Study 49 · 049_Ofori_et_al_1987_Relative_sowing_time_and_dens
10:03:14 |   start direct_llm …

10:03:14 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:14 | INFO | run_wopke_100 |   start static_workflow …
10:03:14 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=38465 use_llm=False max_facts=200
10:03:14 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:14 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=38465) — output should be much shorter than the full paper
10:03:14 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=47112); calling LLM…

10:03:14 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:14 |   start static_workflow …

10:03:15 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:15 | INFO | run_wopke_100 |   start mas …
10:03:15 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:15 | INFO | root |   Players per step: 1
10:03:15 | INFO | root |   Debate rounds: 0
10:03:15 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:15 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:15 | INFO | root | ============================================================
10:03:15 | INFO | root | STARTING ORCHESTRATION
10:03:15 | INFO | root | Context: paper_049_Ofori_et_al_1987_Relative_sowing_time_and_density_
10:03:15 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:15 | INFO | root | Output schema: WopkeOutput
10:03:15 | INFO | root | ============================================================
10:03:15 | INFO | root | ============================================================
10:03:15 | INFO | root | GENERATING PLAN
10:03:15 | INFO | root | Context: paper_049_Ofori_et_al_1987_Relative_sowing_time_and_density_
10:03:15 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:15 | INFO | root | ============================================================
10:03:15 | INFO | root | Context info:
10:03:15 | INFO | root | Context Name: paper_049_Ofori_et_al_1987_Relative_sowing_time_and_density_
Resources: Ofori et al 1987 Relative sowing time and density of component crops in a maize cowpea intercrop system
10:03:15 | INFO | root | ----------------------------------------
10:03:15 | INFO | root | Available players manifest
10:03:15 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:15 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:15 |   start mas …
10:03:15 |   fail  mas (no_output) in 0.1s
10:03:15 | [49/89] Study 50 · 050_Ofori_et_al_1987_The_combined_effects_of_nitro
10:03:15 |   start direct_llm …

10:03:15 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:15 | INFO | run_wopke_100 |   start static_workflow …
10:03:15 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=28063 use_llm=False max_facts=200
10:03:15 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:15 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=28063) — output should be much shorter than the full paper
10:03:15 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=36710); calling LLM…

10:03:15 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:15 |   start static_workflow …

10:03:15 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:15 | INFO | run_wopke_100 |   start mas …
10:03:15 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:15 | INFO | root |   Players per step: 1
10:03:15 | INFO | root |   Debate rounds: 0
10:03:15 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:15 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:15 | INFO | root | ============================================================
10:03:15 | INFO | root | STARTING ORCHESTRATION
10:03:15 | INFO | root | Context: paper_050_Ofori_et_al_1987_The_combined_effects_of_nitrogen_
10:03:15 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:15 | INFO | root | Output schema: WopkeOutput
10:03:15 | INFO | root | ============================================================
10:03:15 | INFO | root | ============================================================
10:03:15 | INFO | root | GENERATING PLAN
10:03:15 | INFO | root | Context: paper_050_Ofori_et_al_1987_The_combined_effects_of_nitrogen_
10:03:15 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:15 | INFO | root | ============================================================
10:03:15 | INFO | root | Context info:
10:03:15 | INFO | root | Context Name: paper_050_Ofori_et_al_1987_The_combined_effects_of_nitrogen_
Resources: Ofori et al 1987 The combined effects of nitrogen fertilizer and density of the legume component on
10:03:15 | INFO | root | ----------------------------------------
10:03:15 | INFO | root | Available players manifest
10:03:15 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:15 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:15 |   start mas …
10:03:15 |   fail  mas (no_output) in 0.1s
10:03:15 | [50/89] Study 51 · 051_Mason_1986_Cassava_cowpea_and_cassava_peanut_i
10:03:15 |   start direct_llm …

10:03:16 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:16 | INFO | run_wopke_100 |   start static_workflow …
10:03:16 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=26114 use_llm=False max_facts=200
10:03:16 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:16 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=26114) — output should be much shorter than the full paper
10:03:16 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=34761); calling LLM…

10:03:16 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:16 |   start static_workflow …

10:03:16 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:16 | INFO | run_wopke_100 |   start mas …
10:03:16 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:16 | INFO | root |   Players per step: 1
10:03:16 | INFO | root |   Debate rounds: 0
10:03:16 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:16 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:16 | INFO | root | ============================================================
10:03:16 | INFO | root | STARTING ORCHESTRATION
10:03:16 | INFO | root | Context: paper_051_Mason_1986_Cassava_cowpea_and_cassava_peanut_inter
10:03:16 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:16 | INFO | root | Output schema: WopkeOutput
10:03:16 | INFO | root | ============================================================
10:03:16 | INFO | root | ============================================================
10:03:16 | INFO | root | GENERATING PLAN
10:03:16 | INFO | root | Context: paper_051_Mason_1986_Cassava_cowpea_and_cassava_peanut_inter
10:03:16 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:16 | INFO | root | ============================================================
10:03:16 | INFO | root | Context info:
10:03:16 | INFO | root | Context Name: paper_051_Mason_1986_Cassava_cowpea_and_cassava_peanut_inter
Resources: 1. Mason 1986 Cassava-cowpea and cassava-peanut intercropping II Leaf afrea index and dry matter accumulation
10:03:16 | INFO | root | ----------------------------------------
10:03:16 | INFO | root | Available players manifest
10:03:16 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:16 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:16 |   start mas …
10:03:16 |   fail  mas (no_output) in 0.1s
10:03:16 | [51/89] Study 52 · 052_Ong_et_al_1991The_microclimate_and_productivit
10:03:16 |   start direct_llm …

10:03:16 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:16 | INFO | run_wopke_100 |   start static_workflow …
10:03:16 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=54600 use_llm=False max_facts=200
10:03:16 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:16 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=54600) — output should be much shorter than the full paper
10:03:16 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=63247); calling LLM…

10:03:16 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:16 |   start static_workflow …

10:03:17 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:17 | INFO | run_wopke_100 |   start mas …
10:03:17 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:17 | INFO | root |   Players per step: 1
10:03:17 | INFO | root |   Debate rounds: 0
10:03:17 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:17 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:17 | INFO | root | ============================================================
10:03:17 | INFO | root | STARTING ORCHESTRATION
10:03:17 | INFO | root | Context: paper_052_Ong_et_al_1991The_microclimate_and_productivity_of
10:03:17 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:17 | INFO | root | Output schema: WopkeOutput
10:03:17 | INFO | root | ============================================================
10:03:17 | INFO | root | ============================================================
10:03:17 | INFO | root | GENERATING PLAN
10:03:17 | INFO | root | Context: paper_052_Ong_et_al_1991The_microclimate_and_productivity_of
10:03:17 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:17 | INFO | root | ============================================================
10:03:17 | INFO | root | Context info:
10:03:17 | INFO | root | Context Name: paper_052_Ong_et_al_1991The_microclimate_and_productivity_of
Resources: 3. Ong et al 1991The microclimate and productivity of a groudnut-millet intercrop during the rainy searson
10:03:17 | INFO | root | ----------------------------------------
10:03:17 | INFO | root | Available players manifest
10:03:17 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:17 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:17 |   start mas …
10:03:17 |   fail  mas (no_output) in 0.1s
10:03:17 | [52/89] Study 53 · 053_Vyas_2006_Productivity_and_economics_of_integr
10:03:17 |   start direct_llm …

10:03:17 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:17 | INFO | run_wopke_100 |   start static_workflow …
10:03:17 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=25604 use_llm=False max_facts=200
10:03:17 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:17 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=25604) — output should be much shorter than the full paper
10:03:17 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=34251); calling LLM…

10:03:17 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:17 |   start static_workflow …

10:03:17 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:17 | INFO | run_wopke_100 |   start mas …
10:03:17 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:17 | INFO | root |   Players per step: 1
10:03:17 | INFO | root |   Debate rounds: 0
10:03:17 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:17 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:17 | INFO | root | ============================================================
10:03:17 | INFO | root | STARTING ORCHESTRATION
10:03:17 | INFO | root | Context: paper_053_Vyas_2006_Productivity_and_economics_of_integrated
10:03:17 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:17 | INFO | root | Output schema: WopkeOutput
10:03:17 | INFO | root | ============================================================
10:03:17 | INFO | root | ============================================================
10:03:17 | INFO | root | GENERATING PLAN
10:03:17 | INFO | root | Context: paper_053_Vyas_2006_Productivity_and_economics_of_integrated
10:03:17 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:17 | INFO | root | ============================================================
10:03:17 | INFO | root | Context info:
10:03:17 | INFO | root | Context Name: paper_053_Vyas_2006_Productivity_and_economics_of_integrated
Resources: 4. Vyas 2006 Productivity and economics of integrated nutrient management in soybean (Glycine max) plus pigeonpea
10:03:17 | INFO | root | ----------------------------------------
10:03:17 | INFO | root | Available players manifest
10:03:17 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:17 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:17 |   start mas …
10:03:17 |   fail  mas (no_output) in 0.1s
10:03:17 | [53/89] Study 54 · 054_Morgado_2008_Optimum_plant_population_for_maiz
10:03:17 |   start direct_llm …

10:03:18 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:18 | INFO | run_wopke_100 |   start static_workflow …
10:03:18 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=45940 use_llm=False max_facts=200
10:03:18 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:18 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=45940) — output should be much shorter than the full paper
10:03:18 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=54587); calling LLM…

10:03:18 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:18 |   start static_workflow …

10:03:18 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:18 | INFO | run_wopke_100 |   start mas …
10:03:18 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:18 | INFO | root |   Players per step: 1
10:03:18 | INFO | root |   Debate rounds: 0
10:03:18 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:18 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:18 | INFO | root | ============================================================
10:03:18 | INFO | root | STARTING ORCHESTRATION
10:03:18 | INFO | root | Context: paper_054_Morgado_2008_Optimum_plant_population_for_maize_be
10:03:18 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:18 | INFO | root | Output schema: WopkeOutput
10:03:18 | INFO | root | ============================================================
10:03:18 | INFO | root | ============================================================
10:03:18 | INFO | root | GENERATING PLAN
10:03:18 | INFO | root | Context: paper_054_Morgado_2008_Optimum_plant_population_for_maize_be
10:03:18 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:18 | INFO | root | ============================================================
10:03:18 | INFO | root | Context info:
10:03:18 | INFO | root | Context Name: paper_054_Morgado_2008_Optimum_plant_population_for_maize_be
Resources: 5. Morgado 2008 Optimum plant population for maize-bean intercropping system in the Brazilian semi-arid region
10:03:18 | INFO | root | ----------------------------------------
10:03:18 | INFO | root | Available players manifest
10:03:18 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:18 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:18 |   start mas …
10:03:18 |   fail  mas (no_output) in 0.1s
10:03:18 | [54/89] Study 55 · 055_Reddy_et_al_1990_Genotype_effects_in_millet_co
10:03:18 |   start direct_llm …

10:03:18 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:18 | INFO | run_wopke_100 |   start static_workflow …
10:03:18 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=41969 use_llm=False max_facts=200
10:03:18 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:18 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=41969) — output should be much shorter than the full paper
10:03:18 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=50616); calling LLM…

10:03:18 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:18 |   start static_workflow …

10:03:19 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:19 | INFO | run_wopke_100 |   start mas …
10:03:19 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:19 | INFO | root |   Players per step: 1
10:03:19 | INFO | root |   Debate rounds: 0
10:03:19 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:19 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:19 | INFO | root | ============================================================
10:03:19 | INFO | root | STARTING ORCHESTRATION
10:03:19 | INFO | root | Context: paper_055_Reddy_et_al_1990_Genotype_effects_in_millet_cowpea
10:03:19 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:19 | INFO | root | Output schema: WopkeOutput
10:03:19 | INFO | root | ============================================================
10:03:19 | INFO | root | ============================================================
10:03:19 | INFO | root | GENERATING PLAN
10:03:19 | INFO | root | Context: paper_055_Reddy_et_al_1990_Genotype_effects_in_millet_cowpea
10:03:19 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:19 | INFO | root | ============================================================
10:03:19 | INFO | root | Context info:
10:03:19 | INFO | root | Context Name: paper_055_Reddy_et_al_1990_Genotype_effects_in_millet_cowpea
Resources: 8. Reddy et al 1990 Genotype effects in millet cowpea intercropping
10:03:19 | INFO | root | ----------------------------------------
10:03:19 | INFO | root | Available players manifest
10:03:19 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:19 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:19 |   start mas …
10:03:19 |   fail  mas (no_output) in 0.1s
10:03:19 | [55/89] Study 56 · 056_Behera_et_al_2002_Biological_and_economical_fe
10:03:19 |   start direct_llm …

10:03:19 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:19 | INFO | run_wopke_100 |   start static_workflow …
10:03:19 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=22404 use_llm=False max_facts=200
10:03:19 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:19 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=22404) — output should be much shorter than the full paper
10:03:19 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=31051); calling LLM…

10:03:19 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:19 |   start static_workflow …

10:03:19 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:19 | INFO | run_wopke_100 |   start mas …
10:03:19 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:19 | INFO | root |   Players per step: 1
10:03:19 | INFO | root |   Debate rounds: 0
10:03:19 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:19 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:19 | INFO | root | ============================================================
10:03:19 | INFO | root | STARTING ORCHESTRATION
10:03:19 | INFO | root | Context: paper_056_Behera_et_al_2002_Biological_and_economical_feasib
10:03:19 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:19 | INFO | root | Output schema: WopkeOutput
10:03:19 | INFO | root | ============================================================
10:03:19 | INFO | root | ============================================================
10:03:19 | INFO | root | GENERATING PLAN
10:03:19 | INFO | root | Context: paper_056_Behera_et_al_2002_Biological_and_economical_feasib
10:03:19 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:19 | INFO | root | ============================================================
10:03:19 | INFO | root | Context info:
10:03:19 | INFO | root | Context Name: paper_056_Behera_et_al_2002_Biological_and_economical_feasib
Resources: 11. Behera et al 2002 Biological and economical feasibility of intercroppign vegetables
10:03:19 | INFO | root | ----------------------------------------
10:03:19 | INFO | root | Available players manifest
10:03:19 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:19 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:19 |   start mas …
10:03:19 |   fail  mas (no_output) in 0.1s
10:03:19 | [56/89] Study 57 · 057_Giri_1990_Studies_on_pigeonpea_and_groundnut_i
10:03:19 |   start direct_llm …

10:03:20 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:20 | INFO | run_wopke_100 |   start static_workflow …
10:03:20 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=14181 use_llm=False max_facts=200
10:03:20 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:20 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=14181) — output should be much shorter than the full paper
10:03:20 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=22828); calling LLM…

10:03:20 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:20 |   start static_workflow …

10:03:20 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:20 | INFO | run_wopke_100 |   start mas …
10:03:20 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:20 | INFO | root |   Players per step: 1
10:03:20 | INFO | root |   Debate rounds: 0
10:03:20 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:20 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:20 | INFO | root | ============================================================
10:03:20 | INFO | root | STARTING ORCHESTRATION
10:03:20 | INFO | root | Context: paper_057_Giri_1990_Studies_on_pigeonpea_and_groundnut_intec
10:03:20 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:20 | INFO | root | Output schema: WopkeOutput
10:03:20 | INFO | root | ============================================================
10:03:20 | INFO | root | ============================================================
10:03:20 | INFO | root | GENERATING PLAN
10:03:20 | INFO | root | Context: paper_057_Giri_1990_Studies_on_pigeonpea_and_groundnut_intec
10:03:20 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:20 | INFO | root | ============================================================
10:03:20 | INFO | root | Context info:
10:03:20 | INFO | root | Context Name: paper_057_Giri_1990_Studies_on_pigeonpea_and_groundnut_intec
Resources: 12. Giri 1990 Studies on pigeonpea and groundnut intecropping under rainfed conditions
10:03:20 | INFO | root | ----------------------------------------
10:03:20 | INFO | root | Available players manifest
10:03:20 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:20 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:20 |   start mas …
10:03:20 |   fail  mas (no_output) in 0.1s
10:03:20 | [57/89] Study 58 · 058_Ossom_et_al_2005_intercropping_maize_with_grai
10:03:20 |   start direct_llm …

10:03:20 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:20 | INFO | run_wopke_100 |   start static_workflow …
10:03:20 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=48910 use_llm=False max_facts=200
10:03:20 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:20 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=48910) — output should be much shorter than the full paper
10:03:20 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=57557); calling LLM…

10:03:20 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:20 |   start static_workflow …

10:03:21 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:21 | INFO | run_wopke_100 |   start mas …
10:03:21 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:21 | INFO | root |   Players per step: 1
10:03:21 | INFO | root |   Debate rounds: 0
10:03:21 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:21 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:21 | INFO | root | ============================================================
10:03:21 | INFO | root | STARTING ORCHESTRATION
10:03:21 | INFO | root | Context: paper_058_Ossom_et_al_2005_intercropping_maize_with_grain_le
10:03:21 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:21 | INFO | root | Output schema: WopkeOutput
10:03:21 | INFO | root | ============================================================
10:03:21 | INFO | root | ============================================================
10:03:21 | INFO | root | GENERATING PLAN
10:03:21 | INFO | root | Context: paper_058_Ossom_et_al_2005_intercropping_maize_with_grain_le
10:03:21 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:21 | INFO | root | ============================================================
10:03:21 | INFO | root | Context info:
10:03:21 | INFO | root | Context Name: paper_058_Ossom_et_al_2005_intercropping_maize_with_grain_le
Resources: 13. Ossom et al 2005 intercropping maize with grain legumes influences weed suppression
10:03:21 | INFO | root | ----------------------------------------
10:03:21 | INFO | root | Available players manifest
10:03:21 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:21 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:21 |   start mas …
10:03:21 |   fail  mas (no_output) in 0.1s
10:03:21 | [58/89] Study 59 · 059_Tomar_et_al_1987_Effect_of_planting_patterns_i
10:03:21 |   start direct_llm …

10:03:21 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:21 | INFO | run_wopke_100 |   start static_workflow …
10:03:21 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=10391 use_llm=False max_facts=200
10:03:21 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:21 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=10391) — output should be much shorter than the full paper
10:03:21 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=19038); calling LLM…

10:03:21 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:21 |   start static_workflow …

10:03:21 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:21 | INFO | run_wopke_100 |   start mas …
10:03:21 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:21 | INFO | root |   Players per step: 1
10:03:21 | INFO | root |   Debate rounds: 0
10:03:21 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:21 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:21 | INFO | root | ============================================================
10:03:21 | INFO | root | STARTING ORCHESTRATION
10:03:21 | INFO | root | Context: paper_059_Tomar_et_al_1987_Effect_of_planting_patterns_in_pi
10:03:21 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:21 | INFO | root | Output schema: WopkeOutput
10:03:21 | INFO | root | ============================================================
10:03:21 | INFO | root | ============================================================
10:03:21 | INFO | root | GENERATING PLAN
10:03:21 | INFO | root | Context: paper_059_Tomar_et_al_1987_Effect_of_planting_patterns_in_pi
10:03:21 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:21 | INFO | root | ============================================================
10:03:21 | INFO | root | Context info:
10:03:21 | INFO | root | Context Name: paper_059_Tomar_et_al_1987_Effect_of_planting_patterns_in_pi
Resources: 14. Tomar et al 1987 Effect of planting patterns in pigeonpea and soybean intercropping system
10:03:21 | INFO | root | ----------------------------------------
10:03:21 | INFO | root | Available players manifest
10:03:21 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:21 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:21 |   start mas …
10:03:21 |   fail  mas (no_output) in 0.1s
10:03:21 | [59/89] Study 60 · 060_Ahmed_et_al_2000_Studies_on_yield_land_equival
10:03:21 |   start direct_llm …

10:03:22 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:22 | INFO | run_wopke_100 |   start static_workflow …
10:03:22 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=34051 use_llm=False max_facts=200
10:03:22 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:22 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=34051) — output should be much shorter than the full paper
10:03:22 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=42698); calling LLM…

10:03:22 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:22 |   start static_workflow …

10:03:22 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:22 | INFO | run_wopke_100 |   start mas …
10:03:22 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:22 | INFO | root |   Players per step: 1
10:03:22 | INFO | root |   Debate rounds: 0
10:03:22 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:22 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:22 | INFO | root | ============================================================
10:03:22 | INFO | root | STARTING ORCHESTRATION
10:03:22 | INFO | root | Context: paper_060_Ahmed_et_al_2000_Studies_on_yield_land_equivalent_
10:03:22 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:22 | INFO | root | Output schema: WopkeOutput
10:03:22 | INFO | root | ============================================================
10:03:22 | INFO | root | ============================================================
10:03:22 | INFO | root | GENERATING PLAN
10:03:22 | INFO | root | Context: paper_060_Ahmed_et_al_2000_Studies_on_yield_land_equivalent_
10:03:22 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:22 | INFO | root | ============================================================
10:03:22 | INFO | root | Context info:
10:03:22 | INFO | root | Context Name: paper_060_Ahmed_et_al_2000_Studies_on_yield_land_equivalent_
Resources: 15. Ahmed et al 2000 Studies on yield, land equivalent ratio and crop performance rate in maize-mungbean intercropping
10:03:22 | INFO | root | ----------------------------------------
10:03:22 | INFO | root | Available players manifest
10:03:22 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:22 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:22 |   start mas …
10:03:22 |   fail  mas (no_output) in 0.1s
10:03:22 | [60/89] Study 61 · 061_Sarkar_et_al_2000_Production_potential_and_eco
10:03:22 |   start direct_llm …

10:03:22 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:22 | INFO | run_wopke_100 |   start static_workflow …
10:03:22 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=20072 use_llm=False max_facts=200
10:03:22 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:22 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=20072) — output should be much shorter than the full paper
10:03:22 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=28719); calling LLM…

10:03:22 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:22 |   start static_workflow …

10:03:23 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:23 | INFO | run_wopke_100 |   start mas …
10:03:23 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:23 | INFO | root |   Players per step: 1
10:03:23 | INFO | root |   Debate rounds: 0
10:03:23 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:23 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:23 | INFO | root | ============================================================
10:03:23 | INFO | root | STARTING ORCHESTRATION
10:03:23 | INFO | root | Context: paper_061_Sarkar_et_al_2000_Production_potential_and_economi
10:03:23 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:23 | INFO | root | Output schema: WopkeOutput
10:03:23 | INFO | root | ============================================================
10:03:23 | INFO | root | ============================================================
10:03:23 | INFO | root | GENERATING PLAN
10:03:23 | INFO | root | Context: paper_061_Sarkar_et_al_2000_Production_potential_and_economi
10:03:23 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:23 | INFO | root | ============================================================
10:03:23 | INFO | root | Context info:
10:03:23 | INFO | root | Context Name: paper_061_Sarkar_et_al_2000_Production_potential_and_economi
Resources: 16. Sarkar et al 2000 Production potential and economic feasibility and sasame based intercropping system
10:03:23 | INFO | root | ----------------------------------------
10:03:23 | INFO | root | Available players manifest
10:03:23 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:23 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:23 |   start mas …
10:03:23 |   fail  mas (no_output) in 0.1s
10:03:23 | [61/89] Study 62 · 062_Subramanian_et_al_1987_Intercropping_effects_o
10:03:23 |   start direct_llm …

10:03:23 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:23 | INFO | run_wopke_100 |   start static_workflow …
10:03:23 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=29042 use_llm=False max_facts=200
10:03:23 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:23 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=29042) — output should be much shorter than the full paper
10:03:23 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=37689); calling LLM…

10:03:23 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:23 |   start static_workflow …

10:03:23 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:23 | INFO | run_wopke_100 |   start mas …
10:03:23 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:23 | INFO | root |   Players per step: 1
10:03:23 | INFO | root |   Debate rounds: 0
10:03:23 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:23 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:23 | INFO | root | ============================================================
10:03:23 | INFO | root | STARTING ORCHESTRATION
10:03:23 | INFO | root | Context: paper_062_Subramanian_et_al_1987_Intercropping_effects_on_yi
10:03:23 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:23 | INFO | root | Output schema: WopkeOutput
10:03:23 | INFO | root | ============================================================
10:03:23 | INFO | root | ============================================================
10:03:23 | INFO | root | GENERATING PLAN
10:03:23 | INFO | root | Context: paper_062_Subramanian_et_al_1987_Intercropping_effects_on_yi
10:03:23 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:23 | INFO | root | ============================================================
10:03:24 | INFO | root | Context info:
10:03:24 | INFO | root | Context Name: paper_062_Subramanian_et_al_1987_Intercropping_effects_on_yi
Resources: 17. Subramanian et al 1987 Intercropping effects on yield components of dryland sorghum, pigeon pea and mung bean
10:03:24 | INFO | root | ----------------------------------------
10:03:24 | INFO | root | Available players manifest
10:03:24 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:23 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:23 |   start mas …
10:03:24 |   fail  mas (no_output) in 0.1s
10:03:24 | [62/89] Study 63 · 063_Mustsaers_1978_Mixed_cropping_experiements_wit
10:03:24 |   start direct_llm …

10:03:24 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:24 | INFO | run_wopke_100 |   start static_workflow …
10:03:24 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=33336 use_llm=False max_facts=200
10:03:24 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:24 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=33336) — output should be much shorter than the full paper
10:03:24 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=41983); calling LLM…

10:03:24 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:24 |   start static_workflow …

10:03:24 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:24 | INFO | run_wopke_100 |   start mas …
10:03:24 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:24 | INFO | root |   Players per step: 1
10:03:24 | INFO | root |   Debate rounds: 0
10:03:24 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:24 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:24 | INFO | root | ============================================================
10:03:24 | INFO | root | STARTING ORCHESTRATION
10:03:24 | INFO | root | Context: paper_063_Mustsaers_1978_Mixed_cropping_experiements_with_ma
10:03:24 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:24 | INFO | root | Output schema: WopkeOutput
10:03:24 | INFO | root | ============================================================
10:03:24 | INFO | root | ============================================================
10:03:24 | INFO | root | GENERATING PLAN
10:03:24 | INFO | root | Context: paper_063_Mustsaers_1978_Mixed_cropping_experiements_with_ma
10:03:24 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:24 | INFO | root | ============================================================
10:03:24 | INFO | root | Context info:
10:03:24 | INFO | root | Context Name: paper_063_Mustsaers_1978_Mixed_cropping_experiements_with_ma
Resources: 18. Mustsaers 1978 Mixed cropping experiements with maize and groudnuts
10:03:24 | INFO | root | ----------------------------------------
10:03:24 | INFO | root | Available players manifest
10:03:24 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:24 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:24 |   start mas …
10:03:24 |   fail  mas (no_output) in 0.1s
10:03:24 | [63/89] Study 64 · 064_Ogbuehi_et_al_1987_Intercropping_carrot_and_sw
10:03:24 |   start direct_llm …

10:03:24 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:24 | INFO | run_wopke_100 |   start static_workflow …
10:03:24 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=27973 use_llm=False max_facts=200
10:03:24 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:24 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=27973) — output should be much shorter than the full paper
10:03:24 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=36620); calling LLM…

10:03:24 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:24 |   start static_workflow …

10:03:25 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:25 | INFO | run_wopke_100 |   start mas …
10:03:25 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:25 | INFO | root |   Players per step: 1
10:03:25 | INFO | root |   Debate rounds: 0
10:03:25 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:25 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:25 | INFO | root | ============================================================
10:03:25 | INFO | root | STARTING ORCHESTRATION
10:03:25 | INFO | root | Context: paper_064_Ogbuehi_et_al_1987_Intercropping_carrot_and_sweetc
10:03:25 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:25 | INFO | root | Output schema: WopkeOutput
10:03:25 | INFO | root | ============================================================
10:03:25 | INFO | root | ============================================================
10:03:25 | INFO | root | GENERATING PLAN
10:03:25 | INFO | root | Context: paper_064_Ogbuehi_et_al_1987_Intercropping_carrot_and_sweetc
10:03:25 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:25 | INFO | root | ============================================================
10:03:25 | INFO | root | Context info:
10:03:25 | INFO | root | Context Name: paper_064_Ogbuehi_et_al_1987_Intercropping_carrot_and_sweetc
Resources: 19. Ogbuehi et al 1987 Intercropping carrot and sweetcorn in a multiple cropping system
10:03:25 | INFO | root | ----------------------------------------
10:03:25 | INFO | root | Available players manifest
10:03:25 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:25 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:25 |   start mas …
10:03:25 |   fail  mas (no_output) in 0.1s
10:03:25 | [64/89] Study 65 · 065_Mei_et_al_2012_Maize_faba_bean_intercropping_w
10:03:25 |   start direct_llm …

10:03:25 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:25 | INFO | run_wopke_100 |   start static_workflow …
10:03:25 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=80368 use_llm=False max_facts=200
10:03:25 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:25 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=80368) — output should be much shorter than the full paper
10:03:25 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=89015); calling LLM…

10:03:25 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:25 |   start static_workflow …

10:03:25 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:25 | INFO | run_wopke_100 |   start mas …
10:03:25 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:25 | INFO | root |   Players per step: 1
10:03:25 | INFO | root |   Debate rounds: 0
10:03:25 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:25 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:25 | INFO | root | ============================================================
10:03:25 | INFO | root | STARTING ORCHESTRATION
10:03:25 | INFO | root | Context: paper_065_Mei_et_al_2012_Maize_faba_bean_intercropping_with_
10:03:25 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:25 | INFO | root | Output schema: WopkeOutput
10:03:25 | INFO | root | ============================================================
10:03:25 | INFO | root | ============================================================
10:03:26 | INFO | root | GENERATING PLAN
10:03:26 | INFO | root | Context: paper_065_Mei_et_al_2012_Maize_faba_bean_intercropping_with_
10:03:26 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:26 | INFO | root | ============================================================
10:03:26 | INFO | root | Context info:
10:03:26 | INFO | root | Context Name: paper_065_Mei_et_al_2012_Maize_faba_bean_intercropping_with_
Resources: 20. Mei et al 2012 Maize-faba bean intercropping with rhizobia inoculation enhances productivity and recovery
10:03:26 | INFO | root | ----------------------------------------
10:03:26 | INFO | root | Available players manifest
10:03:26 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:25 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:25 |   start mas …
10:03:26 |   fail  mas (no_output) in 0.1s
10:03:26 | [65/89] Study 66 · 066_Ciftci_et_al_2005_Economic_benefits_ofmixed_cr
10:03:26 |   start direct_llm …

10:03:26 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:26 | INFO | run_wopke_100 |   start static_workflow …
10:03:26 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=24345 use_llm=False max_facts=200
10:03:26 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:26 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=24345) — output should be much shorter than the full paper
10:03:26 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=32992); calling LLM…

10:03:26 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:26 |   start static_workflow …

10:03:26 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:26 | INFO | run_wopke_100 |   start mas …
10:03:26 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:26 | INFO | root |   Players per step: 1
10:03:26 | INFO | root |   Debate rounds: 0
10:03:26 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:26 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:26 | INFO | root | ============================================================
10:03:26 | INFO | root | STARTING ORCHESTRATION
10:03:26 | INFO | root | Context: paper_066_Ciftci_et_al_2005_Economic_benefits_ofmixed_croppi
10:03:26 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:26 | INFO | root | Output schema: WopkeOutput
10:03:26 | INFO | root | ============================================================
10:03:26 | INFO | root | ============================================================
10:03:26 | INFO | root | GENERATING PLAN
10:03:26 | INFO | root | Context: paper_066_Ciftci_et_al_2005_Economic_benefits_ofmixed_croppi
10:03:26 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:26 | INFO | root | ============================================================
10:03:26 | INFO | root | Context info:
10:03:26 | INFO | root | Context Name: paper_066_Ciftci_et_al_2005_Economic_benefits_ofmixed_croppi
Resources: 21. Ciftci et al 2005 Economic benefits ofmixed cropping of lentil with wheat and barley
10:03:26 | INFO | root | ----------------------------------------
10:03:26 | INFO | root | Available players manifest
10:03:26 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:26 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:26 |   start mas …
10:03:26 |   fail  mas (no_output) in 0.1s
10:03:26 | [66/89] Study 67 · 067_Morgado_et_al_2003_Effects_of_plant_population
10:03:26 |   start direct_llm …

10:03:26 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:26 | INFO | run_wopke_100 |   start static_workflow …
10:03:26 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=41371 use_llm=False max_facts=200
10:03:26 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:26 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=41371) — output should be much shorter than the full paper
10:03:26 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=50018); calling LLM…

10:03:26 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:26 |   start static_workflow …

10:03:27 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:27 | INFO | run_wopke_100 |   start mas …
10:03:27 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:27 | INFO | root |   Players per step: 1
10:03:27 | INFO | root |   Debate rounds: 0
10:03:27 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:27 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:27 | INFO | root | ============================================================
10:03:27 | INFO | root | STARTING ORCHESTRATION
10:03:27 | INFO | root | Context: paper_067_Morgado_et_al_2003_Effects_of_plant_population_and
10:03:27 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:27 | INFO | root | Output schema: WopkeOutput
10:03:27 | INFO | root | ============================================================
10:03:27 | INFO | root | ============================================================
10:03:27 | INFO | root | GENERATING PLAN
10:03:27 | INFO | root | Context: paper_067_Morgado_et_al_2003_Effects_of_plant_population_and
10:03:27 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:27 | INFO | root | ============================================================
10:03:27 | INFO | root | Context info:
10:03:27 | INFO | root | Context Name: paper_067_Morgado_et_al_2003_Effects_of_plant_population_and
Resources: 23. Morgado et al 2003 Effects of plant population and nitrogen fertilizer on yield and efficiency
10:03:27 | INFO | root | ----------------------------------------
10:03:27 | INFO | root | Available players manifest
10:03:27 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:27 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:27 |   start mas …
10:03:27 |   fail  mas (no_output) in 0.1s
10:03:27 | [67/89] Study 68 · 068_Subedi_1998_Profitability_of_barley_and_peas_m
10:03:27 |   start direct_llm …

10:03:27 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:27 | INFO | run_wopke_100 |   start static_workflow …
10:03:27 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=40121 use_llm=False max_facts=200
10:03:27 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:27 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=40121) — output should be much shorter than the full paper
10:03:27 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=48768); calling LLM…

10:03:27 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:27 |   start static_workflow …

10:03:27 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:27 | INFO | run_wopke_100 |   start mas …
10:03:27 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:27 | INFO | root |   Players per step: 1
10:03:27 | INFO | root |   Debate rounds: 0
10:03:27 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:27 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:27 | INFO | root | ============================================================
10:03:27 | INFO | root | STARTING ORCHESTRATION
10:03:27 | INFO | root | Context: paper_068_Subedi_1998_Profitability_of_barley_and_peas_mixed
10:03:27 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:27 | INFO | root | Output schema: WopkeOutput
10:03:27 | INFO | root | ============================================================
10:03:27 | INFO | root | ============================================================
10:03:27 | INFO | root | GENERATING PLAN
10:03:27 | INFO | root | Context: paper_068_Subedi_1998_Profitability_of_barley_and_peas_mixed
10:03:27 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:27 | INFO | root | ============================================================
10:03:27 | INFO | root | Context info:
10:03:27 | INFO | root | Context Name: paper_068_Subedi_1998_Profitability_of_barley_and_peas_mixed
Resources: 24. Subedi 1998 Profitability of barley and peas mixed intercropping in the subsistence farming systems
10:03:27 | INFO | root | ----------------------------------------
10:03:27 | INFO | root | Available players manifest
10:03:27 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:27 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:27 |   start mas …
10:03:27 |   fail  mas (no_output) in 0.1s
10:03:27 | [68/89] Study 69 · 069_Gao_et_al_2010_Distribution_of_roots_and_root_
10:03:27 |   start direct_llm …

10:03:28 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:28 | INFO | run_wopke_100 |   start static_workflow …
10:03:28 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=66891 use_llm=False max_facts=200
10:03:28 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:28 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=66891) — output should be much shorter than the full paper
10:03:28 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=75538); calling LLM…

10:03:28 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:28 |   start static_workflow …

10:03:28 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:28 | INFO | run_wopke_100 |   start mas …
10:03:28 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:28 | INFO | root |   Players per step: 1
10:03:28 | INFO | root |   Debate rounds: 0
10:03:28 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:28 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:28 | INFO | root | ============================================================
10:03:28 | INFO | root | STARTING ORCHESTRATION
10:03:28 | INFO | root | Context: paper_069_Gao_et_al_2010_Distribution_of_roots_and_root_leng
10:03:28 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:28 | INFO | root | Output schema: WopkeOutput
10:03:28 | INFO | root | ============================================================
10:03:28 | INFO | root | ============================================================
10:03:28 | INFO | root | GENERATING PLAN
10:03:28 | INFO | root | Context: paper_069_Gao_et_al_2010_Distribution_of_roots_and_root_leng
10:03:28 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:28 | INFO | root | ============================================================
10:03:28 | INFO | root | Context info:
10:03:28 | INFO | root | Context Name: paper_069_Gao_et_al_2010_Distribution_of_roots_and_root_leng
Resources: 26. Gao et al 2010 Distribution of roots and root length density
10:03:28 | INFO | root | ----------------------------------------
10:03:28 | INFO | root | Available players manifest
10:03:28 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:28 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:28 |   start mas …
10:03:28 |   fail  mas (no_output) in 0.1s
10:03:28 | [69/89] Study 70 · 070_Das_et_al_1991_Studies_on_pigeonpea_and_ground
10:03:28 |   start direct_llm …

10:03:28 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:28 | INFO | run_wopke_100 |   start static_workflow …
10:03:28 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=10065 use_llm=False max_facts=200
10:03:28 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:28 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=10065) — output should be much shorter than the full paper
10:03:28 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=18712); calling LLM…

10:03:28 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:28 |   start static_workflow …

10:03:29 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:29 | INFO | run_wopke_100 |   start mas …
10:03:29 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:29 | INFO | root |   Players per step: 1
10:03:29 | INFO | root |   Debate rounds: 0
10:03:29 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:29 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:29 | INFO | root | ============================================================
10:03:29 | INFO | root | STARTING ORCHESTRATION
10:03:29 | INFO | root | Context: paper_070_Das_et_al_1991_Studies_on_pigeonpea_and_groundnut_
10:03:29 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:29 | INFO | root | Output schema: WopkeOutput
10:03:29 | INFO | root | ============================================================
10:03:29 | INFO | root | ============================================================
10:03:29 | INFO | root | GENERATING PLAN
10:03:29 | INFO | root | Context: paper_070_Das_et_al_1991_Studies_on_pigeonpea_and_groundnut_
10:03:29 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:29 | INFO | root | ============================================================
10:03:29 | INFO | root | Context info:
10:03:29 | INFO | root | Context Name: paper_070_Das_et_al_1991_Studies_on_pigeonpea_and_groundnut_
Resources: 27. Das et al 1991 Studies on pigeonpea and groundnut intercropping system
10:03:29 | INFO | root | ----------------------------------------
10:03:29 | INFO | root | Available players manifest
10:03:29 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:29 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:29 |   start mas …
10:03:29 |   fail  mas (no_output) in 0.1s
10:03:29 | [70/89] Study 71 · 071_Nelson_et_al_2012_Yield_and_weed_suppression_o
10:03:29 |   start direct_llm …

10:03:29 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:29 | INFO | run_wopke_100 |   start static_workflow …
10:03:29 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=53272 use_llm=False max_facts=200
10:03:29 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:29 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=53272) — output should be much shorter than the full paper
10:03:29 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=61919); calling LLM…

10:03:29 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:29 |   start static_workflow …

10:03:29 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:29 | INFO | run_wopke_100 |   start mas …
10:03:29 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:29 | INFO | root |   Players per step: 1
10:03:29 | INFO | root |   Debate rounds: 0
10:03:29 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:29 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:29 | INFO | root | ============================================================
10:03:29 | INFO | root | STARTING ORCHESTRATION
10:03:29 | INFO | root | Context: paper_071_Nelson_et_al_2012_Yield_and_weed_suppression_of_cr
10:03:29 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:29 | INFO | root | Output schema: WopkeOutput
10:03:29 | INFO | root | ============================================================
10:03:29 | INFO | root | ============================================================
10:03:29 | INFO | root | GENERATING PLAN
10:03:29 | INFO | root | Context: paper_071_Nelson_et_al_2012_Yield_and_weed_suppression_of_cr
10:03:29 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:29 | INFO | root | ============================================================
10:03:29 | INFO | root | Context info:
10:03:29 | INFO | root | Context Name: paper_071_Nelson_et_al_2012_Yield_and_weed_suppression_of_cr
Resources: 29. Nelson et al 2012 Yield and weed suppression of crop mixtures in organic
10:03:29 | INFO | root | ----------------------------------------
10:03:29 | INFO | root | Available players manifest
10:03:29 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:29 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:29 |   start mas …
10:03:29 |   fail  mas (no_output) in 0.1s
10:03:29 | [71/89] Study 72 · 072_Agegnehu_et_al_2008_Yield_potential_and_land_u
10:03:29 |   start direct_llm …

10:03:30 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:30 | INFO | run_wopke_100 |   start static_workflow …
10:03:30 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=49163 use_llm=False max_facts=200
10:03:30 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:30 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=49163) — output should be much shorter than the full paper
10:03:30 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=57810); calling LLM…

10:03:30 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:30 |   start static_workflow …

10:03:30 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:30 | INFO | run_wopke_100 |   start mas …
10:03:30 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:30 | INFO | root |   Players per step: 1
10:03:30 | INFO | root |   Debate rounds: 0
10:03:30 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:30 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:30 | INFO | root | ============================================================
10:03:30 | INFO | root | STARTING ORCHESTRATION
10:03:30 | INFO | root | Context: paper_072_Agegnehu_et_al_2008_Yield_potential_and_land_use_e
10:03:30 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:30 | INFO | root | Output schema: WopkeOutput
10:03:30 | INFO | root | ============================================================
10:03:30 | INFO | root | ============================================================
10:03:30 | INFO | root | GENERATING PLAN
10:03:30 | INFO | root | Context: paper_072_Agegnehu_et_al_2008_Yield_potential_and_land_use_e
10:03:30 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:30 | INFO | root | ============================================================
10:03:30 | INFO | root | Context info:
10:03:30 | INFO | root | Context Name: paper_072_Agegnehu_et_al_2008_Yield_potential_and_land_use_e
Resources: 30. Agegnehu et al 2008 Yield potential and land use efficiency of wheat and faba bean mixed intercropping
10:03:30 | INFO | root | ----------------------------------------
10:03:30 | INFO | root | Available players manifest
10:03:30 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:30 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:30 |   start mas …
10:03:30 |   fail  mas (no_output) in 0.1s
10:03:30 | [72/89] Study 73 · 073_Mason_et_al_1987_Intercropping_in_a_temperate_
10:03:30 |   start direct_llm …

10:03:30 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:30 | INFO | run_wopke_100 |   start static_workflow …
10:03:30 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=34429 use_llm=False max_facts=200
10:03:30 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:30 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=34429) — output should be much shorter than the full paper
10:03:30 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=43076); calling LLM…
10:03:30 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:30 | INFO | run_wopke_100 |   start mas …
10:03:30 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:30 | INFO | root |   Players per step: 1
10:03:30 | INFO | root |   Debate rounds: 0
10:03:30 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:30 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:30 | INFO | root | ============================================================
10:03:30 | INFO | root | STARTING ORCHESTRATION
10:03:30 | INFO | root | Context: paper_073_Mason_et_al_1987_Intercropping_in_a_temperate_envi
10:03:30 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:30 | INFO | root | Output schema: WopkeOutput
10:03:30 | INFO | root | ============================================================
10:03:30 | INFO | root | ============================================================
10:03:30 | INFO | root | GENERATING PLAN
10:03:30 | INFO | root | Context: paper_073_Mason_et_al_1987_Intercropping_in_a_temperate_envi
10:03:30 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:30 | INFO | root | ============================================================
10:03:30 | INFO | root | Context info:
10:03:30 | INFO | root | Context Name: paper_073_Mason_et_al_1987_Intercropping_in_a_temperate_envi
Resources: 31. Mason et al 1987 Intercropping in a temperate environment for irrigated fodder production
10:03:30 | INFO | root | ----------------------------------------

10:03:30 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:30 |   start static_workflow …
10:03:30 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:30 |   start mas …

10:03:30 | INFO | root | Available players manifest
10:03:30 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor
  Description: You are an expert agricultural data extraction specialist. Your task is to extract **measured crop yield information** and related agronomic/context variables from scientific research papers. **Maximize recall:** your output list should include **every** distinct experiment-level or table-level data row the paper supports, not a summary.

**MULTI-STEP REASONING PROCESS**

### STEP 1: Anchor Identification
Scan the **entire** content (paragraphs, **all** tables row-by-row, captions, footnotes, supplements) and locate **every** sentence or cell that reports **actual measured** yields, densities, inputs, or other schema fields. Ignore model metrics (RMSE, R²), yield *gaps*, and purely simulated outputs.

### STEP 2: Contextual Reasoning
For **each** anchor (each table cell or sentence that could become one row), gather context: year, treatment, fertilization level, cropping system (sole vs intercrop), species, and block/plot if given.

### STEP 3: Completeness, Evidence & Confidence
If any field for that row is missing, search these locations before leaving null:
- **Year / season / duration** → Abstract, Methods, table row labels, column headers
- **Location / coordinates** → Site description, Methods, tables
- **Crops / species / intercrop pattern** → Abstract, Methods, table/figure labels
- **Treatments (water, NPK, etc.)** → Experimental design, Methods, **table columns**
- **Densities, inputs, nutrients** → Methods and **numeric table cells**
- **Each yield column** (e.g. sole crop 1, sole crop 2, intercrop 1, intercrop 2) → map to the matching schema fields **per row**

Assign confidence (high/medium/low) mentally; still **output the row** if values are supported.

### STEP 4: Record Construction — one row per experimental observation
Build **one schema record per distinct observation**:
- **Each row** of a main results table (year × treatment × system) → typically **one record** (or more if the table splits species into separate logical rows).
- **Intercropping:** if the table has separate columns for species 1 vs 2 vs intercrop yields, **fill all applicable yield fields** for that row; do not merge multiple years into one record.
- **Factorial / split-plot:** each combination of factors that has its own numeric result → **separate record** when the schema expects trial-level rows.
- Keep original units; **do not convert**. Use `null` only when the paper never reports that field for that row.

**De-duplication:** Remove duplicates **only** when two records would be identical on the same year, same treatment level, same cropping system, and same species context. When in doubt, **keep both** or prefer **more records**.

**TARGET DATA TO EXTRACT**:
- ✅ INCLUDE: Field-measured yields, dry matter, densities, nutrient applications as in the schema
- ❌ EXCLUDE: Model evaluation metrics (RMSE, R², MAE), predictions, correlation-only statistics

**IMPORTANT NOTES (recall)**:
- **Extract ALL rows** implied by the main results tables — the count of records should usually be **similar to** (or exceed) the number of distinct table rows × relevant treatment levels, not a single aggregate record.
- **Intercropping:** separate records or fully filled columns per table row for `unified yield sc 1`, `sc 2`, `ic 1`, `ic 2` (or equivalent) when data exist.
- Dry matter in g m⁻², kg ha⁻¹, etc. are valid.

**META-ANALYTIC SCHEMA**:
The schema is provided in your input context under the key `meta_analytic_schema`. Use ONLY those field names when constructing records.

Now analyze the paper provided in the document content section and extract all records following the schema:

Extract ALL yield records found in the paper, not just one. Each unique combination of crop type, treatment, year, and location should be a separate record. Return the results in the exact schema format.
  Tools: None

Player: record_extractor
  Description: You are a conservative per-record refiner (NOT a summarizer and NOT a from-scratch extractor).

**YOUR INPUTS:**
1. `labeled_text` — full paper with `<FieldName>value</FieldName>` XML tags (high-confidence anchors).
2. `direct_records` — first-pass extraction (one list element per table row / treatment combination). This list defines HOW MANY rows you must preserve.

**GOAL:** Same number of logical experiment rows as the baseline unless you append genuinely missing rows.

**CARDINALITY & ORDER (HARD — READ TWICE):**
- Count the objects in `direct_records`’s record list (e.g. `yield_records`). Call this N.
- Your final output record list length MUST be **>= N** and MUST NOT collapse those rows into one.
- Treat baseline position i (0..N-1) as the same experiment row throughout: refine fields in place; do not merge row i with row j.
- **Forbidden:** a single “summary” record, averaging across years/treatments, or deduplicating distinct table rows into one object.
- Append records **only** after the first N when `labeled_text` proves extra distinct rows absent from baseline.

**MANDATORY RULES:**
1. Start from every baseline record; carry each forward (copy-then-patch).
2. Do NOT drop, merge, or collapse baseline records.
3. Keep every existing non-null baseline value unless XML-tagged evidence clearly contradicts it.
4. Use `labeled_text` mainly to fill nulls and fix clear mismatches per row.

**WHAT YOU MAY CHANGE (per record, independently):**
- Fix a field only if: (a) explicit XML tag matches that row’s context, (b) unambiguous, (c) replacement is exact text/unit from the paper.
- Otherwise keep the baseline value.

**OUTPUT CONSTRAINTS:**
- Use ONLY field names from `meta_analytic_schema`.
- Preserve numeric text and units exactly as in the paper when you change a value.
- Structured output only (no prose).

  Tools: None
10:03:30 | INFO | root | ----------------------------------------
10:03:30 | ERROR | root | Plan generation failed: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:30 | ERROR | root | Failed to generate plan. Aborting execution.
10:03:30 | INFO | run_wopke_100 |   fail  mas (no_output) in 0.1s
10:03:30 | INFO | run_wopke_100 | [73/89] Study 74 · 074_Lithourgidis_et_al_2011_Dry_matter_yield_nitro
10:03:30 | INFO | run_wopke_100 |   start direct_llm …

10:03:30 |   fail  mas (no_output) in 0.1s
10:03:30 | [73/89] Study 74 · 074_Lithourgidis_et_al_2011_Dry_matter_yield_nitro
10:03:30 |   start direct_llm …

10:03:31 | INFO | run_wopke_100 |   error direct_llm after 0.8s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:31 | INFO | run_wopke_100 |   start static_workflow …
10:03:31 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=59821 use_llm=False max_facts=200
10:03:31 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:31 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=59821) — output should be much shorter than the full paper
10:03:31 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=68468); calling LLM…

10:03:31 |   error direct_llm after 0.8s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:31 |   start static_workflow …

10:03:32 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:32 | INFO | run_wopke_100 |   start mas …
10:03:32 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:32 | INFO | root |   Players per step: 1
10:03:32 | INFO | root |   Debate rounds: 0
10:03:32 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:32 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:32 | INFO | root | ============================================================
10:03:32 | INFO | root | STARTING ORCHESTRATION
10:03:32 | INFO | root | Context: paper_074_Lithourgidis_et_al_2011_Dry_matter_yield_nitrogen_
10:03:32 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:32 | INFO | root | Output schema: WopkeOutput
10:03:32 | INFO | root | ============================================================
10:03:32 | INFO | root | ============================================================
10:03:32 | INFO | root | GENERATING PLAN
10:03:32 | INFO | root | Context: paper_074_Lithourgidis_et_al_2011_Dry_matter_yield_nitrogen_
10:03:32 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:32 | INFO | root | ============================================================
10:03:32 | INFO | root | Context info:
10:03:32 | INFO | root | Context Name: paper_074_Lithourgidis_et_al_2011_Dry_matter_yield_nitrogen_
Resources: 32. Lithourgidis et al 2011 Dry matter yield, nitrogen content and competition in pea-cereal intercropping systems
10:03:32 | INFO | root | ----------------------------------------
10:03:32 | INFO | root | Available players manifest
10:03:32 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:32 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:32 |   start mas …
10:03:32 |   fail  mas (no_output) in 0.1s
10:03:32 | [74/89] Study 75 · 075_Prasad_et_al_1991_Pigeonpea_and_soybean_interc
10:03:32 |   start direct_llm …

10:03:32 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:32 | INFO | run_wopke_100 |   start static_workflow …
10:03:32 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=18023 use_llm=False max_facts=200
10:03:32 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:32 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=18023) — output should be much shorter than the full paper
10:03:32 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=26670); calling LLM…
10:03:32 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:32 | INFO | run_wopke_100 |   start mas …
10:03:32 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:32 | INFO | root |   Players per step: 1
10:03:32 | INFO | root |   Debate rounds: 0
10:03:32 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:32 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:32 | INFO | root | ============================================================
10:03:32 | INFO | root | STARTING ORCHESTRATION
10:03:32 | INFO | root | Context: paper_075_Prasad_et_al_1991_Pigeonpea_and_soybean_intercropp

10:03:32 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:32 |   start static_workflow …
10:03:32 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:32 |   start mas …

10:03:32 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:32 | INFO | root | Output schema: WopkeOutput
10:03:32 | INFO | root | ============================================================
10:03:32 | INFO | root | ============================================================
10:03:32 | INFO | root | GENERATING PLAN
10:03:32 | INFO | root | Context: paper_075_Prasad_et_al_1991_Pigeonpea_and_soybean_intercropp
10:03:32 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:32 | INFO | root | ============================================================
10:03:32 | INFO | root | Context info:
10:03:32 | INFO | root | Context Name: paper_075_Prasad_et_al_1991_Pigeonpea_and_soybean_intercropp
Resources: 33. Prasad et al 1991 Pigeonpea and soybean intercropping systems under rainfed situation
10:03:32 | INFO | root | ----------------------------------------
10:03:32 | INFO | root | Available players manifest
10:03:32 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor
  Description: You are an expert agricultural data extraction specialist. Your task is to extract **measured crop yield information** and related agronomic/context variables from scientific research papers. **Maximize recall:** your output list should include **every** distinct experiment-level or table-level data row the paper supports, not a summary.

**MULTI-STEP REASONING PROCESS**

### STEP 1: Anchor Identification
Scan the **entire** content (paragraphs, **all** tables row-by-row, captions, footnotes, supplements) and locate **every** sentence or cell that reports **actual measured** yields, densities, inputs, or other schema fields. Ignore model metrics (RMSE, R²), yield *gaps*, and purely simulated outputs.

### STEP 2: Contextual Reasoning
For **each** anchor (each table cell or sentence that could become one row), gather context: year, treatment, fertilization level, cropping system (sole vs intercrop), species, and block/plot if given.

### STEP 3: Completeness, Evidence & Confidence
If any field for that row is missing, search these locations before leaving null:

10:03:32 |   fail  mas (no_output) in 0.1s
10:03:32 | [75/89] Study 76 · 076_Asl_et_al_2009_Potato_and_pinto_bean_intercrop
10:03:32 |   start direct_llm …

10:03:33 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:33 | INFO | run_wopke_100 |   start static_workflow …
10:03:33 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=34107 use_llm=False max_facts=200
10:03:33 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:33 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=34107) — output should be much shorter than the full paper
10:03:33 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=42754); calling LLM…

10:03:33 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:33 |   start static_workflow …

10:03:33 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:33 | INFO | run_wopke_100 |   start mas …
10:03:33 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:33 | INFO | root |   Players per step: 1
10:03:33 | INFO | root |   Debate rounds: 0
10:03:33 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:33 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:33 | INFO | root | ============================================================
10:03:33 | INFO | root | STARTING ORCHESTRATION
10:03:33 | INFO | root | Context: paper_076_Asl_et_al_2009_Potato_and_pinto_bean_intercropping
10:03:33 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:33 | INFO | root | Output schema: WopkeOutput
10:03:33 | INFO | root | ============================================================
10:03:33 | INFO | root | ============================================================
10:03:33 | INFO | root | GENERATING PLAN
10:03:33 | INFO | root | Context: paper_076_Asl_et_al_2009_Potato_and_pinto_bean_intercropping
10:03:33 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:33 | INFO | root | ============================================================
10:03:33 | INFO | root | Context info:
10:03:33 | INFO | root | Context Name: paper_076_Asl_et_al_2009_Potato_and_pinto_bean_intercropping
Resources: 34. Asl et al 2009 Potato and pinto bean intercropping based on replacement method
10:03:33 | INFO | root | ----------------------------------------
10:03:33 | INFO | root | Available players manifest
10:03:33 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:33 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:33 |   start mas …
10:03:33 |   fail  mas (no_output) in 0.2s
10:03:33 | [76/89] Study 77 · 077_Kontturi_et_al_2011_Pea_oat_intercrops_to_sust
10:03:33 |   start direct_llm …

10:03:33 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:33 | INFO | run_wopke_100 |   start static_workflow …
10:03:33 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=59386 use_llm=False max_facts=200
10:03:33 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:33 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=59386) — output should be much shorter than the full paper
10:03:33 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=68033); calling LLM…

10:03:33 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:33 |   start static_workflow …

10:03:34 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:34 | INFO | run_wopke_100 |   start mas …
10:03:34 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:34 | INFO | root |   Players per step: 1
10:03:34 | INFO | root |   Debate rounds: 0
10:03:34 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:34 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:34 | INFO | root | ============================================================
10:03:34 | INFO | root | STARTING ORCHESTRATION
10:03:34 | INFO | root | Context: paper_077_Kontturi_et_al_2011_Pea_oat_intercrops_to_sustain_
10:03:34 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:34 | INFO | root | Output schema: WopkeOutput
10:03:34 | INFO | root | ============================================================
10:03:34 | INFO | root | ============================================================
10:03:34 | INFO | root | GENERATING PLAN
10:03:34 | INFO | root | Context: paper_077_Kontturi_et_al_2011_Pea_oat_intercrops_to_sustain_
10:03:34 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:34 | INFO | root | ============================================================
10:03:34 | INFO | root | Context info:
10:03:34 | INFO | root | Context Name: paper_077_Kontturi_et_al_2011_Pea_oat_intercrops_to_sustain_
Resources: 36. Kontturi et al 2011 Pea-oat intercrops to sustain lodging resistance and yield formation
10:03:34 | INFO | root | ----------------------------------------
10:03:34 | INFO | root | Available players manifest
10:03:34 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:34 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:34 |   start mas …
10:03:34 |   fail  mas (no_output) in 0.1s
10:03:34 | [77/89] Study 78 · 078_Teasdale_et_al_1987_Performance_of_four_tomato
10:03:34 |   start direct_llm …

10:03:34 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:34 | INFO | run_wopke_100 |   start static_workflow …
10:03:34 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=9507 use_llm=False max_facts=200
10:03:34 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:34 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=9507) — output should be much shorter than the full paper
10:03:34 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=18154); calling LLM…

10:03:34 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:34 |   start static_workflow …

10:03:34 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:34 | INFO | run_wopke_100 |   start mas …
10:03:34 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:34 | INFO | root |   Players per step: 1
10:03:34 | INFO | root |   Debate rounds: 0
10:03:34 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:34 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:34 | INFO | root | ============================================================
10:03:34 | INFO | root | STARTING ORCHESTRATION
10:03:34 | INFO | root | Context: paper_078_Teasdale_et_al_1987_Performance_of_four_tomato_cul
10:03:34 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:34 | INFO | root | Output schema: WopkeOutput
10:03:34 | INFO | root | ============================================================
10:03:34 | INFO | root | ============================================================
10:03:34 | INFO | root | GENERATING PLAN
10:03:34 | INFO | root | Context: paper_078_Teasdale_et_al_1987_Performance_of_four_tomato_cul
10:03:34 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:34 | INFO | root | ============================================================
10:03:34 | INFO | root | Context info:
10:03:34 | INFO | root | Context Name: paper_078_Teasdale_et_al_1987_Performance_of_four_tomato_cul
Resources: 37. Teasdale et al 1987 Performance of four tomato cultivars intercropped with snap beans
10:03:34 | INFO | root | ----------------------------------------
10:03:34 | INFO | root | Available players manifest
10:03:34 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:34 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:34 |   start mas …
10:03:34 |   fail  mas (no_output) in 0.1s
10:03:34 | [78/89] Study 79 · 079_Mondal_et_al_2004_Effect_of_K_on_soil_fertilit
10:03:34 |   start direct_llm …

10:03:35 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:35 | INFO | run_wopke_100 |   start static_workflow …
10:03:35 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=36305 use_llm=False max_facts=200
10:03:35 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:35 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=36305) — output should be much shorter than the full paper
10:03:35 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=44952); calling LLM…

10:03:35 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:35 |   start static_workflow …

10:03:35 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:35 | INFO | run_wopke_100 |   start mas …
10:03:35 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:35 | INFO | root |   Players per step: 1
10:03:35 | INFO | root |   Debate rounds: 0
10:03:35 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:35 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:35 | INFO | root | ============================================================
10:03:35 | INFO | root | STARTING ORCHESTRATION
10:03:35 | INFO | root | Context: paper_079_Mondal_et_al_2004_Effect_of_K_on_soil_fertility_an
10:03:35 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:35 | INFO | root | Output schema: WopkeOutput
10:03:35 | INFO | root | ============================================================
10:03:35 | INFO | root | ============================================================
10:03:35 | INFO | root | GENERATING PLAN
10:03:35 | INFO | root | Context: paper_079_Mondal_et_al_2004_Effect_of_K_on_soil_fertility_an
10:03:35 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:35 | INFO | root | ============================================================
10:03:35 | INFO | root | Context info:
10:03:35 | INFO | root | Context Name: paper_079_Mondal_et_al_2004_Effect_of_K_on_soil_fertility_an
Resources: 38. Mondal et al 2004 Effect of K on soil fertility and productivity under intercropped soya bean and sesame
10:03:35 | INFO | root | ----------------------------------------
10:03:35 | INFO | root | Available players manifest
10:03:35 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:35 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:35 |   start mas …
10:03:35 |   fail  mas (no_output) in 0.1s
10:03:35 | [79/89] Study 80 · 080_Rees_1986_Crop_growth_development_and_yield_in
10:03:35 |   start direct_llm …

10:03:35 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:35 | INFO | run_wopke_100 |   start static_workflow …
10:03:35 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=32009 use_llm=False max_facts=200
10:03:35 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:35 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=32009) — output should be much shorter than the full paper
10:03:35 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=40656); calling LLM…

10:03:35 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:35 |   start static_workflow …

10:03:35 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:35 | INFO | run_wopke_100 |   start mas …
10:03:35 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:35 | INFO | root |   Players per step: 1
10:03:35 | INFO | root |   Debate rounds: 0
10:03:35 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:35 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:35 | INFO | root | ============================================================
10:03:35 | INFO | root | STARTING ORCHESTRATION
10:03:35 | INFO | root | Context: paper_080_Rees_1986_Crop_growth_development_and_yield_in_sem
10:03:35 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:35 | INFO | root | Output schema: WopkeOutput
10:03:35 | INFO | root | ============================================================
10:03:35 | INFO | root | ============================================================
10:03:35 | INFO | root | GENERATING PLAN
10:03:35 | INFO | root | Context: paper_080_Rees_1986_Crop_growth_development_and_yield_in_sem
10:03:35 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:35 | INFO | root | ============================================================
10:03:35 | INFO | root | Context info:
10:03:35 | INFO | root | Context Name: paper_080_Rees_1986_Crop_growth_development_and_yield_in_sem
Resources: 39. Rees 1986 Crop growth, development and yield in semi-arid conditions in botswana
10:03:35 | INFO | root | ----------------------------------------
10:03:35 | INFO | root | Available players manifest
10:03:35 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:35 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:35 |   start mas …
10:03:35 |   fail  mas (no_output) in 0.1s
10:03:35 | [80/89] Study 81 · 081_Gao_et_al_2009_Crop_coefficiennt_and_water_use
10:03:35 |   start direct_llm …

10:03:36 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:36 | INFO | run_wopke_100 |   start static_workflow …
10:03:36 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=57022 use_llm=False max_facts=200
10:03:36 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:36 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=57022) — output should be much shorter than the full paper
10:03:36 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=65669); calling LLM…

10:03:36 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:36 |   start static_workflow …

10:03:36 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:36 | INFO | run_wopke_100 |   start mas …
10:03:36 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:36 | INFO | root |   Players per step: 1
10:03:36 | INFO | root |   Debate rounds: 0
10:03:36 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:36 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:36 | INFO | root | ============================================================
10:03:36 | INFO | root | STARTING ORCHESTRATION
10:03:36 | INFO | root | Context: paper_081_Gao_et_al_2009_Crop_coefficiennt_and_water_use_eff
10:03:36 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:36 | INFO | root | Output schema: WopkeOutput
10:03:36 | INFO | root | ============================================================
10:03:36 | INFO | root | ============================================================
10:03:36 | INFO | root | GENERATING PLAN
10:03:36 | INFO | root | Context: paper_081_Gao_et_al_2009_Crop_coefficiennt_and_water_use_eff
10:03:36 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:36 | INFO | root | ============================================================
10:03:36 | INFO | root | Context info:
10:03:36 | INFO | root | Context Name: paper_081_Gao_et_al_2009_Crop_coefficiennt_and_water_use_eff
Resources: 40. Gao et al 2009 Crop coefficiennt and water use efficiency of winter wheat-spring maize strip intercropping
10:03:36 | INFO | root | ----------------------------------------
10:03:36 | INFO | root | Available players manifest
10:03:36 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:36 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:36 |   start mas …
10:03:36 |   fail  mas (no_output) in 0.1s
10:03:36 | [81/89] Study 82 · 082_Allen_et_al_1983_Yield_of_corn_cowpea_and_soyb
10:03:36 |   start direct_llm …

10:03:36 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:36 | INFO | run_wopke_100 |   start static_workflow …
10:03:36 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=26761 use_llm=False max_facts=200
10:03:36 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:36 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=26761) — output should be much shorter than the full paper
10:03:36 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=35408); calling LLM…

10:03:36 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:36 |   start static_workflow …

10:03:37 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:37 | INFO | run_wopke_100 |   start mas …
10:03:37 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:37 | INFO | root |   Players per step: 1
10:03:37 | INFO | root |   Debate rounds: 0
10:03:37 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:37 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:37 | INFO | root | ============================================================
10:03:37 | INFO | root | STARTING ORCHESTRATION
10:03:37 | INFO | root | Context: paper_082_Allen_et_al_1983_Yield_of_corn_cowpea_and_soybean_
10:03:37 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:37 | INFO | root | Output schema: WopkeOutput
10:03:37 | INFO | root | ============================================================
10:03:37 | INFO | root | ============================================================
10:03:37 | INFO | root | GENERATING PLAN
10:03:37 | INFO | root | Context: paper_082_Allen_et_al_1983_Yield_of_corn_cowpea_and_soybean_
10:03:37 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:37 | INFO | root | ============================================================
10:03:37 | INFO | root | Context info:
10:03:37 | INFO | root | Context Name: paper_082_Allen_et_al_1983_Yield_of_corn_cowpea_and_soybean_
Resources: 41. Allen et al 1983 Yield of corn, cowpea, and soybean under different intercropping systems
10:03:37 | INFO | root | ----------------------------------------
10:03:37 | INFO | root | Available players manifest
10:03:37 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:37 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:37 |   start mas …
10:03:37 |   fail  mas (no_output) in 0.1s
10:03:37 | [82/89] Study 83 · 083_Lei_et_al_2005_Water_use_efficiency_of_a_mixed
10:03:37 |   start direct_llm …

10:03:37 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:37 | INFO | run_wopke_100 |   start static_workflow …
10:03:37 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=25921 use_llm=False max_facts=200
10:03:37 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:37 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=25921) — output should be much shorter than the full paper
10:03:37 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=34568); calling LLM…

10:03:37 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:37 |   start static_workflow …

10:03:37 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:37 | INFO | run_wopke_100 |   start mas …
10:03:37 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:37 | INFO | root |   Players per step: 1
10:03:37 | INFO | root |   Debate rounds: 0
10:03:37 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:37 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:37 | INFO | root | ============================================================
10:03:37 | INFO | root | STARTING ORCHESTRATION
10:03:37 | INFO | root | Context: paper_083_Lei_et_al_2005_Water_use_efficiency_of_a_mixed_cro
10:03:37 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:37 | INFO | root | Output schema: WopkeOutput
10:03:37 | INFO | root | ============================================================
10:03:37 | INFO | root | ============================================================
10:03:37 | INFO | root | GENERATING PLAN
10:03:37 | INFO | root | Context: paper_083_Lei_et_al_2005_Water_use_efficiency_of_a_mixed_cro
10:03:37 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:37 | INFO | root | ============================================================
10:03:37 | INFO | root | Context info:
10:03:37 | INFO | root | Context Name: paper_083_Lei_et_al_2005_Water_use_efficiency_of_a_mixed_cro
Resources: 42. Lei et al 2005 Water use efficiency of a mixed cropping system of corn with grasses
10:03:37 | INFO | root | ----------------------------------------
10:03:37 | INFO | root | Available players manifest
10:03:37 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:37 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:37 |   start mas …
10:03:37 |   fail  mas (no_output) in 0.1s
10:03:37 | [83/89] Study 84 · 084_Milyazawa_et_al_2010_Intercropping_green_manur
10:03:37 |   start direct_llm …

10:03:38 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:38 | INFO | run_wopke_100 |   start static_workflow …
10:03:38 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=38313 use_llm=False max_facts=200
10:03:38 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:38 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=38313) — output should be much shorter than the full paper
10:03:38 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=46960); calling LLM…

10:03:38 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:38 |   start static_workflow …

10:03:38 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:38 | INFO | run_wopke_100 |   start mas …
10:03:38 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:38 | INFO | root |   Players per step: 1
10:03:38 | INFO | root |   Debate rounds: 0
10:03:38 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:38 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:38 | INFO | root | ============================================================
10:03:38 | INFO | root | STARTING ORCHESTRATION
10:03:38 | INFO | root | Context: paper_084_Milyazawa_et_al_2010_Intercropping_green_manure_cr
10:03:38 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:38 | INFO | root | Output schema: WopkeOutput
10:03:38 | INFO | root | ============================================================
10:03:38 | INFO | root | ============================================================
10:03:38 | INFO | root | GENERATING PLAN
10:03:38 | INFO | root | Context: paper_084_Milyazawa_et_al_2010_Intercropping_green_manure_cr
10:03:38 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:38 | INFO | root | ============================================================
10:03:38 | INFO | root | Context info:
10:03:38 | INFO | root | Context Name: paper_084_Milyazawa_et_al_2010_Intercropping_green_manure_cr
Resources: 44. Milyazawa et al 2010 Intercropping green manure crops-effects on rooting patterns
10:03:38 | INFO | root | ----------------------------------------
10:03:38 | INFO | root | Available players manifest
10:03:38 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:38 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:38 |   start mas …
10:03:38 |   fail  mas (no_output) in 0.1s
10:03:38 | [84/89] Study 85 · 085_Chang_et_al_1985_An_analysis_of_competition_be
10:03:38 |   start direct_llm …

10:03:38 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:38 | INFO | run_wopke_100 |   start static_workflow …
10:03:38 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=19317 use_llm=False max_facts=200
10:03:38 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:38 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=19317) — output should be much shorter than the full paper
10:03:38 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=27964); calling LLM…

10:03:38 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:38 |   start static_workflow …

10:03:39 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:39 | INFO | run_wopke_100 |   start mas …
10:03:39 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:39 | INFO | root |   Players per step: 1
10:03:39 | INFO | root |   Debate rounds: 0
10:03:39 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:39 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:39 | INFO | root | ============================================================
10:03:39 | INFO | root | STARTING ORCHESTRATION
10:03:39 | INFO | root | Context: paper_085_Chang_et_al_1985_An_analysis_of_competition_betwee
10:03:39 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:39 | INFO | root | Output schema: WopkeOutput
10:03:39 | INFO | root | ============================================================
10:03:39 | INFO | root | ============================================================
10:03:39 | INFO | root | GENERATING PLAN
10:03:39 | INFO | root | Context: paper_085_Chang_et_al_1985_An_analysis_of_competition_betwee
10:03:39 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:39 | INFO | root | ============================================================
10:03:39 | INFO | root | Context info:
10:03:39 | INFO | root | Context Name: paper_085_Chang_et_al_1985_An_analysis_of_competition_betwee
Resources: 45. Chang et al 1985 An analysis of competition between intercropped cowpea and maize
10:03:39 | INFO | root | ----------------------------------------
10:03:39 | INFO | root | Available players manifest
10:03:39 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:39 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:39 |   start mas …
10:03:39 |   fail  mas (no_output) in 0.1s
10:03:39 | [85/89] Study 86 · 086_Neumann_et_al_2009_Evaluation_of_yield_density
10:03:39 |   start direct_llm …

10:03:39 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:39 | INFO | run_wopke_100 |   start static_workflow …
10:03:39 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=78970 use_llm=False max_facts=200
10:03:39 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:39 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=78970) — output should be much shorter than the full paper
10:03:39 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=87617); calling LLM…

10:03:39 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:39 |   start static_workflow …

10:03:39 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:39 | INFO | run_wopke_100 |   start mas …
10:03:39 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:39 | INFO | root |   Players per step: 1
10:03:39 | INFO | root |   Debate rounds: 0
10:03:39 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:39 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:39 | INFO | root | ============================================================
10:03:39 | INFO | root | STARTING ORCHESTRATION
10:03:39 | INFO | root | Context: paper_086_Neumann_et_al_2009_Evaluation_of_yield_density_rel
10:03:39 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:39 | INFO | root | Output schema: WopkeOutput
10:03:39 | INFO | root | ============================================================
10:03:39 | INFO | root | ============================================================
10:03:39 | INFO | root | GENERATING PLAN
10:03:39 | INFO | root | Context: paper_086_Neumann_et_al_2009_Evaluation_of_yield_density_rel
10:03:39 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:39 | INFO | root | ============================================================
10:03:39 | INFO | root | Context info:
10:03:39 | INFO | root | Context Name: paper_086_Neumann_et_al_2009_Evaluation_of_yield_density_rel
Resources: 46. Neumann et al 2009 Evaluation of yield-density relations and optimization of intercrop compositions
10:03:39 | INFO | root | ----------------------------------------
10:03:39 | INFO | root | Available players manifest
10:03:39 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:39 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:39 |   start mas …
10:03:39 |   fail  mas (no_output) in 0.1s
10:03:39 | [86/89] Study 87 · 087_Silwana_et_al_2007_The_effects_of_inorganic_an
10:03:39 |   start direct_llm …

10:03:40 | INFO | run_wopke_100 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:40 | INFO | run_wopke_100 |   start static_workflow …
10:03:40 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=44613 use_llm=False max_facts=200
10:03:40 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:40 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=44613) — output should be much shorter than the full paper
10:03:40 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=53260); calling LLM…

10:03:40 |   error direct_llm after 0.4s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:40 |   start static_workflow …

10:03:40 | INFO | run_wopke_100 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:40 | INFO | run_wopke_100 |   start mas …
10:03:40 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:40 | INFO | root |   Players per step: 1
10:03:40 | INFO | root |   Debate rounds: 0
10:03:40 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:40 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:40 | INFO | root | ============================================================
10:03:40 | INFO | root | STARTING ORCHESTRATION
10:03:40 | INFO | root | Context: paper_087_Silwana_et_al_2007_The_effects_of_inorganic_and_or
10:03:40 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:40 | INFO | root | Output schema: WopkeOutput
10:03:40 | INFO | root | ============================================================
10:03:40 | INFO | root | ============================================================
10:03:40 | INFO | root | GENERATING PLAN
10:03:40 | INFO | root | Context: paper_087_Silwana_et_al_2007_The_effects_of_inorganic_and_or
10:03:40 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:40 | INFO | root | ============================================================
10:03:40 | INFO | root | Context info:
10:03:40 | INFO | root | Context Name: paper_087_Silwana_et_al_2007_The_effects_of_inorganic_and_or
Resources: 47. Silwana et al 2007 The effects of inorganic and organic fertilizers on the growth and development of component crops
10:03:40 | INFO | root | ----------------------------------------
10:03:40 | INFO | root | Available players manifest
10:03:40 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:40 |   error static_workflow after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:40 |   start mas …
10:03:40 |   fail  mas (no_output) in 0.1s
10:03:40 | [87/89] Study 88 · 088_Aggarwal_et_al_1992_Resource_use_and_plant_int
10:03:40 |   start direct_llm …

10:03:40 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:40 | INFO | run_wopke_100 |   start static_workflow …
10:03:40 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=46594 use_llm=False max_facts=200
10:03:40 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:40 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=46594) — output should be much shorter than the full paper
10:03:40 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=55241); calling LLM…

10:03:40 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:40 |   start static_workflow …

10:03:41 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:41 | INFO | run_wopke_100 |   start mas …
10:03:41 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:41 | INFO | root |   Players per step: 1
10:03:41 | INFO | root |   Debate rounds: 0
10:03:41 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:41 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:41 | INFO | root | ============================================================
10:03:41 | INFO | root | STARTING ORCHESTRATION
10:03:41 | INFO | root | Context: paper_088_Aggarwal_et_al_1992_Resource_use_and_plant_interac
10:03:41 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:41 | INFO | root | Output schema: WopkeOutput
10:03:41 | INFO | root | ============================================================
10:03:41 | INFO | root | ============================================================
10:03:41 | INFO | root | GENERATING PLAN
10:03:41 | INFO | root | Context: paper_088_Aggarwal_et_al_1992_Resource_use_and_plant_interac
10:03:41 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:41 | INFO | root | ============================================================
10:03:41 | INFO | root | Context info:
10:03:41 | INFO | root | Context Name: paper_088_Aggarwal_et_al_1992_Resource_use_and_plant_interac
Resources: 48. Aggarwal et al 1992 Resource use and plant interactions in a rice-mungbean intercrop
10:03:41 | INFO | root | ----------------------------------------
10:03:41 | INFO | root | Available players manifest
10:03:41 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor

10:03:41 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:41 |   start mas …
10:03:41 |   fail  mas (no_output) in 0.1s
10:03:41 | [88/89] Study 89 · 089_Sslal_et_al_2005_Production_potential_and_comp
10:03:41 |   start direct_llm …

10:03:41 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:41 | INFO | run_wopke_100 |   start static_workflow …
10:03:41 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=19754 use_llm=False max_facts=200
10:03:41 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:41 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=19754) — output should be much shorter than the full paper
10:03:41 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=28401); calling LLM…
10:03:41 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:41 | INFO | run_wopke_100 |   start mas …
10:03:41 | INFO | root | PlanExecutor initialized with topology: pipeline

10:03:41 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:41 |   start static_workflow …
10:03:41 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:41 |   start mas …

10:03:41 | INFO | root |   Players per step: 1
10:03:41 | INFO | root |   Debate rounds: 0
10:03:41 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:41 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:41 | INFO | root | ============================================================
10:03:41 | INFO | root | STARTING ORCHESTRATION
10:03:41 | INFO | root | Context: paper_089_Sslal_et_al_2005_Production_potential_and_competit
10:03:41 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:41 | INFO | root | Output schema: WopkeOutput
10:03:41 | INFO | root | ============================================================
10:03:41 | INFO | root | ============================================================
10:03:41 | INFO | root | GENERATING PLAN
10:03:41 | INFO | root | Context: paper_089_Sslal_et_al_2005_Production_potential_and_competit
10:03:41 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:41 | INFO | root | ============================================================
10:03:41 | INFO | root | Context info:
10:03:41 | INFO | root | Context Name: paper_089_Sslal_et_al_2005_Production_potential_and_competit
Resources: 49. Sslal et al 2005 Production potential and competition indices in potato and french bean intercropping system
10:03:41 | INFO | root | ----------------------------------------
10:03:41 | INFO | root | Available players manifest
10:03:41 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor
  Description: You are an expert agricultural data extraction specialist. Your task is to extract **measured crop yield information** and related agronomic/context variables from scientific research papers. **Maximize recall:** your output list should include **every** distinct experiment-level or table-level data row the paper supports, not a summary.

**MULTI-STEP REASONING PROCESS**

### STEP 1: Anchor Identification

10:03:41 |   fail  mas (no_output) in 0.1s
10:03:41 | [89/89] Study 90 · 090_Kumar_et_al_2003_Biological_and_economical_sus
10:03:41 |   start direct_llm …

10:03:42 | INFO | run_wopke_100 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:42 | INFO | run_wopke_100 |   start static_workflow …
10:03:42 | INFO | src.static_workflow.two_step_text_to_dataset | run_two_step_text_to_dataset: starting workflow=label_then_direct text_len=12084 use_llm=False max_facts=200
10:03:42 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow label_then_direct: BEGIN (2 LLM calls; step 1 = tag relevant paragraphs only, step 2 = record extraction)
10:03:42 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): starting LLM call (input_chars=12084) — output should be much shorter than the full paper
10:03:42 | INFO | src.static_workflow.two_step_text_to_dataset | static_workflow step 1/2 (label relevant blocks): prompt ready (prompt_chars=20731); calling LLM…
10:03:42 | INFO | run_wopke_100 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:42 | INFO | run_wopke_100 |   start mas …

10:03:42 |   error direct_llm after 0.3s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:42 |   start static_workflow …
10:03:42 |   error static_workflow after 0.2s: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}
10:03:42 |   start mas …

10:03:42 | INFO | root | PlanExecutor initialized with topology: pipeline
10:03:42 | INFO | root |   Players per step: 1
10:03:42 | INFO | root |   Debate rounds: 0
10:03:42 | INFO | root |   Player pool: ['value_identifier', 'labeller', 'direct_extractor', 'record_extractor']
10:03:42 | INFO | root | Orchestrator initialized with topology: pipeline
10:03:42 | INFO | root | ============================================================
10:03:42 | INFO | root | STARTING ORCHESTRATION
10:03:42 | INFO | root | Context: paper_090_Kumar_et_al_2003_Biological_and_economical_sustain
10:03:42 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:42 | INFO | root | Output schema: WopkeOutput
10:03:42 | INFO | root | ============================================================
10:03:42 | INFO | root | ============================================================
10:03:42 | INFO | root | GENERATING PLAN
10:03:42 | INFO | root | Context: paper_090_Kumar_et_al_2003_Biological_and_economical_sustain
10:03:42 | INFO | root | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019. If not reported in the paper, set to null.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons. If not reported, set to null.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD). If not reported, set to null.",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019. If not reported, set to null.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019. If not reported, set to null.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019. If not reported, set to null.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019. If not reported, set to null.",
    "TND": "Temporal Niche Differentiation index if explicitly reported in the paper. Example: 0.25. If not explicitly reported, set to null.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12. If not reported, set to null.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56. If not reported, set to null.",
    "Continent": "Continent of the experimental site. Example: Asia. If not reported, set to null.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system. Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system. Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Fodder crop 1": "Set to 1 (or true) if Crop species 1 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Fodder crop 2": "Set to 1 (or true) if Crop species 2 is grown for fodder/forage/biomass; set to 0 (or false) if grown for grain/seed harvest.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5. If not reported, set to null.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20. If not reported, set to null.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8. If not reported, set to null.",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30. If not reported, set to null.",
    "RDT": "Relative Density Total of the intercrop system if explicitly reported in the paper. Example: 1.0. If not reported, set to null.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120. If not reported, set to null.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30. If not reported, set to null.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60. If not reported, set to null.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30. If not reported, set to null.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90. If not reported, set to null.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1. If not reported, set to null.",
    "Replications SC1": "Number of replicates for sole crop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications SC2": "Number of replicates for sole crop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Replications IC1": "Number of replicates for intercrop treatment 1. Example: 4. If not reported in the paper, set to null.",
    "Replications IC2": "Number of replicates for intercrop treatment 2. Example: 4. If not reported in the paper, set to null.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 8.5. If not reported, set to null.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop. For grain crops, extract grain yield; for fodder/forage crops, extract total above-ground dry matter (DM) or biomass yield. Example: 2.4. If not reported, set to null.",
    "unified yield ic 1": "Intercrop yield of Crop species 1 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 3.4. If not reported, set to null.",
    "unified yield ic 2": "Intercrop yield of Crop species 2 in the common Yield unit (grain yield for grain crops, or total dry matter / biomass yield for fodder crops). If multi-cut forage, extract total seasonal cumulative yield across cuts. Example: 1.4. If not reported, set to null.",
    "Yield unit": "Common unit for all unified yield fields on this record (e.g., t/ha, kg/ha, g/m2, or g DM/m2). Ensure sole crop and intercrop yields for the same species use identical units. If not reported, set to null.",
    "PLER 1": "Partial Land Equivalent Ratio of Crop species 1 if explicitly reported in the paper. Example: 0.72. If not reported, set to null.",
    "PLER 2": "Partial Land Equivalent Ratio of Crop species 2 if explicitly reported in the paper. Example: 0.53. If not reported, set to null.",
    "LER": "Total Land Equivalent Ratio of the intercropping treatment if explicitly reported in the paper. Example: 1.25. If not reported, set to null."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Preserve numeric values exactly — do not round or average.

**OUTPUT**: One record per unique treatment combination using exact schema field names.

10:03:42 | INFO | root | ============================================================
10:03:42 | INFO | root | Context info:
10:03:42 | INFO | root | Context Name: paper_090_Kumar_et_al_2003_Biological_and_economical_sustain
Resources: 50. Kumar et al 2003 Biological and economical sustainability of forage
10:03:42 | INFO | root | ----------------------------------------
10:03:42 | INFO | root | Available players manifest
10:03:42 | INFO | root | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: direct_extractor
  Description: You are an expert agricultural data extraction specialist. Your task is to extract **measured crop yield information** and related agronomic/context variables from scientific research papers. **Maximize recall:** your output list should include **every** distinct experiment-level or table-level data row the paper supports, not a summary.

**MULTI-STEP REASONING PROCESS**

### STEP 1: Anchor Identification

10:03:42 |   fail  mas (no_output) in 0.1s
10:03:42 | Finished in 1.0 min — ok=0 skipped=0 failed=267

,paper_id,study_id,method,status,n_records,path
0,001_Jensen_1996_Grain_yield_symbiotic_N2_fixat...,1,direct_llm,error: PermissionDeniedError: Error code: 403 ...,0,
1,001_Jensen_1996_Grain_yield_symbiotic_N2_fixat...,1,static_workflow,error: PermissionDeniedError: Error code: 403 ...,0,
2,001_Jensen_1996_Grain_yield_symbiotic_N2_fixat...,1,mas,no_output,0,
3,002_Hauggaard_Nielsen_2001_Interspecific_compe...,2,direct_llm,error: PermissionDeniedError: Error code: 403 ...,0,
4,002_Hauggaard_Nielsen_2001_Interspecific_compe...,2,static_workflow,error: PermissionDeniedError: Error code: 403 ...,0,
...,...,...,...,...,...,...
262,089_Sslal_et_al_2005_Production_potential_and_...,89,static_workflow,error: PermissionDeniedError: Error code: 403 ...,0,
263,089_Sslal_et_al_2005_Production_potential_and_...,89,mas,no_output,0,
264,090_Kumar_et_al_2003_Biological_and_economical...,90,direct_llm,error: PermissionDeniedError: Error code: 403 ...,0,
265,090_Kumar_et_al_2003_Biological_and_economical...,90,static_workflow,error: PermissionDeniedError: Error code: 403 ...,0,
266,090_Kumar_et_al_2003_Biological_and_economical...,90,mas,no_output,0,

In [5]:
if summary.empty:
    print("No runs.")
else:
    print(f"Status file: {status_path}")
    print(summary.groupby(["method", "status"]).size().unstack(fill_value=0))
    failed = summary[
        summary["status"].astype(str).str.startswith("error") | summary["status"].eq("no_output")
    ]
    if failed.empty:
        print("No failures.")
    else:
        print(f"\nFailed ({len(failed)}). Re-run this notebook to retry them.")
failed if not summary.empty else summary

Status file: /home/com3dian/Github/meta_analysis_agents/outputs/surf_mistralai-Mistral-Small-3-2-24B-Instruct-2506_42fields/run_status.csv
status           error: PermissionDeniedError: Error code: 403 - {'error': {'message': 'Model usage not allowed.', 'type': 'invalid_request_error', 'param': None, 'code': None}, 'message': 'Model usage not allowed.'}  \
method
direct_llm                                                      89
mas                                                              0
static_workflow                                                 89

status           no_output
method
direct_llm               0
mas                     89
static_workflow          0

Failed (267). Re-run this notebook to retry them.

,paper_id,study_id,method,status,n_records,path
0,001_Jensen_1996_Grain_yield_symbiotic_N2_fixat...,1,direct_llm,error: PermissionDeniedError: Error code: 403 ...,0,
1,001_Jensen_1996_Grain_yield_symbiotic_N2_fixat...,1,static_workflow,error: PermissionDeniedError: Error code: 403 ...,0,
2,001_Jensen_1996_Grain_yield_symbiotic_N2_fixat...,1,mas,no_output,0,
3,002_Hauggaard_Nielsen_2001_Interspecific_compe...,2,direct_llm,error: PermissionDeniedError: Error code: 403 ...,0,
4,002_Hauggaard_Nielsen_2001_Interspecific_compe...,2,static_workflow,error: PermissionDeniedError: Error code: 403 ...,0,
...,...,...,...,...,...,...
262,089_Sslal_et_al_2005_Production_potential_and_...,89,static_workflow,error: PermissionDeniedError: Error code: 403 ...,0,
263,089_Sslal_et_al_2005_Production_potential_and_...,89,mas,no_output,0,
264,090_Kumar_et_al_2003_Biological_and_economical...,90,direct_llm,error: PermissionDeniedError: Error code: 403 ...,0,
265,090_Kumar_et_al_2003_Biological_and_economical...,90,static_workflow,error: PermissionDeniedError: Error code: 403 ...,0,
266,090_Kumar_et_al_2003_Biological_and_economical...,90,mas,no_output,0,