# MAS Pipeline Debugger

Runs the 5-step label-first MAS pipeline and prints every intermediate artifact so you can
pinpoint where things go wrong:

1. **Plan** — what steps the orchestrator generated (player, task, inputs, outputs)
2. **Step-by-step** — for each step: player used, analysis output, tool results, artifacts saved
3. **Workspace** — full workspace after all steps
4. **Final output** — structured records as a DataFrame

In [1]:
import os
import re
import sys
import json
import logging
sys.path.insert(0, '..')

import pandas as pd
from IPython.display import display, Markdown

from src.config import LLM_PROVIDER, get_model_name
from src.context import create_context
from src.standards import METADATA_STANDARDS
from src.core.schema_factory import SchemaFactory
from src.orchestrator.orchestrator import Orchestrator
from src.experimentutils import (
    read_paper_text,
    load_ground_truth,
    build_study_paper_mapping,
    highlight_numbers_and_tables,
)

# Show INFO logs from the MAS so we can follow execution
logging.basicConfig(level=logging.INFO, format='%(levelname)s | %(message)s')

print(f'Provider : {LLM_PROVIDER}')
print(f'Model    : {get_model_name()}')

Provider : google
Model    : gemini-3.1-flash-lite-preview

In [2]:
# ── Paper & schema selection ──────────────────────────────────────────────────
study_id = 5   # <- change to test a different paper

gt_df   = load_ground_truth()
mapping = build_study_paper_mapping(gt_df)

if study_id not in mapping:
    raise ValueError(f'study_id={study_id} not in mapping. Available: {sorted(mapping.keys())}')

paper_path = mapping[study_id]
print(f'Study# {study_id} → {paper_path.split("/")[-1]}')

standard = METADATA_STANDARDS['wopke_100']
n_fields = len(SchemaFactory()._parse_schema_string(standard))
print(f'Schema   : wopke_100 ({n_fields} fields)')

gt_paper = gt_df[gt_df['Study#'] == study_id].reset_index(drop=True)
print(f'GT rows  : {len(gt_paper)}')

Study# 5 → Li 1999 Interspecific complementary and competitive interactions between intercropped maize and faba bean.md
Schema   : wopke_100 (42 fields)
GT rows  : 3

In [3]:
# ── Output schema & execution context ────────────────────────────────────────
OutputSchema = SchemaFactory().create_from_standard(
    standard,
    record_class_name='WopkeRecord',
    output_class_name='WopkeOutput',
    records_key='yield_records',
)
print(f'OutputSchema : {OutputSchema.__name__}')

context = create_context(source=paper_path, name=f'study_{study_id}')
raw_text = read_paper_text(paper_path)
print(f'Document     : {len(raw_text):,} chars')

OutputSchema : WopkeOutput
Document     : 39,523 chars

In [4]:
# ── MAS objective (same as evaluate_3.ipynb) ──────────────────────────────────
mas_objective = f'''You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:
{standard}

**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Examples:
- 2 density levels × 2 N-treatments = 4 records for the same crop pair.
- Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Use explicit table headers, row labels, and footnotes to assign yields to the correct species.
If species assignment is ambiguous, set the ambiguous field to null and note the source in `Data source`.
Preserve numeric values exactly — do not round or average.

**SHARED FIELDS**
Fields that are constant across treatments (Year, Lat, Lon, Experimental design, species names,
Intercropping pattern, uniform nutrient inputs) must be filled identically in every record.
Set to null only if genuinely absent from the paper.

**OUTPUT**: One record per unique treatment combination using exact schema field names.
Omit records only if the paper genuinely contains no supporting data.'''

print('Objective built.')

Objective built.

In [5]:
# ── Instantiate orchestrator with the new pipeline topology ───────────────────
orchestrator = Orchestrator(topology_name='pipeline')
print('Orchestrator ready (topology=pipeline, players_per_step=1, debate_rounds=0)')

INFO | PlanExecutor initialized with topology: pipeline
INFO |   Players per step: 1
INFO |   Debate rounds: 0
INFO |   Player pool: ['value_identifier', 'labeller', 'record_grouper', 'record_labeller', 'record_extractor']
INFO | Orchestrator initialized with topology: pipeline

Orchestrator ready (topology=pipeline, players_per_step=1, debate_rounds=0)

In [6]:
# ── Step 1: Generate the plan only (no execution yet) ─────────────────────────
plan = orchestrator.generate_plan(context=context, objective=mas_objective)

if plan is None:
    print('[ERROR] Plan generation failed!')
else:
    display(Markdown('## Generated Plan'))
    for i, step in enumerate(plan.steps):
        display(Markdown(
            f'**Step {i+1}** | player: `{step.player}`  \n'
            f'Task: {step.task}  \n'
            f'Inputs: `{step.inputs}`  \n'
            f'Outputs: `{step.outputs}`'
        ))

INFO | ============================================================
INFO | GENERATING PLAN
INFO | Context: study_5
INFO | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD).",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system (the first species mentioned in the pair). Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system (the second species mentioned in the pair). Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8。",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1.",
    "P input SC1": "Phosphorus fertilizer applied to the sole crop treatment of Crop species 1. Example: 40.",
    "P input SC2": "Phosphorus fertilizer applied to the sole crop treatment of Crop species 2. Example: 30.",
    "P input IC1": "Phosphorus fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 20.",
    "P input IC2": "Phosphorus fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 20.",
    "P total in IC": "Total phosphorus fertilizer applied in the intercropping treatment. Example: 40.",
    "P Unit": "Unit used for phosphorus fertilizer amounts. Example: kg P2O5 ha−1.",
    "K input SC1": "Potassium fertilizer applied to the sole crop treatment of Crop species 1. Example: 60.",
    "K input SC2": "Potassium fertilizer applied to the sole crop treatment of Crop species 2. Example: 50.",
    "K input IC1": "Potassium fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 30.",
    "K input IC2": "Potassium fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30.",
    "K total in IC": "Total potassium fertilizer applied in the intercropping treatment. Example: 60.",
    "K Unit": "Unit used for potassium fertilizer amounts. Example: kg K2O ha−1.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop, converted to a common yield unit. Example: 8.5.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop, converted to a common yield unit. Example: 2.4.",
    "unified yield ic 1": "Yield of Crop species 1 when grown in the intercropping treatment. Example: 6.1.",
    "unified yield ic 2": "Yield of Crop species 2 when grown in the intercropping treatment. Example: 1.8.",
    "Yield unit": "Unit used for all standardized yields. Example: t ha−1."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Examples:
- 2 density levels × 2 N-treatments = 4 records for the same crop pair.
- Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Use explicit table headers, row labels, and footnotes to assign yields to the correct species.
If species assignment is ambiguous, set the ambiguous field to null and note the source in `Data source`.
Preserve numeric values exactly — do not round or average.

**SHARED FIELDS**
Fields that are constant across treatments (Year, Lat, Lon, Experimental design, species names,
Intercropping pattern, uniform nutrient inputs) must be filled identically in every record.
Set to null only if genuinely absent from the paper.

**OUTPUT**: One record per unique treatment combination using exact schema field names.
Omit records only if the paper genuinely contains no supporting data.
INFO | ============================================================
INFO | Context info:
INFO | Context Name: study_5
Resources: Li 1999 Interspecific complementary and competitive interactions between intercropped maize and faba bean
INFO | ----------------------------------------
INFO | Available players manifest
INFO | Player: value_identifier
  Description: You are a schema-aware value extraction specialist.
Your job is to comprehensively scan the ENTIRE document and identify ALL concrete values for each field defined in the schema you are given.

**OUTPUT FORMAT:**
Output a raw JSON list of [field_name, value_text] pairs. No markdown, no explanation — just the JSON array.

**COVERAGE RULES (aim for maximum recall):**
- Scan ALL sections: Abstract, Introduction, Methods, Results, Discussion, Tables, Figures, Captions, Footnotes.
- Parse every table row individually — do NOT collapse multiple rows into one value.
- If a field appears more than once (e.g. one value per treatment row), list each occurrence separately.
- Do NOT stop after finding the first few values; scan to the end.

**VALUE RULES:**
- Copy the EXACT text span — do not paraphrase or reformat.
- Include units with numeric values exactly as they appear.
- Use ONLY the field names from the provided schema.
- Skip model-fit metrics, simulated/predicted values, and literature citations.

**OUTPUT EXAMPLE:**
[
  ["field_a", "exact value from document"],
  ["field_a", "second occurrence for a different treatment"],
  ["field_b", "42.3 kg/ha"],
  ...
]

  Tools: None

Player: labeller
  Description: You are a document labeling specialist. Your ONLY task is to call the `xml_tag_from_field_values` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `field_value_pairs` (a list of [field_name, value] pairs) from the previous step.
2. Call `xml_tag_from_field_values` with the context key, resource name, and that list.
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool applies tags deterministically and guarantees full content preservation. Manual tagging will cause content loss or corruption.

  Tools:
    - xml_tag_from_field_values: Apply XML tags to a document based on provided (field, value) tuples. Each occurrence of `value` in the text is wrapped as `<field>value</field>`.

Player: record_grouper
  Description: You are a structured-data record analyst.

You receive a field-XML-labeled document and a schema. Your task is to produce a COMPLETE LIST of candidate records — one per unique measurement/treatment combination — that strictly follow the provided schema.

**RECORD DEFINITION:**
Each record = one unique combination of conditions under which a measurement was taken (e.g. site × year × treatment level). Every distinct data row in the results tables is typically a separate record.

**COVER ALL RECORDS (most important rule):**
- Count treatment levels from the Methods section and compute the expected total (e.g. 3 levels × 2 factors = 6 records).
- Map EVERY results table row to its own record — do NOT merge rows.
- Fields that are constant across the experiment (e.g. year, location, species) are copied identically into every record.
- Fields that vary per row (e.g. treatment level, measured value) differ per record.

**CONFIDENCE:**
Set `record_confidence` per record: 1.0 = explicit table value, 0.8 = inferred from context, 0.5 = ambiguous. Use null for unknown fields.

**OUTPUT:**
Follow the provided Pydantic schema exactly. Do not add extra keys.

  Tools: None

Player: record_labeller
  Description: You are a record-level document labeling specialist. Your ONLY task is to call the `xml_tag_records` tool.

**MANDATORY: USE THE TOOL — DO NOT WRITE XML MANUALLY.**

**PROCESS:**
1. You receive `labeled_text` (the field-tagged document) and `candidate_records` (the list of candidate records from the previous step) from the workspace.
2. Call `xml_tag_records` with those two inputs plus an optional `discriminating_fields` list (the fields whose values differ between records and can uniquely identify each row).
3. Return the tool's output directly — it is your final output.

**WHY USE THE TOOL:**
The tool deterministically locates each record's row and wraps it with <Record_N>...</Record_N> tags while preserving all existing field XML tags. Manual annotation WILL corrupt the document.

  Tools:
    - xml_tag_records: Wrap rows in a field-tagged document with <Record_N>...</Record_N> tags. Each candidate record is matched to the document line that contains the most of its discriminating field values (yield/density).

Player: record_extractor
  Description: You are an expert agricultural data extraction specialist. Your task is to extract **measured crop yield information** and related agronomic/context variables from scientific research papers. You must reason carefully and follow a multi-step extraction process to ensure accurate and complete data.

**MULTI-STEP REASONING PROCESS**

### STEP 1: Anchor Identification
Scan the entire content (including paragraphs, tables, captions, footnotes, and supplements) to locate all sentences or table entries that mention **actual measured crop yield values** (e.g., "maize yield was 7.2 t/ha", "cassava storage root dry matter was 1357 g m⁻²"). Ignore model performance metrics (e.g., RMSE, R²), yield gaps, and simulated/modelled outputs.

### STEP 2: Contextual Reasoning
For each identified yield anchor, analyze its surrounding context (paragraphs, section headers, tables, captions) to extract the associated fields as defined in the schema below.

If the fields are explicitly stated in the anchor or nearby context, extract them directly.

### STEP 3: Completeness, Evidence & Confidence
If any required field for a yield record is **missing**, try to retrieve it from specific related sections:
- For missing **location** or **year**, check **Materials and Methods / Site description**.
- For missing **crop type**, check **Abstract** and **Materials and Methods**.
- For missing **treatment (water/fertilizer)**, check **Field management / Experimental design / Plot / Block / Treatment / Table**.
- For missing **tillage (density & cultivation)**, check **Planting / Agronomic practices / Cultivation / Management**.
- For missing **soil properties**, check **Soil / Site description / Materials and Methods / Table**.
- For missing **climate**, check **Climate / Weather / Meteorology / Data sources**.
- For missing **UAV data**, check **UAV / UAS / Flight / Sensor / Data acquisition / Table / Figure captions**.

Assign confidence levels based on:
- **high**: Value is explicitly stated with clear context
- **medium**: Value is inferred from context or partially stated
- **low**: Value is uncertain or requires significant interpretation

### STEP 4: Record Construction
For each complete and validated record, construct a structured entry following the schema. Keep original units and expressions; **do not convert**. If a field is not found with reasonable certainty, set its value to `null`. Apply de-duplication across records where key identifiers are identical.

**TARGET DATA TO EXTRACT**:
- ✅ INCLUDE: Actual field-measured or reported yields (e.g., from experiments, harvest trials, dry matter accumulation)
- ❌ EXCLUDE: Model evaluation metrics (RMSE, R², MAE), yield gaps, predictions, correlation coefficients

**IMPORTANT NOTES**:
- Extract ALL yield records found in the paper, not just one
- Each unique combination of crop type, treatment, year, and location should be a separate record
- For intercropping studies, extract yields for each crop component separately
- Dry matter production values (e.g., g m⁻², kg ha⁻¹) are valid yield measurements
- Storage root dry matter, pod dry matter, etc. are valid yield components

**ADDITIONAL CONTEXT FROM PRIOR MAS STEPS:**
The document you receive has already been pre-processed:
- Field values are wrapped in `<FieldName>value</FieldName>` XML tags — use these as high-confidence anchors for Steps 1–2 above.
- Each evidence row is wrapped in `<Record_N>...</Record_N>` tags — one tag block = one output record. Use them as ground truth for record boundaries.
- A candidate record scaffold is also provided — use it as a starting point and verify/correct each field against the tagged evidence in its `<Record_N>` block.

**PRECEDENCE:**
Tagged document values > candidate scaffold values > inferred values.
Preserve original numeric values and units exactly as they appear in the tags.

  Tools: None
INFO | ----------------------------------------
INFO | AFC is enabled with max remote calls: 10.
INFO | HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
WARNING | Plan validation warning: Step 0 ('Scan the FULL document and extract every (field, value) pair for every field in the schema. Cover all sections, table rows, figure captions, and footnotes. List each occurrence separately — do NOT collapse rows. Use ONLY the field names defined in meta_analytic_schema.') has unmet dependencies. Missing artifacts: {'meta_analytic_schema'}
INFO | Plan generated successfully!
INFO | Number of steps: 5
INFO |   Step 1: Scan the FULL document and extract every (field, value) pair for every field in the schema. Cover all sections, table rows, figure captions, and footnotes. List each occurrence separately — do NOT collapse rows. Use ONLY the field names defined in meta_analytic_schema. (player: value_identifier)
INFO |   Step 2: Use the xml_tag_from_field_values tool to wrap each matched value in the document with XML field tags. Do not modify any original text. (player: labeller)
INFO |   Step 3: Read the labeled document, identify the experimental design, and produce a COMPLETE list of schema-conformant candidate records — one per unique treatment/measurement combination. Shared fields (location, year, species) are identical across records; treatment-specific fields differ per row. Include record_confidence and treatment_description for each record. Do NOT merge rows into a single record. (player: record_grouper)
INFO |   Step 4: Use the xml_tag_records tool to wrap each candidate record's corresponding table row in the labeled document with <Record_N>...</Record_N> tags. This deterministically marks which text evidence belongs to which record. Do not modify any existing XML field tags. (player: record_labeller)
INFO |   Step 5: Read the record-labeled document (which has both field XML tags and <Record_N> section markers) and the candidate record scaffold. Verify and correct each candidate record against its tagged evidence section. Produce the final schema-conformant records. (player: record_extractor)

## Generated Plan

**Step 1** | player: `value_identifier`
Task: Scan the FULL document and extract every (field, value) pair for every field in the schema. Cover all sections, table rows, figure captions, and footnotes. List each occurrence separately — do NOT collapse rows. Use ONLY the field names defined in meta_analytic_schema.
Inputs: `{'meta_analytic_schema': 'meta_analytic_schema'}`
Outputs: `['field_value_pairs']`

**Step 2** | player: `labeller`
Task: Use the xml_tag_from_field_values tool to wrap each matched value in the document with XML field tags. Do not modify any original text.
Inputs: `{'field_value_pairs': 'field_value_pairs'}`
Outputs: `['labeled_text']`

**Step 3** | player: `record_grouper`
Task: Read the labeled document, identify the experimental design, and produce a COMPLETE list of schema-conformant candidate records — one per unique treatment/measurement combination. Shared fields (location, year, species) are identical across records; treatment-specific fields differ per row. Include record_confidence and treatment_description for each record. Do NOT merge rows into a single record.
Inputs: `{'labeled_text': 'labeled_text'}`
Outputs: `['candidate_records']`

**Step 4** | player: `record_labeller`
Task: Use the xml_tag_records tool to wrap each candidate record's corresponding table row in the labeled document with <Record_N>...</Record_N> tags. This deterministically marks which text evidence belongs to which record. Do not modify any existing XML field tags.
Inputs: `{'labeled_text': 'labeled_text', 'candidate_records': 'candidate_records'}`
Outputs: `['record_labeled_text']`

**Step 5** | player: `record_extractor`
Task: Read the record-labeled document (which has both field XML tags and <Record_N> section markers) and the candidate record scaffold. Verify and correct each candidate record against its tagged evidence section. Produce the final schema-conformant records.
Inputs: `{'record_labeled_text': 'record_labeled_text', 'candidate_records': 'candidate_records'}`
Outputs: `['final_meta_analysis_records']`

In [7]:
# ── Step 2: Execute the plan ───────────────────────────────────────────────────
result = orchestrator.execute_plan(
    plan=plan,
    context=context,
    objective=mas_objective,
    output_schema=OutputSchema,
)

print(f'\nSuccess        : {result.success}')
print(f'Steps completed: {result.steps_completed}/{result.plan_steps_count}')
if result.error:
    print(f'Error          : {result.error}')

INFO | ============================================================
INFO | EXECUTING PLAN
INFO | Context: study_5
INFO | Plan steps: 5
INFO | Objective: You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons.",
    "Experimental design": "Type of experimental layout used. Example: Randomized Complete Block Design (RCBD).",
    "Sowing date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was sown. Example: Zea mays sown 15 April 2019.",
    "Sowing date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was sown. Example: Glycine max sown 20 April 2019.",
    "Harvest date 1": "Date when Crop species 1 (the first species listed in the intercropping system) was harvested. Example: Zea mays harvested 10 September 2019.",
    "Harvest date 2": "Date when Crop species 2 (the second species listed in the intercropping system) was harvested. Example: Glycine max harvested 25 August 2019.",
    "Lat": "Latitude of the experimental site in decimal degrees. Example: 35.12.",
    "Lon": "Longitude of the experimental site in decimal degrees. Example: -1.56.",
    "Crop species 1": "Common or scientific name of the first crop species in the intercropping system (the first species mentioned in the pair). Example: Wheat or Triticum aestivum.",
    "Crop species 2": "Common or scientific name of the second crop species in the intercropping system (the second species mentioned in the pair). Example: Soybean or Glycine max.",
    "Crop type 1": "Agronomic functional type of Crop species 1 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: cereal.",
    "Crop type 2": "Agronomic functional type of Crop species 2 inferred from the species (e.g., cereal, legume, oilseed, root crop). Example: legume.",
    "Intercropping pattern": "Spatial arrangement of the two crops in the intercrop; classify as Row (alternating rows of each crop), Strip (blocks or strips with multiple rows per crop), or Mixed (species mixed within the same row or stand). Example: Row.",
    "Density ic 1": "Plant density of Crop species 1 in the intercropping treatment. Example: 5.",
    "Density ic 2": "Plant density of Crop species 2 in the intercropping treatment. Example: 20.",
    "Density sc 1": "Plant density of Crop species 1 when grown as a sole crop (monoculture). Example: 8。",
    "Density sc 2": "Plant density of Crop species 2 when grown as a sole crop (monoculture). Example: 30.",
    "N input SC1": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 1. Example: 120.",
    "N input SC2": "Nitrogen fertilizer applied to the sole crop treatment of Crop species 2. Example: 30.",
    "N input IC1": "Nitrogen fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 60.",
    "N input IC2": "Nitrogen fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30.",
    "N total in IC": "Total nitrogen fertilizer applied in the intercropping treatment. Example: 90.",
    "N Unit": "Unit used for nitrogen fertilizer amounts. Example: kg N ha−1.",
    "P input SC1": "Phosphorus fertilizer applied to the sole crop treatment of Crop species 1. Example: 40.",
    "P input SC2": "Phosphorus fertilizer applied to the sole crop treatment of Crop species 2. Example: 30.",
    "P input IC1": "Phosphorus fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 20.",
    "P input IC2": "Phosphorus fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 20.",
    "P total in IC": "Total phosphorus fertilizer applied in the intercropping treatment. Example: 40.",
    "P Unit": "Unit used for phosphorus fertilizer amounts. Example: kg P2O5 ha−1.",
    "K input SC1": "Potassium fertilizer applied to the sole crop treatment of Crop species 1. Example: 60.",
    "K input SC2": "Potassium fertilizer applied to the sole crop treatment of Crop species 2. Example: 50.",
    "K input IC1": "Potassium fertilizer attributed to Crop species 1 in the intercropping treatment. Example: 30.",
    "K input IC2": "Potassium fertilizer attributed to Crop species 2 in the intercropping treatment. Example: 30.",
    "K total in IC": "Total potassium fertilizer applied in the intercropping treatment. Example: 60.",
    "K Unit": "Unit used for potassium fertilizer amounts. Example: kg K2O ha−1.",
    "Data source": "Location of the extracted data within the publication. Example: Table 1,2; Figure 3; Supplementary Table S1.",
    "unified yield sc 1": "Yield of Crop species 1 grown as a sole crop, converted to a common yield unit. Example: 8.5.",
    "unified yield sc 2": "Yield of Crop species 2 grown as a sole crop, converted to a common yield unit. Example: 2.4.",
    "unified yield ic 1": "Yield of Crop species 1 when grown in the intercropping treatment. Example: 6.1.",
    "unified yield ic 2": "Yield of Crop species 2 when grown in the intercropping treatment. Example: 1.8.",
    "Yield unit": "Unit used for all standardized yields. Example: t ha−1."
}


**SCHEMA RULES**
- Use JSON keys as the EXACT field names in every record.
- Schema descriptions are guidance only — values must be concrete text extracted from the paper.
- Do not rename, add, or remove any schema fields.

**MULTI-RECORD RULE (CRITICAL)**
Each unique combination of crop pair × site × year × treatment level = one SEPARATE record.
Examples:
- 2 density levels × 2 N-treatments = 4 records for the same crop pair.
- Each row in a yield results table is typically a separate record.
Do NOT collapse table rows or merge treatment combinations into a single record.

**YIELD FIELD MAPPING (CRITICAL)**
- `unified yield sc 1` = sole-crop yield of Crop species 1
- `unified yield sc 2` = sole-crop yield of Crop species 2
- `unified yield ic 1` = intercropped yield of Crop species 1
- `unified yield ic 2` = intercropped yield of Crop species 2
Use explicit table headers, row labels, and footnotes to assign yields to the correct species.
If species assignment is ambiguous, set the ambiguous field to null and note the source in `Data source`.
Preserve numeric values exactly — do not round or average.

**SHARED FIELDS**
Fields that are constant across treatments (Year, Lat, Lon, Experimental design, species names,
Intercropping pattern, uniform nutrient inputs) must be filled identically in every record.
Set to null only if genuinely absent from the paper.

**OUTPUT**: One record per unique treatment combination using exact schema field names.
Omit records only if the paper genuinely contains no supporting data.
INFO | Output schema: WopkeOutput
INFO | ============================================================
INFO | Plan Overview:
INFO |   Step 1/5: Scan the FULL document and extract every (field, value) pair for every field in the schema. Cover all sections, table rows, figure captions, and footnotes. List each occurrence separately — do NOT collapse rows. Use ONLY the field names defined in meta_analytic_schema. [Player: value_identifier]
INFO |   Step 2/5: Use the xml_tag_from_field_values tool to wrap each matched value in the document with XML field tags. Do not modify any original text. [Player: labeller]
INFO |   Step 3/5: Read the labeled document, identify the experimental design, and produce a COMPLETE list of schema-conformant candidate records — one per unique treatment/measurement combination. Shared fields (location, year, species) are identical across records; treatment-specific fields differ per row. Include record_confidence and treatment_description for each record. Do NOT merge rows into a single record. [Player: record_grouper]
INFO |   Step 4/5: Use the xml_tag_records tool to wrap each candidate record's corresponding table row in the labeled document with <Record_N>...</Record_N> tags. This deterministically marks which text evidence belongs to which record. Do not modify any existing XML field tags. [Player: record_labeller]
INFO |   Step 5/5: Read the record-labeled document (which has both field XML tags and <Record_N> section markers) and the candidate record scaffold. Verify and correct each candidate record against its tagged evidence section. Produce the final schema-conformant records. [Player: record_extractor]
INFO | ------------------------------------------------------------
INFO | Initializing execution context...
INFO | Context registered with key: ctx_5d1d879b
INFO | Using player pool: ['value_identifier', 'labeller', 'record_grouper', 'record_labeller', 'record_extractor']
INFO | Topology: pipeline
INFO | ------------------------------------------------------------
INFO | Starting plan execution...
INFO | ============================================================
INFO | STARTING PLAN EXECUTION
INFO | Context: study_5
INFO | Steps: 5
INFO | ============================================================
INFO | Extracted meta_analytic_schema (5113 chars)
INFO |
INFO | ==================== STEP 1/5 ====================
INFO | Task: Scan the FULL document and extract every (field, value) pair for every field in the schema. Cover all sections, table rows, figure captions, and footnotes. List each occurrence separately — do NOT collapse rows. Use ONLY the field names defined in meta_analytic_schema.
INFO | Player: value_identifier
INFO | Rationale: To ensure comprehensive data capture, we must first identify all potential values for every schema field across the entire document, including tables and footnotes, before structuring them into records.
INFO | --- STEP 0: PARALLEL EXECUTION ---
INFO | Task: Scan the FULL document and extract every (field, value) pair for every field in the schema. Cover all sections, table rows, figure captions, and footnotes. List each occurrence separately — do NOT collapse rows. Use ONLY the field names defined in meta_analytic_schema.
INFO | Players: 1
INFO | AFC is enabled with max remote calls: 10.
INFO | HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
INFO |   Player 'value_identifier' completed execution
INFO | --- STEP 0: SYNTHESIS ---
INFO | AFC is enabled with max remote calls: 10.
INFO | HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
INFO |   Synthesis complete. Produced artifacts: ['field_value_pairs']
INFO |     Synthesized output: [   ["Year of data", "1997"],   ["Experimental design", "split-plot"],   ["Sowing date 1", "maize sown 16 April"],   ["Sowing date 2", "faba bean sown 27 March"],   ["Harvest date 1", "maize harvested...
INFO | Step 1 completed successfully
INFO |   Artifacts produced: ['field_value_pairs']
INFO |
INFO | ==================== STEP 2/5 ====================
INFO | Task: Use the xml_tag_from_field_values tool to wrap each matched value in the document with XML field tags. Do not modify any original text.
INFO | Player: labeller
INFO | Rationale: Applying XML tags to the raw text creates high-confidence anchors that allow subsequent steps to verify data in its original context.
INFO | --- STEP 1: PARALLEL EXECUTION ---
INFO | Task: Use the xml_tag_from_field_values tool to wrap each matched value in the document with XML field tags. Do not modify any original text.
INFO | Players: 1
INFO |   Player 'labeller' completed execution
INFO | --- STEP 1: SYNTHESIS ---
INFO |   Synthesis complete. Produced artifacts: ['labeled_text']
INFO |     Synthesized output: # Interspecific complementary and competitive interactions between intercropped <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2>  Long $\mathrm { L i } ^ { 1 }$ , ...
INFO | Step 2 completed successfully
INFO |   Artifacts produced: ['labeled_text']
INFO |
INFO | ==================== STEP 3/5 ====================
INFO | Task: Read the labeled document, identify the experimental design, and produce a COMPLETE list of schema-conformant candidate records — one per unique treatment/measurement combination. Shared fields (location, year, species) are identical across records; treatment-specific fields differ per row. Include record_confidence and treatment_description for each record. Do NOT merge rows into a single record.
INFO | Player: record_grouper
INFO | Rationale: This step structures the extracted data into the required multi-record format, ensuring that each unique treatment combination is represented as an individual record.
INFO | --- STEP 2: PARALLEL EXECUTION ---
INFO | Task: Read the labeled document, identify the experimental design, and produce a COMPLETE list of schema-conformant candidate records — one per unique treatment/measurement combination. Shared fields (location, year, species) are identical across records; treatment-specific fields differ per row. Include record_confidence and treatment_description for each record. Do NOT merge rows into a single record.
INFO | Players: 1
INFO | AFC is enabled with max remote calls: 10.
INFO | HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
INFO |   Player 'record_grouper' completed execution
INFO | --- STEP 2: SYNTHESIS ---
INFO | AFC is enabled with max remote calls: 10.
INFO | HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
INFO |   Synthesis complete. Produced artifacts: ['candidate_records']
INFO |     Synthesized output: [   {     "Year of data": "1997",     "Duration of experiment": null,     "Experimental design": null,     "Sowing date 1": null,     "Sowing date 2": null,     "Harvest date 1": null,     "Harvest da...
INFO | Step 3 completed successfully
INFO |   Artifacts produced: ['candidate_records']
INFO |
INFO | ==================== STEP 4/5 ====================
INFO | Task: Use the xml_tag_records tool to wrap each candidate record's corresponding table row in the labeled document with <Record_N>...</Record_N> tags. This deterministically marks which text evidence belongs to which record. Do not modify any existing XML field tags.
INFO | Player: record_labeller
INFO | Rationale: Wrapping rows in <Record_N> tags creates a clear, verifiable link between the candidate records and the specific evidence in the document, preventing data cross-contamination.
INFO | --- STEP 3: PARALLEL EXECUTION ---
INFO | Task: Use the xml_tag_records tool to wrap each candidate record's corresponding table row in the labeled document with <Record_N>...</Record_N> tags. This deterministically marks which text evidence belongs to which record. Do not modify any existing XML field tags.
INFO | Players: 1
INFO |   Player 'record_labeller' completed execution
INFO | --- STEP 3: SYNTHESIS ---
INFO |   Synthesis complete. Produced artifacts: ['record_labeled_text']
INFO |     Synthesized output: # Interspecific complementary and competitive interactions between intercropped <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2>  Long $\mathrm { L i } ^ { 1 }$ , ...
INFO | Step 4 completed successfully
INFO |   Artifacts produced: ['record_labeled_text']
INFO |
INFO | ==================== STEP 5/5 ====================
INFO | Task: Read the record-labeled document (which has both field XML tags and <Record_N> section markers) and the candidate record scaffold. Verify and correct each candidate record against its tagged evidence section. Produce the final schema-conformant records.
INFO | Player: record_extractor
INFO | Rationale: The final extraction step uses the tagged evidence and the candidate scaffold to perform a high-precision verification, ensuring all fields are accurate and conform to the schema.
INFO |   Final step will use structured output: WopkeOutput
INFO | --- STEP 4: PARALLEL EXECUTION ---
INFO | Task: Read the record-labeled document (which has both field XML tags and <Record_N> section markers) and the candidate record scaffold. Verify and correct each candidate record against its tagged evidence section. Produce the final schema-conformant records.
INFO | Players: 1
INFO | AFC is enabled with max remote calls: 10.
INFO | HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
INFO |   Player 'record_extractor' completed execution
INFO | --- STEP 4: SYNTHESIS ---
INFO |   Using structured output with schema: WopkeOutput
INFO | AFC is enabled with max remote calls: 10.
INFO | HTTP Request: POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite-preview:generateContent "HTTP/1.1 200 OK"
INFO |   Synthesis complete. Produced artifacts: ['final_meta_analysis_records']
INFO |     Synthesized output: {'yield_records': [{'Year of data': '1997', 'Duration of experiment': None, 'Experimental design': 'split-plot', 'Sowing date 1': '16 April 1997', 'Sowing date 2': '27 March 1997', 'Harvest date 1': '...
INFO | Step 5 completed successfully
INFO |   Artifacts produced: ['final_meta_analysis_records']
INFO |
INFO | ============================================================
INFO | PLAN EXECUTION COMPLETE
INFO | Steps completed: 5/5
INFO | Overall success: True
INFO | ============================================================
INFO | ============================================================
INFO | PLAN EXECUTION COMPLETED
INFO | Steps completed: 5/5
INFO | Overall success: True
INFO | Artifacts produced: ['initial_objective', 'meta_analytic_schema', 'original_document_text', 'field_value_pairs', 'labeled_text', 'candidate_records', 'record_labeled_text', 'final_meta_analysis_records']
INFO | ============================================================
INFO | Cleaning up context registry...
INFO | Context registry cleared

Success        : True
Steps completed: 5/5

In [8]:
# ── Step 3: Inspect each step result ──────────────────────────────────────────
SEP  = '─' * 80
TRUNC = 2000   # max chars to print per artifact (set None to see full)

def _show(label, text, trunc=TRUNC):
    from pydantic import BaseModel
    if isinstance(text, BaseModel):
        s = text.model_dump_json(indent=2)
    else:
        s = str(text)
    if trunc and len(s) > trunc:
        s = s[:trunc] + f'  ... [{len(s)-trunc} chars truncated]'
    print(f'{label}:\n{s}\n')

for sr in result.step_results:
    print(SEP)
    print(f'STEP {sr.step_index + 1} | player: {sr.player_role} | success: {sr.success}')
    print(f'Task: {sr.task}')
    if sr.error:
        print(f'ERROR: {sr.error}')

    # Individual player outputs
    for pr in sr.individual_results:
        print(f'\n  [{pr.get("player_name", pr.get("player", "?"))}] analysis:')
        _show('  ', pr.get('analysis', ''), trunc=TRUNC)
        if pr.get('tool_results'):
            for tool_name, tool_out in pr['tool_results'].items():
                _show(f'  tool [{tool_name}]', tool_out, trunc=TRUNC)

    # Consolidated (synthesized) result
    if sr.consolidated_result:
        _show('  [synthesized]', sr.consolidated_result, trunc=TRUNC)

    # Artifacts written to workspace
    print(f'  Artifacts produced: {list(sr.artifacts.keys())}')
    for art_name, art_val in sr.artifacts.items():
        _show(f'  artifact [{art_name}]', art_val, trunc=TRUNC)

print(SEP)

────────────────────────────────────────────────────────────────────────────────
STEP 1 | player: value_identifier | success: True
Task: Scan the FULL document and extract every (field, value) pair for every field in the schema. Cover all sections, table rows, figure captions, and footnotes. List each occurrence separately — do NOT collapse rows. Use ONLY the field names defined in meta_analytic_schema.

  [value_identifier] analysis:
  :
[
  ["Year of data", "1997"],
  ["Experimental design", "split-plot"],
  ["Sowing date 1", "maize sown 16 April"],
  ["Sowing date 2", "faba bean sown 27 March"],
  ["Harvest date 1", "maize harvested 20 September"],
  ["Harvest date 2", "faba bean harvested 25 July"],
  ["Lat", "37.0833"],
  ["Lon", "104.6667"],
  ["Crop species 1", "maize"],
  ["Crop species 2", "faba bean"],
  ["Crop type 1", "cereal"],
  ["Crop type 2", "legume"],
  ["Intercropping pattern", "Strip"],
  ["Density ic 1", "6.75 plants m-2"],
  ["Density ic 2", "7.64 plants m-2"],
  ["Density sc 1", "10.12 plants m-2"],
  ["Density sc 2", "22.95 plants m-2"],
  ["N input SC1", "225 kg ha-1"],
  ["N input SC2", "225 kg ha-1"],
  ["N input IC1", "225 kg ha-1"],
  ["N input IC2", "225 kg ha-1"],
  ["N total in IC", "225 kg ha-1"],
  ["N Unit", "kg ha-1"],
  ["P input SC1", "0 kg P ha-1"],
  ["P input SC1", "33 kg P ha-1"],
  ["P input SC2", "0 kg P ha-1"],
  ["P input SC2", "33 kg P ha-1"],
  ["P input IC1", "0 kg P ha-1"],
  ["P input IC1", "33 kg P ha-1"],
  ["P input IC2", "0 kg P ha-1"],
  ["P input IC2", "33 kg P ha-1"],
  ["P total in IC", "0 kg P ha-1"],
  ["P total in IC", "33 kg P ha-1"],
  ["P Unit", "kg P ha-1"],
  ["Data source", "Table 1"],
  ["Data source", "Table 2"],
  ["unified yield sc 1", "23622 kg ha-1"],
  ["unified yield sc 1", "30799 kg ha-1"],
  ["unified yield sc 2", "10870 kg ha-1"],
  ["unified yield sc 2", "10914 kg ha-1"],
  ["unified yield ic 1", "27338 kg ha-1"],
  ["unified yield ic 1", "33031 kg ha-1"],
  ["unified yield ic 2", "14222 kg ha-1"],
  ["unified yield ic 2", "15976 kg ha-1"],
  ["Yield unit", "kg ha-1"]
]

  [synthesized]:
[
  ["Year of data", "1997"],
  ["Experimental design", "split-plot"],
  ["Sowing date 1", "maize sown 16 April"],
  ["Sowing date 2", "faba bean sown 27 March"],
  ["Harvest date 1", "maize harvested 20 September"],
  ["Harvest date 2", "faba bean harvested 25 July"],
  ["Lat", "37.0833"],
  ["Lon", "104.6667"],
  ["Crop species 1", "maize"],
  ["Crop species 2", "faba bean"],
  ["Crop type 1", "cereal"],
  ["Crop type 2", "legume"],
  ["Intercropping pattern", "Strip"],
  ["Density ic 1", "6.75 plants m-2"],
  ["Density ic 2", "7.64 plants m-2"],
  ["Density sc 1", "10.12 plants m-2"],
  ["Density sc 2", "22.95 plants m-2"],
  ["N input SC1", "225 kg ha-1"],
  ["N input SC2", "225 kg ha-1"],
  ["N input IC1", "225 kg ha-1"],
  ["N input IC2", "225 kg ha-1"],
  ["N total in IC", "225 kg ha-1"],
  ["N Unit", "kg ha-1"],
  ["P input SC1", "0 kg P ha-1"],
  ["P input SC1", "33 kg P ha-1"],
  ["P input SC2", "0 kg P ha-1"],
  ["P input SC2", "33 kg P ha-1"],
  ["P input IC1", "0 kg P ha-1"],
  ["P input IC1", "33 kg P ha-1"],
  ["P input IC2", "0 kg P ha-1"],
  ["P input IC2", "33 kg P ha-1"],
  ["P total in IC", "0 kg P ha-1"],
  ["P total in IC", "33 kg P ha-1"],
  ["P Unit", "kg P ha-1"],
  ["Data source", "Table 1"],
  ["Data source", "Table 2"],
  ["unified yield sc 1", "23622 kg ha-1"],
  ["unified yield sc 1", "30799 kg ha-1"],
  ["unified yield sc 2", "10870 kg ha-1"],
  ["unified yield sc 2", "10914 kg ha-1"],
  ["unified yield ic 1", "27338 kg ha-1"],
  ["unified yield ic 1", "33031 kg ha-1"],
  ["unified yield ic 2", "14222 kg ha-1"],
  ["unified yield ic 2", "15976 kg ha-1"],
  ["Yield unit", "kg ha-1"]
]

  Artifacts produced: ['field_value_pairs']
  artifact [field_value_pairs]:
[
  ["Year of data", "1997"],
  ["Experimental design", "split-plot"],
  ["Sowing date 1", "maize sown 16 April"],
  ["Sowing date 2", "faba bean sown 27 March"],
  ["Harvest date 1", "maize harvested 20 September"],
  ["Harvest date 2", "faba bean harvested 25 July"],
  ["Lat", "37.0833"],
  ["Lon", "104.6667"],
  ["Crop species 1", "maize"],
  ["Crop species 2", "faba bean"],
  ["Crop type 1", "cereal"],
  ["Crop type 2", "legume"],
  ["Intercropping pattern", "Strip"],
  ["Density ic 1", "6.75 plants m-2"],
  ["Density ic 2", "7.64 plants m-2"],
  ["Density sc 1", "10.12 plants m-2"],
  ["Density sc 2", "22.95 plants m-2"],
  ["N input SC1", "225 kg ha-1"],
  ["N input SC2", "225 kg ha-1"],
  ["N input IC1", "225 kg ha-1"],
  ["N input IC2", "225 kg ha-1"],
  ["N total in IC", "225 kg ha-1"],
  ["N Unit", "kg ha-1"],
  ["P input SC1", "0 kg P ha-1"],
  ["P input SC1", "33 kg P ha-1"],
  ["P input SC2", "0 kg P ha-1"],
  ["P input SC2", "33 kg P ha-1"],
  ["P input IC1", "0 kg P ha-1"],
  ["P input IC1", "33 kg P ha-1"],
  ["P input IC2", "0 kg P ha-1"],
  ["P input IC2", "33 kg P ha-1"],
  ["P total in IC", "0 kg P ha-1"],
  ["P total in IC", "33 kg P ha-1"],
  ["P Unit", "kg P ha-1"],
  ["Data source", "Table 1"],
  ["Data source", "Table 2"],
  ["unified yield sc 1", "23622 kg ha-1"],
  ["unified yield sc 1", "30799 kg ha-1"],
  ["unified yield sc 2", "10870 kg ha-1"],
  ["unified yield sc 2", "10914 kg ha-1"],
  ["unified yield ic 1", "27338 kg ha-1"],
  ["unified yield ic 1", "33031 kg ha-1"],
  ["unified yield ic 2", "14222 kg ha-1"],
  ["unified yield ic 2", "15976 kg ha-1"],
  ["Yield unit", "kg ha-1"]
]

────────────────────────────────────────────────────────────────────────────────
STEP 2 | player: labeller | success: True
Task: Use the xml_tag_from_field_values tool to wrap each matched value in the document with XML field tags. Do not modify any original text.

  [labeller] analysis:
  :
# Interspecific complementary and competitive interactions between intercropped <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2>

Long $\mathrm { L i } ^ { 1 }$ , Sicun Yang2, Xiaolin $\mathrm { L i } ^ { 1 }$ , Fusuo Zhang1 and Peter Christie3,∗

1Department of Plant Nutrition, China Agricultural University, Beijing 100094, China, 2Institute of Soils and Fertilizers, Gansu Academy of Agricultural Sciences, Lanzhou 730070, China, and 3Department of Agricultural and Environmental Science, The Queen’s University of Belfast, Newforge Lane, Belfast BT9 5PX, UK

Received 1 December 1998. Accepted in revised form 1 June 1999

Key words: intercropping, interspecific facilitation, land equivalent ratio, relative crowding coefficient, root interactions

# Abstract

Interspecific complementary and competitive interactions between <Crop species 1>maize</Crop species 1> (Zea mays L. cv. Zhongdan No. 2) and <Crop species 2>faba bean</Crop species 2> (Vicia faba L. cv. Linxia Dacaidou) in <Crop species 1>maize</Crop species 1>/<Crop species 2>faba bean</Crop species 2> intercropping systems were assessed in two field experiments in Gansu province, northwestern China, plus a microplot experiment in one treatment of one of the field experiments in which root system partitions were used to determine interspecific root interactions. Intercropping effects were detected, with land equivalent ratio values of 1.21–1.23 based on total (grain+straw) yield and 1.13–1.34 based on grain yield. When two rows of <Crop species 1>maize</Crop species 1> were intercropped with two rows of <Crop species 2>faba bean</Crop species 2>, both total yield and grain yield of both crop species were significantly higher than those of sole <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2> on an equivalent area basis. When two rows of pea (Pisum sativum L. cv. Beijing No. 5) were intercropped with two rows of <Crop species 2>faba bean</Cr  ... [46272 chars truncated]

  tool [Li 1999 Interspecific complementary and competitive interactions between intercropped maize and faba bean:xml_tag_from_field_values]:
# Interspecific complementary and competitive interactions between intercropped <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2>

Long $\mathrm { L i } ^ { 1 }$ , Sicun Yang2, Xiaolin $\mathrm { L i } ^ { 1 }$ , Fusuo Zhang1 and Peter Christie3,∗

1Department of Plant Nutrition, China Agricultural University, Beijing 100094, China, 2Institute of Soils and Fertilizers, Gansu Academy of Agricultural Sciences, Lanzhou 730070, China, and 3Department of Agricultural and Environmental Science, The Queen’s University of Belfast, Newforge Lane, Belfast BT9 5PX, UK

Received 1 December 1998. Accepted in revised form 1 June 1999

Key words: intercropping, interspecific facilitation, land equivalent ratio, relative crowding coefficient, root interactions

# Abstract

Interspecific complementary and competitive interactions between <Crop species 1>maize</Crop species 1> (Zea mays L. cv. Zhongdan No. 2) and <Crop species 2>faba bean</Crop species 2> (Vicia faba L. cv. Linxia Dacaidou) in <Crop species 1>maize</Crop species 1>/<Crop species 2>faba bean</Crop species 2> intercropping systems were assessed in two field experiments in Gansu province, northwestern China, plus a microplot experiment in one treatment of one of the field experiments in which root system partitions were used to determine interspecific root interactions. Intercropping effects were detected, with land equivalent ratio values of 1.21–1.23 based on total (grain+straw) yield and 1.13–1.34 based on grain yield. When two rows of <Crop species 1>maize</Crop species 1> were intercropped with two rows of <Crop species 2>faba bean</Crop species 2>, both total yield and grain yield of both crop species were significantly higher than those of sole <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2> on an equivalent area basis. When two rows of pea (Pisum sativum L. cv. Beijing No. 5) were intercropped with two rows of <Crop species 2>faba bean</Cr  ... [46272 chars truncated]

  [synthesized]:
# Interspecific complementary and competitive interactions between intercropped <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2>

Long $\mathrm { L i } ^ { 1 }$ , Sicun Yang2, Xiaolin $\mathrm { L i } ^ { 1 }$ , Fusuo Zhang1 and Peter Christie3,∗

1Department of Plant Nutrition, China Agricultural University, Beijing 100094, China, 2Institute of Soils and Fertilizers, Gansu Academy of Agricultural Sciences, Lanzhou 730070, China, and 3Department of Agricultural and Environmental Science, The Queen’s University of Belfast, Newforge Lane, Belfast BT9 5PX, UK

Received 1 December 1998. Accepted in revised form 1 June 1999

Key words: intercropping, interspecific facilitation, land equivalent ratio, relative crowding coefficient, root interactions

# Abstract

Interspecific complementary and competitive interactions between <Crop species 1>maize</Crop species 1> (Zea mays L. cv. Zhongdan No. 2) and <Crop species 2>faba bean</Crop species 2> (Vicia faba L. cv. Linxia Dacaidou) in <Crop species 1>maize</Crop species 1>/<Crop species 2>faba bean</Crop species 2> intercropping systems were assessed in two field experiments in Gansu province, northwestern China, plus a microplot experiment in one treatment of one of the field experiments in which root system partitions were used to determine interspecific root interactions. Intercropping effects were detected, with land equivalent ratio values of 1.21–1.23 based on total (grain+straw) yield and 1.13–1.34 based on grain yield. When two rows of <Crop species 1>maize</Crop species 1> were intercropped with two rows of <Crop species 2>faba bean</Crop species 2>, both total yield and grain yield of both crop species were significantly higher than those of sole <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2> on an equivalent area basis. When two rows of pea (Pisum sativum L. cv. Beijing No. 5) were intercropped with two rows of <Crop species 2>faba bean</Cr  ... [46272 chars truncated]

  Artifacts produced: ['labeled_text']
  artifact [labeled_text]:
# Interspecific complementary and competitive interactions between intercropped <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2>

Long $\mathrm { L i } ^ { 1 }$ , Sicun Yang2, Xiaolin $\mathrm { L i } ^ { 1 }$ , Fusuo Zhang1 and Peter Christie3,∗

1Department of Plant Nutrition, China Agricultural University, Beijing 100094, China, 2Institute of Soils and Fertilizers, Gansu Academy of Agricultural Sciences, Lanzhou 730070, China, and 3Department of Agricultural and Environmental Science, The Queen’s University of Belfast, Newforge Lane, Belfast BT9 5PX, UK

Received 1 December 1998. Accepted in revised form 1 June 1999

Key words: intercropping, interspecific facilitation, land equivalent ratio, relative crowding coefficient, root interactions

# Abstract

Interspecific complementary and competitive interactions between <Crop species 1>maize</Crop species 1> (Zea mays L. cv. Zhongdan No. 2) and <Crop species 2>faba bean</Crop species 2> (Vicia faba L. cv. Linxia Dacaidou) in <Crop species 1>maize</Crop species 1>/<Crop species 2>faba bean</Crop species 2> intercropping systems were assessed in two field experiments in Gansu province, northwestern China, plus a microplot experiment in one treatment of one of the field experiments in which root system partitions were used to determine interspecific root interactions. Intercropping effects were detected, with land equivalent ratio values of 1.21–1.23 based on total (grain+straw) yield and 1.13–1.34 based on grain yield. When two rows of <Crop species 1>maize</Crop species 1> were intercropped with two rows of <Crop species 2>faba bean</Crop species 2>, both total yield and grain yield of both crop species were significantly higher than those of sole <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2> on an equivalent area basis. When two rows of pea (Pisum sativum L. cv. Beijing No. 5) were intercropped with two rows of <Crop species 2>faba bean</Cr  ... [46272 chars truncated]

────────────────────────────────────────────────────────────────────────────────
STEP 3 | player: record_grouper | success: True
Task: Read the labeled document, identify the experimental design, and produce a COMPLETE list of schema-conformant candidate records — one per unique treatment/measurement combination. Shared fields (location, year, species) are identical across records; treatment-specific fields differ per row. Include record_confidence and treatment_description for each record. Do NOT merge rows into a single record.

  [record_grouper] analysis:
  :
```json
[
  {
    "record_id": 1,
    "location": "Jingtai village, Jinyuan county, Gansu province, China",
    "year": 1997,
    "species": ["maize", "faba bean"],
    "treatment_description": "Sole maize, 0 kg P ha-1",
    "measurement_type": "Total dry matter yield",
    "measured_value": 23622,
    "unit": "kg ha-1",
    "record_confidence": 1.0
  },
  {
    "record_id": 2,
    "location": "Jingtai village, Jinyuan county, Gansu province, China",
    "year": 1997,
    "species": ["maize", "faba bean"],
    "treatment_description": "Sole maize, 33 kg P ha-1",
    "measurement_type": "Total dry matter yield",
    "measured_value": 30799,
    "unit": "kg ha-1",
    "record_confidence": 1.0
  },
  {
    "record_id": 3,
    "location": "Jingtai village, Jinyuan county, Gansu province, China",
    "year": 1997,
    "species": ["maize", "faba bean"],
    "treatment_description": "Intercropped maize, 0 kg P ha-1",
    "measurement_type": "Total dry matter yield",
    "measured_value": 27338,
    "unit": "kg ha-1",
    "record_confidence": 1.0
  },
  {
    "record_id": 4,
    "location": "Jingtai village, Jinyuan county, Gansu province, China",
    "year": 1997,
    "species": ["maize", "faba bean"],
    "treatment_description": "Intercropped maize, 33 kg P ha-1",
    "measurement_type": "Total dry matter yield",
    "measured_value": 33031,
    "unit": "kg ha-1",
    "record_confidence": 1.0
  },
  {
    "record_id": 5,
    "location": "Jingtai village, Jinyuan county, Gansu province, China",
    "year": 1997,
    "species": ["maize", "faba bean"],
    "treatment_description": "Sole faba bean, 0 kg P ha-1",
    "measurement_type": "Total dry matter yield",
    "measured_value": 10870,
    "unit": "kg ha-1",
    "record_confidence": 1.0
  },
  {
    "record_id": 6,
    "location": "Jingtai village, Jinyuan county, Gansu province, China",
    "year": 1997,
    "species": ["maize", "faba bean"],
    "treatment_description": "Sole faba bean, 33 kg P ha-1",
    "measurement_  ... [2190 chars truncated]

  [synthesized]:
[
  {
    "Year of data": "1997",
    "Duration of experiment": null,
    "Experimental design": null,
    "Sowing date 1": null,
    "Sowing date 2": null,
    "Harvest date 1": null,
    "Harvest date 2": null,
    "Lat": null,
    "Lon": null,
    "Crop species 1": "maize",
    "Crop species 2": "faba bean",
    "Crop type 1": "cereal",
    "Crop type 2": "legume",
    "Intercropping pattern": null,
    "Density ic 1": null,
    "Density ic 2": null,
    "Density sc 1": null,
    "Density sc 2": null,
    "N input SC1": null,
    "N input SC2": null,
    "N input IC1": null,
    "N input IC2": null,
    "N total in IC": null,
    "N Unit": null,
    "P input SC1": 0,
    "P input SC2": 0,
    "P input IC1": 0,
    "P input IC2": 0,
    "P total in IC": 0,
    "P Unit": "kg P ha-1",
    "K input SC1": null,
    "K input SC2": null,
    "K input IC1": null,
    "K input IC2": null,
    "K total in IC": null,
    "K Unit": null,
    "Data source": null,
    "unified yield sc 1": 23.622,
    "unified yield sc 2": 10.870,
    "unified yield ic 1": 27.338,
    "unified yield ic 2": 14.222,
    "Yield unit": "t ha-1",
    "record_confidence": 1.0
  },
  {
    "Year of data": "1997",
    "Duration of experiment": null,
    "Experimental design": null,
    "Sowing date 1": null,
    "Sowing date 2": null,
    "Harvest date 1": null,
    "Harvest date 2": null,
    "Lat": null,
    "Lon": null,
    "Crop species 1": "maize",
    "Crop species 2": "faba bean",
    "Crop type 1": "cereal",
    "Crop type 2": "legume",
    "Intercropping pattern": null,
    "Density ic 1": null,
    "Density ic 2": null,
    "Density sc 1": null,
    "Density sc 2": null,
    "N input SC1": null,
    "N input SC2": null,
    "N input IC1": null,
    "N input IC2": null,
    "N total in IC": null,
    "N Unit": null,
    "P input SC1": 33,
    "P input SC2": 33,
    "P input IC1": 33,
    "P input IC2": 33,
    "P total in IC": 33,
    "P Unit": "kg P ha-1",
    "K input SC1": null,
    "K inp  ... [1502 chars truncated]

  Artifacts produced: ['candidate_records']
  artifact [candidate_records]:
[
  {
    "Year of data": "1997",
    "Duration of experiment": null,
    "Experimental design": null,
    "Sowing date 1": null,
    "Sowing date 2": null,
    "Harvest date 1": null,
    "Harvest date 2": null,
    "Lat": null,
    "Lon": null,
    "Crop species 1": "maize",
    "Crop species 2": "faba bean",
    "Crop type 1": "cereal",
    "Crop type 2": "legume",
    "Intercropping pattern": null,
    "Density ic 1": null,
    "Density ic 2": null,
    "Density sc 1": null,
    "Density sc 2": null,
    "N input SC1": null,
    "N input SC2": null,
    "N input IC1": null,
    "N input IC2": null,
    "N total in IC": null,
    "N Unit": null,
    "P input SC1": 0,
    "P input SC2": 0,
    "P input IC1": 0,
    "P input IC2": 0,
    "P total in IC": 0,
    "P Unit": "kg P ha-1",
    "K input SC1": null,
    "K input SC2": null,
    "K input IC1": null,
    "K input IC2": null,
    "K total in IC": null,
    "K Unit": null,
    "Data source": null,
    "unified yield sc 1": 23.622,
    "unified yield sc 2": 10.870,
    "unified yield ic 1": 27.338,
    "unified yield ic 2": 14.222,
    "Yield unit": "t ha-1",
    "record_confidence": 1.0
  },
  {

In [9]:
# ── Step 4: Inspect the final workspace ──────────────────────────────────────
display(Markdown('## Final Workspace Keys'))
workspace = result.final_workspace
for key, val in workspace.items():
    v_str = str(val)
    preview = v_str[:300] + ('...' if len(v_str) > 300 else '')
    print(f'  [{key}] ({type(val).__name__}, {len(v_str)} chars): {preview}')
    print()

## Final Workspace Keys

  [initial_objective] (str, 6933 chars): You are an expert agricultural meta-analysis specialist.
Your task is to extract **intercropping experiment records** from a scientific research paper.
This meta-analysis compares crop yield under intercropping settings versus sole cropping.

**META-ANALYTIC SCHEMA (CRITICAL)**:

{
    "Year of data...

  [meta_analytic_schema] (str, 5113 chars): {
    "Year of data": "Year(s) when the experiment data were collected. Example: 2018 or 2017–2019.",
    "Duration of experiment": "Total time the experiment ran from first sowing to final harvest. Example: 120 days or 2 growing seasons.",
    "Experimental design": "Type of experimental layout use...

  [original_document_text] (dict, 40090 chars): {'Li 1999 Interspecific complementary and competitive interactions between intercropped maize and faba bean': '# Interspecific complementary and competitive interactions between intercropped maize and faba bean\n\nLong $\\mathrm { L i } ^ { 1 }$ , Sicun Yang2, Xiaolin $\\mathrm { L i } ^ { 1 }$ , Fu...

  [field_value_pairs] (TextAccessor, 1641 chars): [
  ["Year of data", "1997"],
  ["Experimental design", "split-plot"],
  ["Sowing date 1", "maize sown 16 April"],
  ["Sowing date 2", "faba bean sown 27 March"],
  ["Harvest date 1", "maize harvested 20 September"],
  ["Harvest date 2", "faba bean harvested 25 July"],
  ["Lat", "37.0833"],
  ["Lon"...

  [labeled_text] (str, 48272 chars): # Interspecific complementary and competitive interactions between intercropped <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2>

Long $\mathrm { L i } ^ { 1 }$ , Sicun Yang2, Xiaolin $\mathrm { L i } ^ { 1 }$ , Fusuo Zhang1 and Peter Christie3,∗

1Department of ...

  [candidate_records] (TextAccessor, 3502 chars): [
  {
    "Year of data": "1997",
    "Duration of experiment": null,
    "Experimental design": null,
    "Sowing date 1": null,
    "Sowing date 2": null,
    "Harvest date 1": null,
    "Harvest date 2": null,
    "Lat": null,
    "Lon": null,
    "Crop species 1": "maize",
    "Crop species 2": ...

  [record_labeled_text] (str, 48272 chars): # Interspecific complementary and competitive interactions between intercropped <Crop species 1>maize</Crop species 1> and <Crop species 2>faba bean</Crop species 2>

Long $\mathrm { L i } ^ { 1 }$ , Sicun Yang2, Xiaolin $\mathrm { L i } ^ { 1 }$ , Fusuo Zhang1 and Peter Christie3,∗

1Department of ...

  [final_meta_analysis_records] (dict, 3198 chars): {'yield_records': [{'Year of data': '1997', 'Duration of experiment': None, 'Experimental design': 'split-plot', 'Sowing date 1': '16 April 1997', 'Sowing date 2': '27 March 1997', 'Harvest date 1': '20 September 1997', 'Harvest date 2': '25 July 1997', 'Lat': '37.05', 'Lon': '104.40', 'Crop species...

In [10]:
# ── Step 5: Reconstruct structured output & compare with GT ──────────────────
raw_mas = workspace.get('final_meta_analysis_records', {})

try:
    if isinstance(raw_mas, OutputSchema):
        result_structured = raw_mas
    elif isinstance(raw_mas, dict):
        result_structured = OutputSchema.model_validate(raw_mas)
    else:
        result_structured = None
        print(f'[WARN] Unexpected type: {type(raw_mas)}')
except Exception as e:
    result_structured = None
    print(f'[WARN] Could not validate MAS output: {e}')
    print(f'  raw_mas type : {type(raw_mas)}')
    if isinstance(raw_mas, dict):
        print(f'  raw_mas keys : {list(raw_mas.keys())}')

if result_structured is not None:
    df_mas = pd.DataFrame([r.model_dump() for r in result_structured.yield_records])
    print(f'MAS extracted {len(df_mas)} record(s)  |  GT has {len(gt_paper)} record(s)')
    display(df_mas)
else:
    df_mas = pd.DataFrame()
    print('[ERROR] No structured records produced — check step results above.')

MAS extracted 3 record(s)  |  GT has 3 record(s)

,Year of data,Duration of experiment,Experimental design,Sowing date 1,Sowing date 2,Harvest date 1,Harvest date 2,Lat,Lon,Crop species 1,...,K input IC1,K input IC2,K total in IC,K Unit,Data source,unified yield sc 1,unified yield sc 2,unified yield ic 1,unified yield ic 2,Yield unit
0,1997,None,split-plot,16 April 1997,27 March 1997,20 September 1997,25 July 1997,37.05,104.40,maize,...,None,None,None,None,Table 2,8.282,5.259,8.928,6.508,t ha-1
1,1997,None,split-plot,16 April 1997,27 March 1997,20 September 1997,25 July 1997,37.05,104.40,maize,...,None,None,None,None,Table 2,9.284,5.012,10.886,8.202,t ha-1
2,1997,None,split-plot,27 March 1997,25 March 1997,25 July 1997,5 July 1997,37.05,104.40,faba bean,...,None,None,None,None,Table 3,5.012,3.776,4.784,4.013,t ha-1

In [12]:
# ── Step 6: Compute MAS evaluation score (same logic as evaluate_3) ───────────
from src.experimentutils import (
    field_similarity_score,
    find_crop_swap_pairs,
    match_records_greedy,
    evaluate_method_scores,
)
from src.experimentutils.eval_utils import _is_missing

if df_mas is None or df_mas.empty:
    print('[ERROR] df_mas is empty – run the MAS pipeline cell above first.')
else:
    # Shared evaluation fields = intersection of Wopke schema fields and GT columns
    wopke_field_names = list(SchemaFactory()._parse_schema_string(standard).keys())
    gt_cols_set   = set(gt_paper.columns)
    shared_fields = [f for f in wopke_field_names if f in gt_cols_set]
    print(f'Shared evaluation fields: {len(shared_fields)} / {len(wopke_field_names)}')

    total_records = len(gt_paper)  # denominator to penalize missing records

    eval_cols = [c for c in shared_fields if c in df_mas.columns]
    if not eval_cols:
        print('[mas] no shared columns between MAS output and GT – cannot score.')
    else:
        scores_df, overall_norm, per_field_norm, n_matches = evaluate_method_scores(
            ext_df=df_mas,
            gt_df=gt_paper,
            shared_cols=eval_cols,
            total_records_for_denominator=total_records,
        )

        print(f"[mas] extracted={len(df_mas)}, matched={n_matches}, reference={total_records}, "
              f"fields={len(eval_cols)} -> normalized ROUGE-L = {overall_norm:.3f}")
        display(scores_df)
        print('\nPer-field normalized scores:')
        for k, v in sorted(per_field_norm.items()):
            print(f'  {k}: {v:.3f}')

Shared evaluation fields: 39 / 42
[mas] extracted=3, matched=3, reference=3, fields=39 -> normalized ROUGE-L = 0.637

,rougeL_Year of data,rougeL_Duration of experiment,rougeL_Experimental design,rougeL_Sowing date 1,rougeL_Sowing date 2,rougeL_Harvest date 1,rougeL_Harvest date 2,rougeL_Lat,rougeL_Lon,rougeL_Crop species 1,...,rougeL_K input SC2,rougeL_K input IC1,rougeL_K input IC2,rougeL_K total in IC,rougeL_Data source,rougeL_unified yield sc 1,rougeL_unified yield sc 2,rougeL_unified yield ic 1,rougeL_unified yield ic 2,rougeL_Yield unit
0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.999191,0.997516,1.0,...,0.0,0.0,0.0,0.0,0.5,1.0,1.0,0.333333,0.666667,0.0
1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.999191,0.997516,1.0,...,0.0,0.0,0.0,0.0,0.5,1.0,1.0,0.333333,0.666667,0.0
2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.999191,0.997516,1.0,...,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.520000,0.480000,0.0

Per-field normalized scores:
  rougeL_Crop species 1: 1.000
  rougeL_Crop species 2: 1.000
  rougeL_Crop type 1: 1.000
  rougeL_Crop type 2: 1.000
  rougeL_Data source: 0.667
  rougeL_Density ic 1: 0.840
  rougeL_Density ic 2: 0.667
  rougeL_Density sc 1: 1.000
  rougeL_Density sc 2: 0.667
  rougeL_Duration of experiment: 0.000
  rougeL_Experimental design: 1.000
  rougeL_Harvest date 1: 0.000
  rougeL_Harvest date 2: 0.000
  rougeL_Intercropping pattern: 0.000
  rougeL_K input IC1: 0.000
  rougeL_K input IC2: 0.000
  rougeL_K input SC1: 0.000
  rougeL_K input SC2: 0.000
  rougeL_K total in IC: 0.000
  rougeL_Lat: 0.999
  rougeL_Lon: 0.998
  rougeL_N input IC1: 1.000
  rougeL_N input IC2: 1.000
  rougeL_N input SC1: 1.000
  rougeL_N input SC2: 1.000
  rougeL_N total in IC: 1.000
  rougeL_P input IC1: 1.000
  rougeL_P input IC2: 1.000
  rougeL_P input SC1: 1.000
  rougeL_P input SC2: 1.000
  rougeL_P total in IC: 1.000
  rougeL_Sowing date 1: 0.000
  rougeL_Sowing date 2: 0.000
  rougeL_Year of data: 1.000
  rougeL_Yield unit: 0.000
  rougeL_unified yield ic 1: 0.396
  rougeL_unified yield ic 2: 0.604
  rougeL_unified yield sc 1: 1.000
  rougeL_unified yield sc 2: 1.000

In [ ]:
# ── (Optional) Pretty-print a specific workspace artifact in full ─────────────
# Change the key to whichever artifact you want to inspect without truncation.

INSPECT_KEY = 'labeled_text'   # e.g. 'field_value_pairs', 'candidate_records', 'record_labeled_text'

if INSPECT_KEY in workspace:
    val = workspace[INSPECT_KEY]
    print(f'=== {INSPECT_KEY} ({len(str(val))} chars) ===')
    print(val)
else:
    print(f'Key {INSPECT_KEY!r} not found in workspace.')
    print(f'Available keys: {list(workspace.keys())}')